package edu.cs102.g04t06.game.execution.ai;

// Generated by Claude Sonnet 4.6

import edu.cs102.g04t06.game.rules.entities.ActionType;
import edu.cs102.g04t06.game.rules.entities.Card;
import edu.cs102.g04t06.game.rules.entities.GemColor;
import edu.cs102.g04t06.game.rules.valueobjects.Cost;
import edu.cs102.g04t06.game.rules.valueobjects.GemCollection;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.EnumMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("AIAction Tests")
class AIActionTest {

    private Card sampleCard;
    private GemCollection sampleGems;

    @BeforeEach
    void setUp() {
        Map<GemColor, Integer> costMap = new EnumMap<>(GemColor.class);
        costMap.put(GemColor.RED, 2);
        costMap.put(GemColor.BLUE, 1);
        sampleCard = new Card(2, 3, GemColor.RED, new Cost(costMap));

        sampleGems = new GemCollection()
                .add(GemColor.WHITE, 1)
                .add(GemColor.BLUE, 1)
                .add(GemColor.GREEN, 1);
    }

    // ==================== Constructor / getActionType() ====================

    @Test
    @DisplayName("getActionType returns PURCHASE_CARD")
    void getActionType_purchaseCard() {
        AIAction action = new AIAction(ActionType.PURCHASE_CARD, sampleCard, false, null, "buy");
        assertEquals(ActionType.PURCHASE_CARD, action.getActionType());
    }

    @Test
    @DisplayName("getActionType returns RESERVE_CARD")
    void getActionType_reserveCard() {
        AIAction action = new AIAction(ActionType.RESERVE_CARD, sampleCard, false, null, "reserve");
        assertEquals(ActionType.RESERVE_CARD, action.getActionType());
    }

    @Test
    @DisplayName("getActionType returns TAKE_THREE_DIFFERENT")
    void getActionType_takeThreeDifferent() {
        AIAction action = new AIAction(ActionType.TAKE_THREE_DIFFERENT, null, false, sampleGems, "take 3");
        assertEquals(ActionType.TAKE_THREE_DIFFERENT, action.getActionType());
    }

    @Test
    @DisplayName("getActionType returns TAKE_TWO_SAME")
    void getActionType_takeTwoSame() {
        GemCollection twoSame = new GemCollection().add(GemColor.RED, 2);
        AIAction action = new AIAction(ActionType.TAKE_TWO_SAME, null, false, twoSame, "take 2");
        assertEquals(ActionType.TAKE_TWO_SAME, action.getActionType());
    }

    // ==================== getTargetCard() ====================

    @Test
    @DisplayName("getTargetCard returns the card passed to constructor")
    void getTargetCard_returnsCard() {
        AIAction action = new AIAction(ActionType.PURCHASE_CARD, sampleCard, false, null, "buy");
        assertSame(sampleCard, action.getTargetCard());
    }

    @Test
    @DisplayName("getTargetCard returns null for gem-take actions")
    void getTargetCard_nullForGemActions() {
        AIAction action = new AIAction(ActionType.TAKE_THREE_DIFFERENT, null, false, sampleGems, "take 3");
        assertNull(action.getTargetCard());
    }

    @Test
    @DisplayName("getTargetCard returns null when explicitly set to null")
    void getTargetCard_explicitNull() {
        AIAction action = new AIAction(ActionType.RESERVE_CARD, null, false, null, "reserve from deck");
        assertNull(action.getTargetCard());
    }

    // ==================== isFromReserved() ====================

    @Test
    @DisplayName("isFromReserved returns true when purchasing from reserved hand")
    void isFromReserved_true() {
        AIAction action = new AIAction(ActionType.PURCHASE_CARD, sampleCard, true, null, "buy from reserve");
        assertTrue(action.isFromReserved());
    }

    @Test
    @DisplayName("isFromReserved returns false when purchasing from market")
    void isFromReserved_false() {
        AIAction action = new AIAction(ActionType.PURCHASE_CARD, sampleCard, false, null, "buy from market");
        assertFalse(action.isFromReserved());
    }

    @Test
    @DisplayName("isFromReserved defaults to false for gem-take actions")
    void isFromReserved_falseForGemActions() {
        AIAction action = new AIAction(ActionType.TAKE_THREE_DIFFERENT, null, false, sampleGems, "take 3");
        assertFalse(action.isFromReserved());
    }

    // ==================== getGemSelection() ====================

    @Test
    @DisplayName("getGemSelection returns the gem collection passed to constructor")
    void getGemSelection_returnsGems() {
        AIAction action = new AIAction(ActionType.TAKE_THREE_DIFFERENT, null, false, sampleGems, "take 3");
        assertSame(sampleGems, action.getGemSelection());
    }

    @Test
    @DisplayName("getGemSelection returns null for card-purchase actions")
    void getGemSelection_nullForPurchase() {
        AIAction action = new AIAction(ActionType.PURCHASE_CARD, sampleCard, false, null, "buy");
        assertNull(action.getGemSelection());
    }

    @Test
    @DisplayName("getGemSelection returns null for reserve actions")
    void getGemSelection_nullForReserve() {
        AIAction action = new AIAction(ActionType.RESERVE_CARD, sampleCard, false, null, "reserve");
        assertNull(action.getGemSelection());
    }

    @Test
    @DisplayName("getGemSelection reflects correct gem counts for TAKE_TWO_SAME")
    void getGemSelection_twoSameGems() {
        GemCollection twoRed = new GemCollection().add(GemColor.RED, 2);
        AIAction action = new AIAction(ActionType.TAKE_TWO_SAME, null, false, twoRed, "take 2 red");
        assertEquals(2, action.getGemSelection().getCount(GemColor.RED));
        assertEquals(2, action.getGemSelection().getTotalCount());
    }

    @Test
    @DisplayName("getGemSelection reflects correct gem counts for TAKE_THREE_DIFFERENT")
    void getGemSelection_threeDifferentGems() {
        AIAction action = new AIAction(ActionType.TAKE_THREE_DIFFERENT, null, false, sampleGems, "take 3");
        assertEquals(1, action.getGemSelection().getCount(GemColor.WHITE));
        assertEquals(1, action.getGemSelection().getCount(GemColor.BLUE));
        assertEquals(1, action.getGemSelection().getCount(GemColor.GREEN));
        assertEquals(3, action.getGemSelection().getTotalCount());
    }

    // ==================== getDescription() ====================

    @Test
    @DisplayName("getDescription returns the string passed to constructor")
    void getDescription_returnsString() {
        AIAction action = new AIAction(ActionType.PURCHASE_CARD, sampleCard, false, null, "AI buys RED card");
        assertEquals("AI buys RED card", action.getDescription());
    }

    @Test
    @DisplayName("getDescription returns empty string when empty")
    void getDescription_emptyString() {
        AIAction action = new AIAction(ActionType.RESERVE_CARD, sampleCard, false, null, "");
        assertEquals("", action.getDescription());
    }

    @Test
    @DisplayName("getDescription returns null when null passed")
    void getDescription_null() {
        AIAction action = new AIAction(ActionType.TAKE_THREE_DIFFERENT, null, false, sampleGems, null);
        assertNull(action.getDescription());
    }

    // ==================== Realistic scenario tests ====================

    @Test
    @DisplayName("Purchase from market: card set, fromReserved false, gems null")
    void scenario_purchaseFromMarket() {
        AIAction action = new AIAction(ActionType.PURCHASE_CARD, sampleCard, false, null, "AI purchases level 2 card");
        assertEquals(ActionType.PURCHASE_CARD, action.getActionType());
        assertSame(sampleCard, action.getTargetCard());
        assertFalse(action.isFromReserved());
        assertNull(action.getGemSelection());
        assertNotNull(action.getDescription());
    }

    @Test
    @DisplayName("Purchase from reserved hand: card set, fromReserved true, gems null")
    void scenario_purchaseFromReserved() {
        AIAction action = new AIAction(ActionType.PURCHASE_CARD, sampleCard, true, null, "AI buys reserved card");
        assertEquals(ActionType.PURCHASE_CARD, action.getActionType());
        assertSame(sampleCard, action.getTargetCard());
        assertTrue(action.isFromReserved());
        assertNull(action.getGemSelection());
    }

    @Test
    @DisplayName("Reserve card: card set, fromReserved false, gems null")
    void scenario_reserveCard() {
        AIAction action = new AIAction(ActionType.RESERVE_CARD, sampleCard, false, null, "AI reserves card");
        assertEquals(ActionType.RESERVE_CARD, action.getActionType());
        assertSame(sampleCard, action.getTargetCard());
        assertFalse(action.isFromReserved());
        assertNull(action.getGemSelection());
    }

    @Test
    @DisplayName("Take three different: card null, gems set")
    void scenario_takeThreeDifferent() {
        AIAction action = new AIAction(ActionType.TAKE_THREE_DIFFERENT, null, false, sampleGems, "AI takes 3 gems");
        assertEquals(ActionType.TAKE_THREE_DIFFERENT, action.getActionType());
        assertNull(action.getTargetCard());
        assertFalse(action.isFromReserved());
        assertNotNull(action.getGemSelection());
        assertEquals(3, action.getGemSelection().getTotalCount());
    }

    @Test
    @DisplayName("Take two same: card null, gems set with count 2")
    void scenario_takeTwoSame() {
        GemCollection twoBlue = new GemCollection().add(GemColor.BLUE, 2);
        AIAction action = new AIAction(ActionType.TAKE_TWO_SAME, null, false, twoBlue, "AI takes 2 blue");
        assertEquals(ActionType.TAKE_TWO_SAME, action.getActionType());
        assertNull(action.getTargetCard());
        assertEquals(2, action.getGemSelection().getCount(GemColor.BLUE));
    }
}
