package edu.cs102.g04t06.game.execution.ai;

// Generated by Claude Sonnet 4.6

import edu.cs102.g04t06.game.rules.GameState;
import edu.cs102.g04t06.game.rules.entities.ActionType;
import edu.cs102.g04t06.game.rules.entities.Card;
import edu.cs102.g04t06.game.rules.entities.GemColor;
import edu.cs102.g04t06.game.rules.entities.Noble;
import edu.cs102.g04t06.game.rules.entities.Player;
import edu.cs102.g04t06.game.rules.valueobjects.CardMarket;
import edu.cs102.g04t06.game.rules.valueobjects.Cost;
import edu.cs102.g04t06.game.rules.valueobjects.GemCollection;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests the AIStrategy interface contract using a minimal stub implementation.
 * Verifies that each of the three interface methods fulfils its documented contract
 * (correct return type, non-null where required, semantically correct values).
 */
@DisplayName("AIStrategy Interface Contract Tests")
class AIStrategyTest {

    // -----------------------------------------------------------------------
    // Minimal stub — always returns a fixed, deterministic answer.
    // Used to verify the interface is correctly typed and callable.
    // -----------------------------------------------------------------------
    private static class StubStrategy implements AIStrategy {
        private final AIAction fixedAction;
        private final Noble fixedNoble;
        private final GemCollection fixedReturn;

        StubStrategy(AIAction fixedAction, Noble fixedNoble, GemCollection fixedReturn) {
            this.fixedAction = fixedAction;
            this.fixedNoble = fixedNoble;
            this.fixedReturn = fixedReturn;
        }

        @Override
        public AIAction decideAction(GameState state, Player self) {
            return fixedAction;
        }

        @Override
        public Noble chooseNoble(List<Noble> claimable, GameState state, Player self) {
            return fixedNoble;
        }

        @Override
        public GemCollection chooseGemsToReturn(Player self, int excessCount, GameState state) {
            return fixedReturn;
        }
    }

    // -----------------------------------------------------------------------
    // Test fixtures
    // -----------------------------------------------------------------------
    private Player player;
    private GameState state;
    private Noble noble1;
    private Noble noble2;
    private List<Noble> claimableNobles;

    @BeforeEach
    void setUp() {
        player = new Player("TestAI", 0);

        // Minimal card market (needs 20 cards per level)
        List<Card> level1 = buildCardList(1, 20);
        List<Card> level2 = buildCardList(2, 30);
        List<Card> level3 = buildCardList(3, 20);
        CardMarket market = new CardMarket(level1, level2, level3);

        GemCollection bank = new GemCollection()
                .add(GemColor.WHITE, 7)
                .add(GemColor.BLUE, 7)
                .add(GemColor.GREEN, 7)
                .add(GemColor.RED, 7)
                .add(GemColor.BLACK, 7)
                .add(GemColor.GOLD, 5);

        Map<GemColor, Integer> req1 = new EnumMap<>(GemColor.class);
        req1.put(GemColor.WHITE, 3);
        req1.put(GemColor.BLUE, 3);
        noble1 = new Noble(1, "Queen", req1);

        Map<GemColor, Integer> req2 = new EnumMap<>(GemColor.class);
        req2.put(GemColor.RED, 4);
        noble2 = new Noble(2, "King", req2);

        claimableNobles = new ArrayList<>();
        claimableNobles.add(noble1);
        claimableNobles.add(noble2);

        List<Noble> availableNobles = new ArrayList<>(claimableNobles);
        state = new GameState(List.of(player), market, bank, availableNobles, 15);
    }

    // -----------------------------------------------------------------------
    // decideAction() contract
    // -----------------------------------------------------------------------

    @Test
    @DisplayName("decideAction: returns the AIAction produced by the strategy")
    void decideAction_returnsAction() {
        AIAction expectedAction = new AIAction(ActionType.TAKE_THREE_DIFFERENT, null, false,
                new GemCollection().add(GemColor.WHITE, 1).add(GemColor.BLUE, 1).add(GemColor.GREEN, 1),
                "take 3");
        AIStrategy strategy = new StubStrategy(expectedAction, noble1, new GemCollection());

        AIAction result = strategy.decideAction(state, player);

        assertSame(expectedAction, result);
    }

    @Test
    @DisplayName("decideAction: returned action has a non-null ActionType")
    void decideAction_actionTypeNotNull() {
        AIAction action = new AIAction(ActionType.PURCHASE_CARD, buildCard(1, 2, GemColor.WHITE), false, null, "buy");
        AIStrategy strategy = new StubStrategy(action, noble1, new GemCollection());

        AIAction result = strategy.decideAction(state, player);

        assertNotNull(result.getActionType());
    }

    @Test
    @DisplayName("decideAction: PURCHASE_CARD action carries a target card")
    void decideAction_purchaseCardHasTargetCard() {
        Card card = buildCard(2, 3, GemColor.RED);
        AIAction action = new AIAction(ActionType.PURCHASE_CARD, card, false, null, "buy");
        AIStrategy strategy = new StubStrategy(action, noble1, new GemCollection());

        AIAction result = strategy.decideAction(state, player);

        assertEquals(ActionType.PURCHASE_CARD, result.getActionType());
        assertNotNull(result.getTargetCard());
    }

    @Test
    @DisplayName("decideAction: RESERVE_CARD action carries a target card")
    void decideAction_reserveCardHasTargetCard() {
        Card card = buildCard(3, 5, GemColor.GREEN);
        AIAction action = new AIAction(ActionType.RESERVE_CARD, card, false, null, "reserve");
        AIStrategy strategy = new StubStrategy(action, noble1, new GemCollection());

        AIAction result = strategy.decideAction(state, player);

        assertEquals(ActionType.RESERVE_CARD, result.getActionType());
        assertNotNull(result.getTargetCard());
    }

    @Test
    @DisplayName("decideAction: TAKE_THREE_DIFFERENT action has gem selection with total 3")
    void decideAction_takeThreeDifferentHasGemSelection() {
        GemCollection gems = new GemCollection()
                .add(GemColor.WHITE, 1).add(GemColor.BLUE, 1).add(GemColor.GREEN, 1);
        AIAction action = new AIAction(ActionType.TAKE_THREE_DIFFERENT, null, false, gems, "take 3");
        AIStrategy strategy = new StubStrategy(action, noble1, new GemCollection());

        AIAction result = strategy.decideAction(state, player);

        assertEquals(ActionType.TAKE_THREE_DIFFERENT, result.getActionType());
        assertNotNull(result.getGemSelection());
        assertEquals(3, result.getGemSelection().getTotalCount());
    }

    @Test
    @DisplayName("decideAction: TAKE_TWO_SAME action has gem selection with total 2")
    void decideAction_takeTwoSameHasGemSelection() {
        GemCollection gems = new GemCollection().add(GemColor.RED, 2);
        AIAction action = new AIAction(ActionType.TAKE_TWO_SAME, null, false, gems, "take 2 red");
        AIStrategy strategy = new StubStrategy(action, noble1, new GemCollection());

        AIAction result = strategy.decideAction(state, player);

        assertEquals(ActionType.TAKE_TWO_SAME, result.getActionType());
        assertNotNull(result.getGemSelection());
        assertEquals(2, result.getGemSelection().getTotalCount());
    }

    @Test
    @DisplayName("decideAction: PURCHASE_CARD fromReserved flag is preserved")
    void decideAction_fromReservedFlagPreserved() {
        Card card = buildCard(1, 0, GemColor.BLACK);
        AIAction action = new AIAction(ActionType.PURCHASE_CARD, card, true, null, "buy reserved");
        AIStrategy strategy = new StubStrategy(action, noble1, new GemCollection());

        AIAction result = strategy.decideAction(state, player);

        assertTrue(result.isFromReserved());
    }

    // -----------------------------------------------------------------------
    // chooseNoble() contract
    // -----------------------------------------------------------------------

    @Test
    @DisplayName("chooseNoble: returns one of the claimable nobles")
    void chooseNoble_returnsNobleFromList() {
        AIStrategy strategy = new StubStrategy(null, noble1, new GemCollection());

        Noble chosen = strategy.chooseNoble(claimableNobles, state, player);

        assertTrue(claimableNobles.contains(chosen));
    }

    @Test
    @DisplayName("chooseNoble: does not return null when list is non-empty")
    void chooseNoble_nonNullForNonEmptyList() {
        AIStrategy strategy = new StubStrategy(null, noble2, new GemCollection());

        Noble chosen = strategy.chooseNoble(claimableNobles, state, player);

        assertNotNull(chosen);
    }

    @Test
    @DisplayName("chooseNoble: single noble in list — only valid choice returned")
    void chooseNoble_singleElementList() {
        List<Noble> singleNoble = List.of(noble1);
        AIStrategy strategy = new StubStrategy(null, noble1, new GemCollection());

        Noble chosen = strategy.chooseNoble(singleNoble, state, player);

        assertSame(noble1, chosen);
    }

    @Test
    @DisplayName("chooseNoble: returned noble has positive points")
    void chooseNoble_returnedNobleHasPoints() {
        AIStrategy strategy = new StubStrategy(null, noble1, new GemCollection());

        Noble chosen = strategy.chooseNoble(claimableNobles, state, player);

        assertTrue(chosen.getPoints() > 0);
    }

    @Test
    @DisplayName("chooseNoble: returned noble's requirements are non-null")
    void chooseNoble_requirementsNotNull() {
        AIStrategy strategy = new StubStrategy(null, noble2, new GemCollection());

        Noble chosen = strategy.chooseNoble(claimableNobles, state, player);

        assertNotNull(chosen.getRequirements());
    }

    // -----------------------------------------------------------------------
    // chooseGemsToReturn() contract
    // -----------------------------------------------------------------------

    @Test
    @DisplayName("chooseGemsToReturn: returns a non-null GemCollection")
    void chooseGemsToReturn_notNull() {
        GemCollection toReturn = new GemCollection().add(GemColor.WHITE, 1);
        AIStrategy strategy = new StubStrategy(null, noble1, toReturn);

        GemCollection result = strategy.chooseGemsToReturn(player, 1, state);

        assertNotNull(result);
    }

    @Test
    @DisplayName("chooseGemsToReturn: returned collection has exactly excessCount gems")
    void chooseGemsToReturn_exactCount() {
        GemCollection toReturn = new GemCollection()
                .add(GemColor.WHITE, 1).add(GemColor.BLUE, 1).add(GemColor.GREEN, 1);
        AIStrategy strategy = new StubStrategy(null, noble1, toReturn);

        GemCollection result = strategy.chooseGemsToReturn(player, 3, state);

        assertEquals(3, result.getTotalCount());
    }

    @Test
    @DisplayName("chooseGemsToReturn: returned collection for excess=1 has exactly 1 gem")
    void chooseGemsToReturn_exactlyOne() {
        GemCollection toReturn = new GemCollection().add(GemColor.BLACK, 1);
        AIStrategy strategy = new StubStrategy(null, noble1, toReturn);

        GemCollection result = strategy.chooseGemsToReturn(player, 1, state);

        assertEquals(1, result.getTotalCount());
    }

    @Test
    @DisplayName("chooseGemsToReturn: returned collection for excess=2 has exactly 2 gems")
    void chooseGemsToReturn_exactlyTwo() {
        GemCollection toReturn = new GemCollection().add(GemColor.RED, 2);
        AIStrategy strategy = new StubStrategy(null, noble1, toReturn);

        GemCollection result = strategy.chooseGemsToReturn(player, 2, state);

        assertEquals(2, result.getTotalCount());
    }

    @Test
    @DisplayName("chooseGemsToReturn: returned gems have non-negative counts per color")
    void chooseGemsToReturn_noNegativeCounts() {
        GemCollection toReturn = new GemCollection()
                .add(GemColor.WHITE, 1).add(GemColor.RED, 1);
        AIStrategy strategy = new StubStrategy(null, noble1, toReturn);

        GemCollection result = strategy.chooseGemsToReturn(player, 2, state);

        for (GemColor color : GemColor.values()) {
            assertTrue(result.getCount(color) >= 0,
                    "Negative count for color " + color);
        }
    }

    // -----------------------------------------------------------------------
    // Interface polymorphism — same variable, two strategies
    // -----------------------------------------------------------------------

    @Test
    @DisplayName("AIStrategy variable can hold different implementations")
    void polymorphism_differentStrategiesViaInterface() {
        Card card = buildCard(1, 0, GemColor.WHITE);
        AIAction actionA = new AIAction(ActionType.PURCHASE_CARD, card, false, null, "strategy A");
        AIAction actionB = new AIAction(ActionType.RESERVE_CARD, card, false, null, "strategy B");

        AIStrategy strategyA = new StubStrategy(actionA, noble1, new GemCollection());
        AIStrategy strategyB = new StubStrategy(actionB, noble2, new GemCollection());

        assertEquals(ActionType.PURCHASE_CARD, strategyA.decideAction(state, player).getActionType());
        assertEquals(ActionType.RESERVE_CARD,  strategyB.decideAction(state, player).getActionType());
    }

    @Test
    @DisplayName("Swapping strategy reference changes decision outcome")
    void polymorphism_strategySwap() {
        AIAction buyAction = new AIAction(ActionType.PURCHASE_CARD, buildCard(1, 0, GemColor.WHITE),
                false, null, "buy");
        AIAction takeAction = new AIAction(ActionType.TAKE_THREE_DIFFERENT, null, false,
                new GemCollection().add(GemColor.WHITE, 1).add(GemColor.BLUE, 1).add(GemColor.GREEN, 1),
                "take");

        AIStrategy current = new StubStrategy(buyAction, noble1, new GemCollection());
        assertEquals(ActionType.PURCHASE_CARD, current.decideAction(state, player).getActionType());

        current = new StubStrategy(takeAction, noble1, new GemCollection());
        assertEquals(ActionType.TAKE_THREE_DIFFERENT, current.decideAction(state, player).getActionType());
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    private Card buildCard(int level, int points, GemColor bonus) {
        Map<GemColor, Integer> costMap = new EnumMap<>(GemColor.class);
        costMap.put(GemColor.WHITE, 1);
        return new Card(level, points, bonus, new Cost(costMap));
    }

    private List<Card> buildCardList(int level, int count) {
        List<Card> cards = new ArrayList<>();
        GemColor[] colors = {GemColor.WHITE, GemColor.BLUE, GemColor.GREEN, GemColor.RED, GemColor.BLACK};
        for (int i = 0; i < count; i++) {
            Map<GemColor, Integer> costMap = new EnumMap<>(GemColor.class);
            costMap.put(colors[i % colors.length], 1 + (i % 3));
            cards.add(new Card(level, i % 4, colors[i % colors.length], new Cost(costMap)));
        }
        return cards;
    }
}
