//generated by Claude Opus 4.6

package edu.cs102.g04t06.game.execution.ai;

import java.util.ArrayList;
import java.util.Collections;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import edu.cs102.g04t06.game.rules.GameState;
import edu.cs102.g04t06.game.rules.entities.Card;
import edu.cs102.g04t06.game.rules.entities.GemColor;
import edu.cs102.g04t06.game.rules.entities.Noble;
import edu.cs102.g04t06.game.rules.entities.Player;
import edu.cs102.g04t06.game.rules.valueobjects.CardMarket;
import edu.cs102.g04t06.game.rules.valueobjects.Cost;
import edu.cs102.g04t06.game.rules.valueobjects.GemCollection;

@DisplayName("CardEvaluator Tests")
class CardEvaluatorTest {

    // =========================================================================
    // Shared fixtures
    // =========================================================================

    // Costs RED:2, BLUE:1 — cheap multi-colour card, bonus GREEN
    private Card cheapCard;

    // Costs RED:4, BLUE:3, GREEN:2 — expensive card, bonus WHITE
    private Card expensiveCard;

    // Player with no gems and no purchased cards
    private Player brokePlayer;

    // Player with exactly enough gems to afford cheapCard (RED:2, BLUE:1)
    private Player richPlayer;

    // Bank with 7 of every non-gold colour and 5 gold (standard Splendor start)
    private GemCollection fullBank;

    // Bank with nothing
    private GemCollection emptyBank;

    @BeforeEach
    void setUp() {
        // --- Cards ---
        Map<GemColor, Integer> cheapCost = new EnumMap<>(GemColor.class);
        cheapCost.put(GemColor.RED,  2);
        cheapCost.put(GemColor.BLUE, 1);
        cheapCard = new Card(1, 1, GemColor.GREEN, new Cost(cheapCost));

        Map<GemColor, Integer> expensiveCost = new EnumMap<>(GemColor.class);
        expensiveCost.put(GemColor.RED,   4);
        expensiveCost.put(GemColor.BLUE,  3);
        expensiveCost.put(GemColor.GREEN, 2);
        expensiveCard = new Card(2, 3, GemColor.WHITE, new Cost(expensiveCost));

        // --- Players ---
        brokePlayer = new Player("Broke", 1);

        richPlayer = new Player("Rich", 2);
        richPlayer.addGems(new GemCollection()
            .add(GemColor.RED,  2)
            .add(GemColor.BLUE, 1));

        // --- Banks ---
        fullBank = new GemCollection()
            .add(GemColor.RED,   7)
            .add(GemColor.BLUE,  7)
            .add(GemColor.GREEN, 7)
            .add(GemColor.WHITE, 7)
            .add(GemColor.BLACK, 7)
            .add(GemColor.GOLD,  5);

        emptyBank = new GemCollection();
    }

    // =========================================================================
    // Helper builders
    // =========================================================================

    /** Builds a Cost with a single colour requirement. */
    private Cost cost(GemColor color, int amount) {
        Map<GemColor, Integer> map = new EnumMap<>(GemColor.class);
        map.put(color, amount);
        return new Cost(map);
    }

    /**
     * Builds a minimal card (costs WHITE:1) with the given bonus colour.
     * Used to give players purchased card bonuses via addCard().
     */
    private Card minimalCard(GemColor bonus) {
        return new Card(1, 0, bonus, cost(GemColor.WHITE, 1));
    }

    private Noble noble(int id, Map<GemColor, Integer> requirements) {
        return new Noble(id, "Noble-" + id, requirements);
    }

    /** Builds a requirements map from colour-amount pairs. */
    private Map<GemColor, Integer> req(Object... pairs) {
        Map<GemColor, Integer> map = new EnumMap<>(GemColor.class);
        for (int i = 0; i < pairs.length; i += 2) {
            map.put((GemColor) pairs[i], (Integer) pairs[i + 1]);
        }
        return map;
    }

    private Player playerWithBonuses(GemColor color, int count) {
        Player p = new Player("BonusPlayer", 1);
        for (int i = 0; i < count; i++) {
            p.addCard(minimalCard(color));
        }
        return p;
    }

    // =========================================================================
    // FIX #1: Property-based card matching instead of reference equality.
    //
    // Card likely doesn't override equals(), so List.contains() uses ==.
    // After CardMarket shuffles, the original object may not be in the visible
    // slots — but a copy with identical properties is. This helper compares
    // by level, points, bonus, and per-colour cost.
    // =========================================================================

    /**
     * Returns true if the list contains at least one Card whose level, points,
     * bonus colour, and per-colour cost all match the target card.
     */
    private boolean containsMatchingCard(List<Card> cards, Card target) {
        for (Card c : cards) {
            if (c.getLevel() == target.getLevel()
                && c.getPoints() == target.getPoints()
                && c.getBonus() == target.getBonus()
                && sameCost(c.getCost(), target.getCost())) {
                return true;
            }
        }
        return false;
    }

    /** Returns true if two Cost objects require the same amount of each colour. */
    private boolean sameCost(Cost a, Cost b) {
        for (GemColor color : GemColor.values()) {
            if (color == GemColor.GOLD) continue;
            if (a.getRequired(color) != b.getRequired(color)) return false;
        }
        return true;
    }

    /**
     * Counts how many cards in the list match the target by properties.
     * Useful for asserting "at least N affordable cards of this type".
     */
    private long countMatchingCards(List<Card> cards, Card target) {
        long count = 0;
        for (Card c : cards) {
            if (c.getLevel() == target.getLevel()
                && c.getPoints() == target.getPoints()
                && c.getBonus() == target.getBonus()
                && sameCost(c.getCost(), target.getCost())) {
                count++;
            }
        }
        return count;
    }

    // =========================================================================
    // FIX #2: Market builders that avoid filler-card pollution.
    //
    // The original buildState padded empty tiers with cards costing WHITE:1
    // (via padToTwenty). For findAllAffordableCards tests this was fine because
    // those filler cards are cheap but irrelevant. For discountUtility, however,
    // the WHITE:1 filler (or all-colour filler in emptyState) polluted the
    // matching ratio.
    //
    // Solution:
    //   - For findAllAffordableCards: use buildStateForAffordability which pads
    //     with un-affordable filler (costs 7 of every colour).
    //   - For discountUtility: use buildStateForDiscount which pads with
    //     "neutral" filler whose cost matches the *same* colour as the tier's
    //     real card, so the ratio within each tier stays consistent. Empty tiers
    //     use filler that costs only BLACK:1 (a colour unlikely to be the bonus
    //     being tested with cheapCard/GREEN).
    // =========================================================================

    /**
     * Builds an un-affordable filler card (costs 7 of every non-GOLD colour).
     * No player in our test suite can afford this, and no reasonable bonus
     * colour query will accidentally match all 5 colours uniformly.
     */
    private Card unaffordableFiller() {
        Map<GemColor, Integer> map = new EnumMap<>(GemColor.class);
        for (GemColor c : GemColor.values()) {
            if (c != GemColor.GOLD) map.put(c, 7);
        }
        return new Card(1, 0, GemColor.WHITE, new Cost(map));
    }

    /**
     * Pads a list to 20 by repeating the first card (or a filler if empty).
     * The filler parameter controls what goes in when the list is empty.
     */
    private List<Card> padToTwenty(List<Card> cards, Card filler) {
        List<Card> padded = new ArrayList<>(cards);
        Card template = cards.isEmpty() ? filler : cards.get(0);
        while (padded.size() < 20) {
            padded.add(new Card(
                template.getLevel(),
                template.getPoints(),
                template.getBonus(),
                template.getCost()
            ));
        }
        return padded;
    }

    // --- Affordability builders ---

    /**
     * Builds a GameState for findAllAffordableCards tests.
     * Empty tiers are padded with un-affordable filler so they never produce
     * false positives.
     */
    private GameState stateWithTier1(Card... cards) {
        return buildStateForAffordability(
            new ArrayList<>(List.of(cards)),
            Collections.emptyList(),
            Collections.emptyList()
        );
    }

    private GameState stateWithAllTiers(List<Card> t1, List<Card> t2, List<Card> t3) {
        return buildStateForAffordability(
            new ArrayList<>(t1),
            new ArrayList<>(t2),
            new ArrayList<>(t3)
        );
    }

    private GameState buildStateForAffordability(List<Card> t1, List<Card> t2, List<Card> t3) {
        Card filler = unaffordableFiller();
        CardMarket market = new CardMarket(
            padToTwenty(t1, filler),
            padToTwenty(t2, filler),
            padToTwenty(t3, filler)
        );
        Player dummy = new Player("Dummy", 1);
        return new GameState(
            List.of(dummy), market, fullBank, Collections.emptyList(), 15
        );
    }

    /**
     * A market where every card is un-affordable — used as "empty" for
     * findAllAffordableCards tests. Because every filler costs 7 of all
     * colours, no test player can afford anything.
     */
    private GameState emptyAffordabilityState() {
        return buildStateForAffordability(
            Collections.emptyList(),
            Collections.emptyList(),
            Collections.emptyList()
        );
    }

    // --- Discount utility builders ---

    /**
     * Builds a GameState for discountUtility tests.
     *
     * Each tier is padded by repeating its own real card so the visible/deck
     * split after shuffle doesn't change the ratio.  Empty tiers are filled
     * with "neutral" filler that costs only BLACK:1 — this avoids accidentally
     * matching GREEN (cheapCard's bonus) or other colours under test.
     */
    private GameState buildStateForDiscount(List<Card> t1, List<Card> t2, List<Card> t3) {
        // Neutral filler: costs only BLACK:1, bonus RED.
        // Will NOT match GREEN (cheapCard's bonus) in any discountUtility test.
        Card neutralFiller = new Card(1, 0, GemColor.RED, cost(GemColor.BLACK, 1));
        CardMarket market = new CardMarket(
            padToTwenty(t1, neutralFiller),
            padToTwenty(t2, neutralFiller),
            padToTwenty(t3, neutralFiller)
        );
        Player dummy = new Player("Dummy", 1);
        return new GameState(
            List.of(dummy), market, fullBank, Collections.emptyList(), 15
        );
    }

    /**
     * A market where no visible card's cost includes GREEN (cheapCard's bonus).
     * All filler costs only BLACK:1, so discountUtility returns 0.0 for a
     * GREEN-bonus card.
     */
    private GameState emptyDiscountState() {
        return buildStateForDiscount(
            Collections.emptyList(),
            Collections.emptyList(),
            Collections.emptyList()
        );
    }

    // =========================================================================
    // 1. findAllAffordableCards
    // =========================================================================

    @Nested
    @DisplayName("findAllAffordableCards")
    class FindAllAffordableCardsTests {

        @Test
        @DisplayName("Returns empty list when market and reserved hand are both empty")
        void emptyMarketAndReserved_returnsEmptyList() {
            List<Card> result = CardEvaluator.findAllAffordableCards(
                emptyAffordabilityState(), brokePlayer);
            assertTrue(result.isEmpty());
        }

        @Test
        @DisplayName("Returns card when player has exactly the right single gem")
        void singleGem_cardIsAffordable() {
            Card singleGemCard = new Card(1, 0, GemColor.RED, cost(GemColor.WHITE, 1));
            Player p = new Player("SingleGem", 1);
            p.addGems(new GemCollection().add(GemColor.WHITE, 1));
            GameState state = stateWithTier1(singleGemCard);
            List<Card> result = CardEvaluator.findAllAffordableCards(state, p);
            assertTrue(containsMatchingCard(result, singleGemCard),
                "Result should contain a card matching singleGemCard by properties");
        }

        @Test
        @DisplayName("Does not return a card the player cannot afford")
        void cannotAffordExpensiveCard() {
            GameState state = stateWithTier1(expensiveCard);
            List<Card> result = CardEvaluator.findAllAffordableCards(state, brokePlayer);
            assertFalse(containsMatchingCard(result, expensiveCard),
                "Broke player should not be able to afford the expensive card");
        }

        @Test
        @DisplayName("Returns card when player has exactly enough gems")
        void exactGems_cardIsAffordable() {
            GameState state = stateWithTier1(cheapCard);
            List<Card> result = CardEvaluator.findAllAffordableCards(state, richPlayer);
            assertTrue(containsMatchingCard(result, cheapCard),
                "Result should contain a card matching cheapCard by properties");
        }

        @Test
        @DisplayName("Returns card when player has more than enough gems")
        void surplusGems_cardIsAffordable() {
            Player wealthy = new Player("Wealthy", 1);
            wealthy.addGems(new GemCollection()
                .add(GemColor.RED,  10)
                .add(GemColor.BLUE, 10));
            GameState state = stateWithTier1(cheapCard);
            List<Card> result = CardEvaluator.findAllAffordableCards(state, wealthy);
            assertTrue(containsMatchingCard(result, cheapCard),
                "Wealthy player should be able to afford cheapCard");
        }

        @Test
        @DisplayName("Scans all three tiers and returns affordable cards from each")
        void returnsCardsFromAllThreeTiers() {
            Map<GemColor, Integer> sameCost = new EnumMap<>(GemColor.class);
            sameCost.put(GemColor.RED,  2);
            sameCost.put(GemColor.BLUE, 1);
            Card tier1Card = new Card(1, 1, GemColor.GREEN, new Cost(sameCost));
            Card tier2Card = new Card(2, 1, GemColor.WHITE, new Cost(sameCost));
            Card tier3Card = new Card(3, 1, GemColor.BLACK, new Cost(sameCost));
            GameState state = stateWithAllTiers(
                List.of(tier1Card),
                List.of(tier2Card),
                List.of(tier3Card)
            );
            List<Card> result = CardEvaluator.findAllAffordableCards(state, richPlayer);
            // Each card has a unique level, so containsMatchingCard distinguishes them
            assertTrue(containsMatchingCard(result, tier1Card), "Should find tier 1 card");
            assertTrue(containsMatchingCard(result, tier2Card), "Should find tier 2 card");
            assertTrue(containsMatchingCard(result, tier3Card), "Should find tier 3 card");
        }

        @Test
        @DisplayName("Includes affordable card from reserved hand when market is empty")
        void affordableReservedCard_includedInResult() {
            richPlayer.addReservedCard(cheapCard);
            List<Card> result = CardEvaluator.findAllAffordableCards(
                emptyAffordabilityState(), richPlayer);
            // Reserved cards are the actual object (no shuffle), so contains() works
            assertTrue(result.contains(cheapCard));
        }

        @Test
        @DisplayName("Does not include unaffordable card from reserved hand")
        void unaffordableReservedCard_notIncluded() {
            brokePlayer.addReservedCard(expensiveCard);
            List<Card> result = CardEvaluator.findAllAffordableCards(
                emptyAffordabilityState(), brokePlayer);
            assertFalse(result.contains(expensiveCard));
        }

        @Test
        @DisplayName("Bonuses from purchased cards count toward affording a reserved card")
        void bonusesReduceCost_makingReservedCardAffordable() {
            Player p = playerWithBonuses(GemColor.RED, 4);
            p.addGems(new GemCollection()
                .add(GemColor.BLUE,  3)
                .add(GemColor.GREEN, 2));
            p.addReservedCard(expensiveCard);
            List<Card> result = CardEvaluator.findAllAffordableCards(
                emptyAffordabilityState(), p);
            assertTrue(result.contains(expensiveCard));
        }

        @Test
        @DisplayName("GOLD gems cover any colour deficit making the card affordable")
        void goldGems_actAsWild() {
            Player goldPlayer = new Player("Gold", 1);
            goldPlayer.addGems(new GemCollection().add(GemColor.GOLD, 3));
            GameState state = stateWithTier1(cheapCard);
            List<Card> result = CardEvaluator.findAllAffordableCards(state, goldPlayer);
            assertTrue(containsMatchingCard(result, cheapCard),
                "GOLD gems should cover the deficit, making cheapCard affordable");
        }

        @Test
        @DisplayName("Result contains no null entries")
        void resultContainsNoNullEntries() {
            Map<GemColor, Integer> sameCost = new EnumMap<>(GemColor.class);
            sameCost.put(GemColor.RED,  2);
            sameCost.put(GemColor.BLUE, 1);
            Card card1 = new Card(1, 1, GemColor.GREEN, new Cost(sameCost));
            Card card2 = new Card(1, 2, GemColor.WHITE, new Cost(sameCost));
            GameState state = stateWithTier1(card1, card2);
            List<Card> result = CardEvaluator.findAllAffordableCards(state, richPlayer);
            result.forEach(card ->
                assertNotNull(card, "Result list must not contain null entries"));
        }

        @Test
        @DisplayName("Player with no gems and no bonuses cannot afford any card with a cost")
        void brokePlayerCannotAffordCardWithCost() {
            Card minCard = new Card(1, 0, GemColor.BLUE, cost(GemColor.RED, 1));
            GameState state = stateWithTier1(minCard);
            List<Card> result = CardEvaluator.findAllAffordableCards(state, brokePlayer);
            assertFalse(containsMatchingCard(result, minCard),
                "Broke player should not afford any card with a cost");
        }
    }

    // =========================================================================
    // 2. calculateDeficit
    // =========================================================================

    @Nested
    @DisplayName("calculateDeficit")
    class CalculateDeficitTests {

        @Test
        @DisplayName("Returns empty map when player gems exactly cover the card cost")
        void exactGems_noDeficit() {
            Map<GemColor, Integer> deficit = CardEvaluator.calculateDeficit(richPlayer, cheapCard);
            assertTrue(deficit.isEmpty());
        }

        @Test
        @DisplayName("Returns full cost as deficit when player has zero gems")
        void brokePlayer_fullDeficit() {
            Map<GemColor, Integer> deficit = CardEvaluator.calculateDeficit(brokePlayer, cheapCard);
            assertEquals(2, deficit.get(GemColor.RED));
            assertEquals(1, deficit.get(GemColor.BLUE));
        }

        @Test
        @DisplayName("Returns empty map when player has more than enough gems")
        void surplusGems_noDeficit() {
            Player wealthy = new Player("Wealthy", 1);
            wealthy.addGems(new GemCollection()
                .add(GemColor.RED,  10)
                .add(GemColor.BLUE, 10));
            assertTrue(CardEvaluator.calculateDeficit(wealthy, cheapCard).isEmpty());
        }

        @Test
        @DisplayName("Returns partial deficit when player covers some colours but not all")
        void partialGems_partialDeficit() {
            Player p = new Player("Partial", 1);
            p.addGems(new GemCollection().add(GemColor.RED, 1));
            Map<GemColor, Integer> deficit = CardEvaluator.calculateDeficit(p, cheapCard);
            assertEquals(1, deficit.get(GemColor.RED));
            assertEquals(1, deficit.get(GemColor.BLUE));
        }

        @Test
        @DisplayName("Purchased card bonuses from addCard() reduce the deficit")
        void purchasedCardBonuses_reduceDeficit() {
            Player p = playerWithBonuses(GemColor.RED, 1);
            p.addGems(new GemCollection().add(GemColor.RED, 1));
            Map<GemColor, Integer> deficit = CardEvaluator.calculateDeficit(p, cheapCard);
            assertFalse(deficit.containsKey(GemColor.RED));
            assertEquals(1, deficit.get(GemColor.BLUE));
        }

        @Test
        @DisplayName("Bonus that exceeds the cost does not produce a negative deficit entry")
        void bonusExceedsCost_noNegativeDeficit() {
            Player p = playerWithBonuses(GemColor.RED, 5);
            Map<GemColor, Integer> deficit = CardEvaluator.calculateDeficit(p, cheapCard);
            deficit.values().forEach(v ->
                assertTrue(v > 0, "All deficit values must be positive"));
            assertFalse(deficit.containsKey(GemColor.RED));
        }

        @Test
        @DisplayName("GOLD gems held by player do not reduce per-colour deficit entries")
        void goldGems_notCountedInDeficit() {
            Player p = new Player("Gold", 1);
            p.addGems(new GemCollection().add(GemColor.GOLD, 5));
            Map<GemColor, Integer> deficit = CardEvaluator.calculateDeficit(p, cheapCard);
            assertEquals(2, deficit.get(GemColor.RED));
            assertEquals(1, deficit.get(GemColor.BLUE));
        }

        @Test
        @DisplayName("GOLD is never a key in the returned deficit map")
        void goldNeverAppearsAsDeficitKey() {
            Map<GemColor, Integer> deficit = CardEvaluator.calculateDeficit(
                brokePlayer, expensiveCard);
            assertFalse(deficit.containsKey(GemColor.GOLD));
        }

        @Test
        @DisplayName("Only colours with a positive deficit appear as keys")
        void onlyPositiveDeficitsAppearAsKeys() {
            Player p = new Player("Partial", 1);
            p.addGems(new GemCollection().add(GemColor.BLUE, 2));
            Map<GemColor, Integer> deficit = CardEvaluator.calculateDeficit(p, cheapCard);
            assertTrue(deficit.containsKey(GemColor.RED));
            assertFalse(deficit.containsKey(GemColor.BLUE));
        }

        @Test
        @DisplayName("Colours not in the card cost never appear as deficit keys")
        void colourNotInCost_neverInDeficit() {
            Map<GemColor, Integer> deficit = CardEvaluator.calculateDeficit(
                brokePlayer, cheapCard);
            assertFalse(deficit.containsKey(GemColor.GREEN));
            assertFalse(deficit.containsKey(GemColor.WHITE));
            assertFalse(deficit.containsKey(GemColor.BLACK));
        }

        @Test
        @DisplayName("Boundary: exact gem match produces empty deficit map")
        void exactMatchBoundary_emptyDeficit() {
            assertTrue(CardEvaluator.calculateDeficit(richPlayer, cheapCard).isEmpty());
        }
    }

    // =========================================================================
    // 3. totalDeficit
    // =========================================================================

    @Nested
    @DisplayName("totalDeficit")
    class TotalDeficitTests {

        @Test
        @DisplayName("Returns 0 when player gems exactly cover the card cost")
        void exactGems_zeroDeficit() {
            assertEquals(0, CardEvaluator.totalDeficit(richPlayer, cheapCard));
        }

        @Test
        @DisplayName("Returns 0 when player can fully afford the card")
        void fullyAffordable_zeroDeficit() {
            assertEquals(0, CardEvaluator.totalDeficit(richPlayer, cheapCard));
        }

        @Test
        @DisplayName("Returns exact sum of all colour deficits for a broke player")
        void sumsAllColourDeficits() {
            assertEquals(3, CardEvaluator.totalDeficit(brokePlayer, cheapCard));
        }

        @Test
        @DisplayName("Returns correct total for a multi-colour expensive card")
        void expensiveCard_correctTotal() {
            assertEquals(9, CardEvaluator.totalDeficit(brokePlayer, expensiveCard));
        }

        @Test
        @DisplayName("Partial gems reduce total deficit proportionally")
        void partialGems_reducedTotal() {
            Player p = new Player("Partial", 1);
            p.addGems(new GemCollection()
                .add(GemColor.RED,  1)
                .add(GemColor.BLUE, 1));
            assertEquals(1, CardEvaluator.totalDeficit(p, cheapCard));
        }

        @Test
        @DisplayName("GOLD gems in hand do not reduce total deficit")
        void goldGems_doNotReduceTotal() {
            Player p = new Player("Gold", 1);
            p.addGems(new GemCollection().add(GemColor.GOLD, 5));
            assertEquals(3, CardEvaluator.totalDeficit(p, cheapCard));
        }

        @Test
        @DisplayName("Never returns a negative value")
        void neverReturnsNegative() {
            Player p = new Player("OverGemmed", 1);
            p.addGems(new GemCollection()
                .add(GemColor.RED,  10)
                .add(GemColor.BLUE, 10));
            assertTrue(CardEvaluator.totalDeficit(p, cheapCard) >= 0);
        }

        @Test
        @DisplayName("Bonuses from addCard() reduce total deficit correctly")
        void bonuses_reduceTotal() {
            Player p = playerWithBonuses(GemColor.RED, 2);
            assertEquals(1, CardEvaluator.totalDeficit(p, cheapCard));
        }

        @Test
        @DisplayName("Returns 0 when bonuses fully cover the card cost")
        void fullBonusCoverage_zeroTotal() {
            Player p = playerWithBonuses(GemColor.RED, 2);
            p.addCard(minimalCard(GemColor.BLUE));
            assertEquals(0, CardEvaluator.totalDeficit(p, cheapCard));
        }
    }

    // =========================================================================
    // 4. estimateTurns
    // =========================================================================

    @Nested
    @DisplayName("estimateTurns")
    class EstimateTurnsTests {

        @Test
        @DisplayName("Returns 0 when player can immediately afford the card")
        void immediatelyAffordable_returnsZero() {
            assertEquals(0, CardEvaluator.estimateTurns(richPlayer, cheapCard, fullBank));
        }

        @Test
        @DisplayName("Returns 0 when player gems exactly cover the card cost regardless of bank")
        void exactGems_returnsZeroRegardlessOfBank() {
            assertEquals(0, CardEvaluator.estimateTurns(richPlayer, cheapCard, emptyBank));
        }

        @Test
        @DisplayName("Returns 1 for exactly 3 different colour deficit with a full bank")
        void threeColourDeficit_oneThreeDifferentTurn() {
            Map<GemColor, Integer> c = new EnumMap<>(GemColor.class);
            c.put(GemColor.RED,   1);
            c.put(GemColor.BLUE,  1);
            c.put(GemColor.GREEN, 1);
            Card card = new Card(1, 1, GemColor.WHITE, new Cost(c));
            assertEquals(1, CardEvaluator.estimateTurns(brokePlayer, card, fullBank));
        }

        @Test
        @DisplayName("Returns 1 when single colour deficit is 2 and bank has >= 4")
        void twoSamePath_oneTurn() {
            Card card = new Card(1, 1, GemColor.BLUE, cost(GemColor.RED, 2));
            assertEquals(1, CardEvaluator.estimateTurns(brokePlayer, card, fullBank));
        }

        @Test
        @DisplayName("Returns 2 when bank has fewer than 4 of the only needed colour")
        void twoSameBankTooSmall_twoTurns() {
            Card card = new Card(1, 1, GemColor.BLUE, cost(GemColor.RED, 2));
            GemCollection thinBank = new GemCollection()
                .add(GemColor.RED,   3)
                .add(GemColor.BLUE,  3)
                .add(GemColor.GREEN, 3)
                .add(GemColor.WHITE, 3)
                .add(GemColor.BLACK, 3);
            assertEquals(2, CardEvaluator.estimateTurns(brokePlayer, card, thinBank));
        }

        @Test
        @DisplayName("4-colour deficit of 2 each requires at least 3 turns")
        void fourColourDeficit_atLeastThreeTurns() {
            Map<GemColor, Integer> c = new EnumMap<>(GemColor.class);
            c.put(GemColor.RED,   2);
            c.put(GemColor.BLUE,  2);
            c.put(GemColor.GREEN, 2);
            c.put(GemColor.WHITE, 2);
            Card card = new Card(2, 4, GemColor.BLACK, new Cost(c));
            assertTrue(CardEvaluator.estimateTurns(brokePlayer, card, fullBank) >= 3);
        }

        @Test
        @DisplayName("Bonuses from addCard() reduce the number of turns needed")
        void bonuses_reduceTurns() {
            Player bonusPlayer = playerWithBonuses(GemColor.RED, 4);
            int turnsWithBonus    = CardEvaluator.estimateTurns(
                bonusPlayer, expensiveCard, fullBank);
            int turnsWithoutBonus = CardEvaluator.estimateTurns(
                brokePlayer, expensiveCard, fullBank);
            assertTrue(turnsWithBonus < turnsWithoutBonus,
                "Bonuses should strictly reduce estimated turns");
        }

        @Test
        @DisplayName("Never returns a negative number")
        void neverReturnsNegative() {
            assertTrue(CardEvaluator.estimateTurns(richPlayer, cheapCard, fullBank) >= 0);
        }

        @Test
        @DisplayName("Single colour deficit of 1 resolves in exactly 1 turn")
        void singleColourDeficitOfOne_oneTurn() {
            Card card = new Card(1, 0, GemColor.BLUE, cost(GemColor.RED, 1));
            assertEquals(1, CardEvaluator.estimateTurns(brokePlayer, card, fullBank));
        }

        @Test
        @DisplayName("Full bonus coverage gives 0 turns even with an empty bank")
        void fullBonusCoverage_zeroTurnsEmptyBank() {
            Player p = playerWithBonuses(GemColor.RED, 2);
            p.addCard(minimalCard(GemColor.BLUE));
            assertEquals(0, CardEvaluator.estimateTurns(p, cheapCard, emptyBank));
        }
    }

    // =========================================================================
    // 5. nobleProgress
    // =========================================================================

    @Nested
    @DisplayName("nobleProgress")
    class NobleProgressTests {

        @Test
        @DisplayName("Returns 0.0 for an empty noble list")
        void emptyNobleList_returnsZero() {
            assertEquals(0.0,
                CardEvaluator.nobleProgress(cheapCard, brokePlayer, Collections.emptyList()),
                0.001);
        }

        @Test
        @DisplayName("Returns 0.0 when no noble requires the card's bonus colour")
        void noNobleNeedsColour_returnsZero() {
            Noble n = noble(1, req(GemColor.BLUE, 3));
            assertEquals(0.0,
                CardEvaluator.nobleProgress(cheapCard, brokePlayer, List.of(n)),
                0.001);
        }

        @Test
        @DisplayName("Returns 1/remaining for a single noble with no existing bonuses")
        void singleNoble_noExistingBonuses() {
            Noble n = noble(1, req(GemColor.GREEN, 3));
            assertEquals(1.0 / 3,
                CardEvaluator.nobleProgress(cheapCard, brokePlayer, List.of(n)),
                0.001);
        }

        @Test
        @DisplayName("Returns 1.0 when exactly 1 more bonus of this colour is needed")
        void oneCardAway_returnsOne() {
            Noble n = noble(1, req(GemColor.GREEN, 3));
            Player p = playerWithBonuses(GemColor.GREEN, 2);
            assertEquals(1.0,
                CardEvaluator.nobleProgress(cheapCard, p, List.of(n)),
                0.001);
        }

        @Test
        @DisplayName("Sums progress across multiple nobles that need the same colour")
        void multipleNobles_sameColour_summed() {
            Noble n1 = noble(1, req(GemColor.GREEN, 3));
            Noble n2 = noble(2, req(GemColor.GREEN, 3));
            Noble n3 = noble(3, req(GemColor.GREEN, 3));
            assertEquals(1.0,
                CardEvaluator.nobleProgress(cheapCard, brokePlayer, List.of(n1, n2, n3)),
                0.001);
        }

        @Test
        @DisplayName("Can exceed 1.0 when many nobles are only one card away")
        void manyNoblesOneCardAway_exceedsOne() {
            Player p = playerWithBonuses(GemColor.GREEN, 2);
            List<Noble> nobles = List.of(
                noble(1, req(GemColor.GREEN, 3)),
                noble(2, req(GemColor.GREEN, 3)),
                noble(3, req(GemColor.GREEN, 3)),
                noble(4, req(GemColor.GREEN, 3)),
                noble(5, req(GemColor.GREEN, 3))
            );
            assertEquals(5.0,
                CardEvaluator.nobleProgress(cheapCard, p, nobles),
                0.001);
        }

        @Test
        @DisplayName("Returns 0.0 for a noble whose colour requirement is already fully satisfied")
        void alreadySatisfied_returnsZero() {
            Noble n = noble(1, req(GemColor.GREEN, 3));
            Player p = playerWithBonuses(GemColor.GREEN, 3);
            assertEquals(0.0,
                CardEvaluator.nobleProgress(cheapCard, p, List.of(n)),
                0.001);
        }

        @Test
        @DisplayName("Ignores nobles that do not require the card's bonus colour")
        void irrelevantNoble_ignored() {
            Noble relevant   = noble(1, req(GemColor.GREEN, 2));
            Noble irrelevant = noble(2, req(GemColor.RED,   4));
            assertEquals(0.5,
                CardEvaluator.nobleProgress(cheapCard, brokePlayer,
                    List.of(relevant, irrelevant)),
                0.001);
        }

        @Test
        @DisplayName("Noble with multiple colour requirements only scores the card's bonus colour")
        void multiColourNoble_onlyBonusColourScored() {
            Noble n = noble(1, req(GemColor.GREEN, 2, GemColor.RED, 3));
            assertEquals(0.5,
                CardEvaluator.nobleProgress(cheapCard, brokePlayer, List.of(n)),
                0.001);
        }

        @Test
        @DisplayName("Mixed list: only contributions from relevant nobles are summed")
        void mixedNobleList_onlyRelevantSummed() {
            Noble relevant1  = noble(1, req(GemColor.GREEN, 4));
            Noble relevant2  = noble(2, req(GemColor.GREEN, 2));
            Noble irrelevant = noble(3, req(GemColor.BLUE,  3));
            assertEquals(0.75,
                CardEvaluator.nobleProgress(cheapCard, brokePlayer,
                    List.of(relevant1, irrelevant, relevant2)),
                0.001);
        }
    }

    // =========================================================================
    // 6. discountUtility
    // =========================================================================

    @Nested
    @DisplayName("discountUtility")
    class DiscountUtilityTests {

        @Test
        @DisplayName("Returns 0.0 when no visible card requires the bonus colour")
        void emptyMarket_returnsZero() {
            // All filler cards cost only BLACK:1, so getRequired(GREEN) == 0
            assertEquals(0.0,
                CardEvaluator.discountUtility(cheapCard, emptyDiscountState()),
                0.001);
        }

        @Test
        @DisplayName("Returns 1.0 when all visible cards require the bonus colour")
        void allCardsNeedColour_returnsOne() {
            // cheapCard bonus is GREEN; fill ALL tiers with cards that cost GREEN
            Map<GemColor, Integer> needsGreen = new EnumMap<>(GemColor.class);
            needsGreen.put(GemColor.GREEN, 2);
            Card greenCard = new Card(1, 1, GemColor.RED, new Cost(needsGreen));
            // Every tier is padded with copies of greenCard → 100% match
            GameState state = buildStateForDiscount(
                List.of(greenCard),
                List.of(greenCard),
                List.of(greenCard)
            );
            assertEquals(1.0, CardEvaluator.discountUtility(cheapCard, state), 0.001);
        }

        @Test
        @DisplayName("Returns 0.0 when no visible card requires the bonus colour")
        void noCardNeedsColour_returnsZero() {
            // cheapCard bonus is GREEN; all cards cost only RED
            Card redOnly = new Card(1, 1, GemColor.BLUE, cost(GemColor.RED, 2));
            GameState state = buildStateForDiscount(
                List.of(redOnly),
                List.of(redOnly),
                List.of(redOnly)
            );
            assertEquals(0.0, CardEvaluator.discountUtility(cheapCard, state), 0.001);
        }

        @Test
        @DisplayName("Returns correct ratio when only some tiers need the colour")
        void partialMatch_correctRatio() {
            // cheapCard bonus is GREEN.
            //   tier 1 (all 20 copies): costs GREEN → 4 visible match
            //   tier 2 (all 20 copies): costs RED   → 0 visible match
            //   tier 3 (all 20 copies): costs GREEN → 4 visible match
            // 8 of 12 visible → 2/3
            Map<GemColor, Integer> needsGreen = new EnumMap<>(GemColor.class);
            needsGreen.put(GemColor.GREEN, 1);
            Card greenCard = new Card(1, 1, GemColor.RED,   new Cost(needsGreen));
            Card redCard   = new Card(1, 1, GemColor.WHITE, cost(GemColor.RED, 1));
            GameState state = buildStateForDiscount(
                List.of(greenCard),
                List.of(redCard),
                List.of(greenCard)
            );
            assertEquals(2.0 / 3, CardEvaluator.discountUtility(cheapCard, state), 0.001);
        }

        @Test
        @DisplayName("Scans all three tiers when computing the ratio")
        void scansAllThreeTiers() {
            Map<GemColor, Integer> needsGreen = new EnumMap<>(GemColor.class);
            needsGreen.put(GemColor.GREEN, 1);
            Card greenCard = new Card(1, 1, GemColor.RED,   new Cost(needsGreen));
            Card noMatch   = new Card(2, 2, GemColor.WHITE, cost(GemColor.RED, 1));
            GameState state = buildStateForDiscount(
                List.of(greenCard),
                List.of(noMatch),
                List.of(greenCard)
            );
            assertEquals(2.0 / 3, CardEvaluator.discountUtility(cheapCard, state), 0.001);
        }

        @Test
        @DisplayName("Result is always within [0.0, 1.0]")
        void resultAlwaysInBounds() {
            Map<GemColor, Integer> needsGreen = new EnumMap<>(GemColor.class);
            needsGreen.put(GemColor.GREEN, 2);
            Card m1 = new Card(1, 1, GemColor.RED, new Cost(needsGreen));
            GameState state = buildStateForDiscount(
                List.of(m1), List.of(m1), List.of(m1)
            );
            double result = CardEvaluator.discountUtility(cheapCard, state);
            assertTrue(result >= 0.0 && result <= 1.0,
                "discountUtility must return a value in [0.0, 1.0]");
        }

        @Test
        @DisplayName("A market card with 0 requirement for the bonus colour does not count")
        void zeroRequirement_notAMatch() {
            Card m1 = new Card(1, 1, GemColor.RED, cost(GemColor.BLUE, 2));
            GameState state = buildStateForDiscount(
                List.of(m1), List.of(m1), List.of(m1)
            );
            assertEquals(0.0, CardEvaluator.discountUtility(cheapCard, state), 0.001);
        }

        @Test
        @DisplayName("One tier matches, two tiers do not — gives ratio of 1/3")
        void oneTierMatchesTwoDoNot_oneThirdRatio() {
            Map<GemColor, Integer> needsGreen = new EnumMap<>(GemColor.class);
            needsGreen.put(GemColor.GREEN, 1);
            Card greenCard = new Card(1, 1, GemColor.RED,   new Cost(needsGreen));
            Card redCard   = new Card(1, 1, GemColor.WHITE, cost(GemColor.RED, 1));
            GameState state = buildStateForDiscount(
                List.of(greenCard),
                List.of(redCard),
                List.of(redCard)
            );
            assertEquals(1.0 / 3, CardEvaluator.discountUtility(cheapCard, state), 0.001);
        }
    }
}