package edu.cs102.g04t06.game.execution.ai;

// Generated by Claude Sonnet 4.6

import edu.cs102.g04t06.game.rules.GameState;
import edu.cs102.g04t06.game.rules.entities.ActionType;
import edu.cs102.g04t06.game.rules.entities.Card;
import edu.cs102.g04t06.game.rules.entities.GemColor;
import edu.cs102.g04t06.game.rules.entities.Noble;
import edu.cs102.g04t06.game.rules.entities.Player;
import edu.cs102.g04t06.game.rules.valueobjects.CardMarket;
import edu.cs102.g04t06.game.rules.valueobjects.Cost;
import edu.cs102.g04t06.game.rules.valueobjects.GemCollection;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("HardAIStrategy Tests")
class HardAIStrategyTest {

    private HardAIStrategy strategy;
    private Player player;

    @BeforeEach
    void setUp() {
        strategy = new HardAIStrategy();
        player = new Player("TestAI", 0);
    }

    // =========================================================
    // decideAction
    // =========================================================

    @Test
    @DisplayName("decideAction: returns non-null in a normal game state")
    void decideAction_returnsNonNull() {
        GameState state = buildDefaultState(player);
        assertNotNull(strategy.decideAction(state, player));
    }

    @Test
    @DisplayName("decideAction: returns PURCHASE_CARD when player can afford a visible card")
    void decideAction_prefersPurchaseWhenAffordable() {
        GameState state = buildStateWithFreeCards(player);
        AIAction action = strategy.decideAction(state, player);
        assertEquals(ActionType.PURCHASE_CARD, action.getActionType());
    }

    @Test
    @DisplayName("decideAction: PURCHASE_CARD action carries a non-null targetCard")
    void decideAction_purchaseActionHasTargetCard() {
        GameState state = buildStateWithFreeCards(player);
        AIAction action = strategy.decideAction(state, player);
        assertNotNull(action.getTargetCard());
    }

    @Test
    @DisplayName("decideAction: PURCHASE_CARD from market has fromReserved=false")
    void decideAction_purchaseFromMarketIsNotFromReserved() {
        GameState state = buildStateWithFreeCards(player);
        AIAction action = strategy.decideAction(state, player);
        assertFalse(action.isFromReserved());
    }

    @Test
    @DisplayName("decideAction: returns PURCHASE_CARD fromReserved=true when only reserved card is affordable")
    void decideAction_purchaseFromReservedWhenOnlyReservedIsAffordable() {
        // Visible cards are all very expensive; reserved card has zero cost.
        // Use WHITE bonus so discount utility is non-zero (expensive cards cost WHITE).
        Card freeReserved = buildFreeCard(2, 3, GemColor.WHITE);
        player.addReservedCard(freeReserved);
        GameState state = buildStateWithExpensiveCards(player);

        AIAction action = strategy.decideAction(state, player);

        assertEquals(ActionType.PURCHASE_CARD, action.getActionType());
        assertTrue(action.isFromReserved());
        assertSame(freeReserved, action.getTargetCard());
    }

    @Test
    @DisplayName("decideAction: returns a TAKE action when no card is affordable")
    void decideAction_returnsTakeActionWhenNothingAffordable() {
        GameState state = buildStateWithExpensiveCards(player);
        AIAction action = strategy.decideAction(state, player);
        assertNotNull(action);
        assertTrue(
            action.getActionType() == ActionType.TAKE_THREE_DIFFERENT ||
            action.getActionType() == ActionType.TAKE_TWO_SAME,
            "Expected a gem-take action but got: " + action.getActionType()
        );
    }

    @Test
    @DisplayName("decideAction: TAKE action carries a non-null gemSelection with at least 1 gem")
    void decideAction_takeActionHasGemSelection() {
        GameState state = buildStateWithExpensiveCards(player);
        AIAction action = strategy.decideAction(state, player);
        assertNotNull(action.getGemSelection());
        assertTrue(action.getGemSelection().getTotalCount() > 0);
    }

    @Test
    @DisplayName("decideAction: TAKE_THREE_DIFFERENT gemSelection has exactly 3 gems")
    void decideAction_takeThreeDifferentHasExactlyThreeGems() {
        GameState state = buildStateWithExpensiveCards(player);
        AIAction action = strategy.decideAction(state, player);
        if (action.getActionType() == ActionType.TAKE_THREE_DIFFERENT) {
            assertEquals(3, action.getGemSelection().getTotalCount());
        }
    }

    @Test
    @DisplayName("decideAction: does not return RESERVE_CARD when player already has 3 reserved cards")
    void decideAction_doesNotReserveAtMaxCapacity() {
        player.addReservedCard(buildExpensiveCard(1));
        player.addReservedCard(buildExpensiveCard(1));
        player.addReservedCard(buildExpensiveCard(1));
        GameState state = buildStateWithExpensiveCards(player);

        AIAction action = strategy.decideAction(state, player);

        assertNotNull(action);
        assertNotEquals(ActionType.RESERVE_CARD, action.getActionType());
    }

    @Test
    @DisplayName("decideAction: prefers PURCHASE over RESERVE for same visible card (full score vs 0.7x)")
    void decideAction_prefersPurchaseOverReserveForSameCard() {
        // Free cards are affordable → purchase at full score beats reserve at 0.7x
        GameState state = buildStateWithFreeCards(player);
        AIAction action = strategy.decideAction(state, player);
        assertEquals(ActionType.PURCHASE_CARD, action.getActionType());
    }

    // =========================================================
    // chooseNoble
    // =========================================================

    @Test
    @DisplayName("chooseNoble: returns the single noble when list has exactly one element")
    void chooseNoble_returnsSingleNoble() {
        Noble noble = buildSingleColorNoble(1, GemColor.WHITE, 3);
        List<Noble> claimable = List.of(noble);
        GameState state = buildStateWithNobles(player, new ArrayList<>(claimable));

        assertSame(noble, strategy.chooseNoble(claimable, state, player));
    }

    @Test
    @DisplayName("chooseNoble: returned noble is always a member of the claimable list")
    void chooseNoble_returnedNobleIsInClaimableList() {
        Noble noble1 = buildSingleColorNoble(1, GemColor.WHITE, 3);
        Noble noble2 = buildSingleColorNoble(2, GemColor.RED, 3);
        List<Noble> claimable = new ArrayList<>(List.of(noble1, noble2));
        GameState state = buildStateWithNobles(player, new ArrayList<>(claimable));

        Noble chosen = strategy.chooseNoble(claimable, state, player);

        assertTrue(claimable.contains(chosen));
    }

    @Test
    @DisplayName("chooseNoble: returns non-null for any non-empty claimable list")
    void chooseNoble_returnsNonNullForNonEmptyList() {
        Noble noble = buildSingleColorNoble(1, GemColor.BLUE, 3);
        List<Noble> claimable = List.of(noble);
        GameState state = buildStateWithNobles(player, new ArrayList<>(claimable));

        assertNotNull(strategy.chooseNoble(claimable, state, player));
    }

    @Test
    @DisplayName("chooseNoble: blocking strategy — picks noble opponent is closest to claiming")
    void chooseNoble_picksNobleOpponentIsClosestTo() {
        // Opponent has 2 WHITE bonus cards (needs 3 for noble1) → deficit=1 → score=1/(1+1)=0.5
        // Opponent has 0 RED bonus cards (needs 3 for noble2)  → deficit=3 → score=1/(3+1)=0.25
        // AI should pick noble1 to block the opponent
        Player opponent = new Player("Opponent", 1);
        Map<GemColor, Integer> whiteCost = new EnumMap<>(GemColor.class);
        whiteCost.put(GemColor.WHITE, 1);
        opponent.addCard(new Card(1, 0, GemColor.WHITE, new Cost(whiteCost)));
        opponent.addCard(new Card(1, 0, GemColor.WHITE, new Cost(whiteCost)));

        Noble noble1 = buildSingleColorNoble(1, GemColor.WHITE, 3);
        Noble noble2 = buildSingleColorNoble(2, GemColor.RED,   3);
        List<Noble> claimable = new ArrayList<>(List.of(noble1, noble2));

        CardMarket market = new CardMarket(buildCardList(1, 20), buildCardList(2, 20), buildCardList(3, 20));
        GameState state = new GameState(
                List.of(player, opponent), market, fullBank(), new ArrayList<>(claimable), 15);

        Noble chosen = strategy.chooseNoble(claimable, state, player);
        assertSame(noble1, chosen);
    }

    @Test
    @DisplayName("chooseNoble: returns first-encountered noble when blocking scores tie (no opponents)")
    void chooseNoble_returnsFirstOnTie() {
        // Single-player game → no opponents → all blocking scores are 0.0
        // Strict '>' means first-encountered (noble1) wins the tie
        Noble noble1 = buildSingleColorNoble(1, GemColor.WHITE, 3);
        Noble noble2 = buildSingleColorNoble(2, GemColor.RED, 3);
        List<Noble> claimable = new ArrayList<>(List.of(noble1, noble2));
        GameState state = buildStateWithNobles(player, new ArrayList<>(claimable));

        Noble chosen = strategy.chooseNoble(claimable, state, player);
        assertSame(noble1, chosen);
    }

    // =========================================================
    // chooseGemsToReturn
    // =========================================================

    @Test
    @DisplayName("chooseGemsToReturn: returns exactly 1 gem for excessCount=1")
    void chooseGemsToReturn_returnsExactlyOneGem() {
        player.addGems(new GemCollection().add(GemColor.WHITE, 4).add(GemColor.BLACK, 3));
        GameState state = buildStateWithMarketCostingColor(GemColor.WHITE, player);

        GemCollection result = strategy.chooseGemsToReturn(player, 1, state);

        assertEquals(1, result.getTotalCount());
    }

    @Test
    @DisplayName("chooseGemsToReturn: returns exactly 2 gems for excessCount=2")
    void chooseGemsToReturn_returnsExactlyTwoGems() {
        player.addGems(new GemCollection().add(GemColor.WHITE, 4).add(GemColor.BLACK, 4));
        GameState state = buildStateWithMarketCostingColor(GemColor.WHITE, player);

        GemCollection result = strategy.chooseGemsToReturn(player, 2, state);

        assertEquals(2, result.getTotalCount());
    }

    @Test
    @DisplayName("chooseGemsToReturn: all color counts in result are non-negative")
    void chooseGemsToReturn_noNegativeCounts() {
        player.addGems(new GemCollection().add(GemColor.WHITE, 4).add(GemColor.BLACK, 3));
        GameState state = buildStateWithMarketCostingColor(GemColor.WHITE, player);

        GemCollection result = strategy.chooseGemsToReturn(player, 2, state);

        for (GemColor c : GemColor.values()) {
            assertTrue(result.getCount(c) >= 0, "Negative gem count for " + c);
        }
    }

    @Test
    @DisplayName("chooseGemsToReturn: returns LOW priority gem (not needed for target) before HIGH")
    void chooseGemsToReturn_returnsLowPriorityBeforeHigh() {
        // Market costs WHITE:5 → WHITE deficit=1 (HIGH priority)
        // Player has WHITE:4 (HIGH) and BLACK:3 (LOW — target doesn't need BLACK)
        // excessCount=1 → return BLACK (LOW), not WHITE (HIGH)
        GameState state = buildStateWithMarketCostingColor(GemColor.WHITE, player);
        player.addGems(new GemCollection().add(GemColor.WHITE, 4).add(GemColor.BLACK, 3));

        GemCollection result = strategy.chooseGemsToReturn(player, 1, state);

        assertEquals(0, result.getCount(GemColor.WHITE), "HIGH priority gem WHITE should not be returned");
        assertEquals(1, result.getCount(GemColor.BLACK), "LOW priority gem BLACK should be returned");
    }

    @Test
    @DisplayName("chooseGemsToReturn: among LOW priority gems, returns the most-held color first")
    void chooseGemsToReturn_mostHeldLowPriorityFirst() {
        // Market costs WHITE → WHITE is HIGH; BLACK(4) and BLUE(2) are LOW
        // excessCount=1 → return 1 BLACK (most-held LOW, 4 > 2)
        GameState state = buildStateWithMarketCostingColor(GemColor.WHITE, player);
        player.addGems(new GemCollection()
                .add(GemColor.WHITE, 4)   // HIGH priority
                .add(GemColor.BLACK, 4)   // LOW priority, most held
                .add(GemColor.BLUE, 2));  // LOW priority, less held

        GemCollection result = strategy.chooseGemsToReturn(player, 1, state);

        assertEquals(1, result.getCount(GemColor.BLACK));
        assertEquals(0, result.getCount(GemColor.BLUE));
    }

    @Test
    @DisplayName("chooseGemsToReturn: falls through to HIGH priority when no LOW priority gems held")
    void chooseGemsToReturn_fallsToHighPriorityWhenNoLow() {
        // Market costs WHITE → WHITE deficit=1 (HIGH).  Player holds only WHITE (no LOW).
        // excessCount=1 → must fall through and return WHITE (the only available gem)
        GameState state = buildStateWithMarketCostingColor(GemColor.WHITE, player);
        player.addGems(new GemCollection().add(GemColor.WHITE, 4));

        GemCollection result = strategy.chooseGemsToReturn(player, 1, state);

        assertEquals(1, result.getTotalCount());
        assertEquals(1, result.getCount(GemColor.WHITE));
    }

    @Test
    @DisplayName("chooseGemsToReturn: returns gold as absolute last resort")
    void chooseGemsToReturn_returnsGoldAsLastResort() {
        // Player holds only gold — all non-gold counts are 0, so the LOW/HIGH loops
        // skip everything, and the gold fallback kicks in
        player.addGems(new GemCollection().add(GemColor.GOLD, 3));
        GameState state = buildDefaultState(player);

        GemCollection result = strategy.chooseGemsToReturn(player, 1, state);

        assertEquals(1, result.getTotalCount());
        assertEquals(1, result.getCount(GemColor.GOLD));
    }

    // =========================================================
    // Helpers
    // =========================================================

    /** Standard game state: moderate-cost cards, full bank, no nobles. */
    private GameState buildDefaultState(Player p) {
        CardMarket market = new CardMarket(
                buildCardList(1, 20), buildCardList(2, 20), buildCardList(3, 20));
        return new GameState(List.of(p), market, fullBank(), new ArrayList<>(), 15);
    }

    /** All market cards have zero cost — player can always afford them. */
    private GameState buildStateWithFreeCards(Player p) {
        CardMarket market = new CardMarket(
                buildFreeCardList(1, 20), buildFreeCardList(2, 20), buildFreeCardList(3, 20));
        return new GameState(List.of(p), market, fullBank(), new ArrayList<>(), 15);
    }

    /** All market cards cost 7 of three colors — impossible to afford with no gems. */
    private GameState buildStateWithExpensiveCards(Player p) {
        CardMarket market = new CardMarket(
                buildExpensiveCardList(1, 20),
                buildExpensiveCardList(2, 20),
                buildExpensiveCardList(3, 20));
        return new GameState(List.of(p), market, fullBank(), new ArrayList<>(), 15);
    }

    /**
     * All market cards cost {@code costColor}:5.
     * Useful for making a specific color the HIGH-priority gem in chooseGemsToReturn tests.
     */
    private GameState buildStateWithMarketCostingColor(GemColor costColor, Player p) {
        CardMarket market = new CardMarket(
                buildCardsWithCost(1, 20, costColor, 5),
                buildCardsWithCost(2, 20, costColor, 5),
                buildCardsWithCost(3, 20, costColor, 5));
        return new GameState(List.of(p), market, fullBank(), new ArrayList<>(), 15);
    }

    /** Game state with a specific set of available nobles. */
    private GameState buildStateWithNobles(Player p, List<Noble> nobles) {
        CardMarket market = new CardMarket(
                buildCardList(1, 20), buildCardList(2, 20), buildCardList(3, 20));
        return new GameState(List.of(p), market, fullBank(), nobles, 15);
    }

    // ---- Card list builders ----

    private List<Card> buildCardList(int level, int count) {
        GemColor[] bonuses = {GemColor.WHITE, GemColor.BLUE, GemColor.GREEN, GemColor.RED, GemColor.BLACK};
        List<Card> cards = new ArrayList<>();
        for (int i = 0; i < count; i++) {
            Map<GemColor, Integer> cm = new EnumMap<>(GemColor.class);
            cm.put(GemColor.WHITE, 2 + (i % 3));
            cm.put(GemColor.BLUE, 1 + (i % 2));
            cards.add(new Card(level, i % 3, bonuses[i % 5], new Cost(cm)));
        }
        return cards;
    }

    private List<Card> buildFreeCardList(int level, int count) {
        GemColor[] bonuses = {GemColor.WHITE, GemColor.BLUE, GemColor.GREEN, GemColor.RED, GemColor.BLACK};
        List<Card> cards = new ArrayList<>();
        for (int i = 0; i < count; i++) {
            cards.add(new Card(level, i % 4, bonuses[i % 5], new Cost(new EnumMap<>(GemColor.class))));
        }
        return cards;
    }

    private List<Card> buildExpensiveCardList(int level, int count) {
        List<Card> cards = new ArrayList<>();
        for (int i = 0; i < count; i++) cards.add(buildExpensiveCard(level));
        return cards;
    }

    private List<Card> buildCardsWithCost(int level, int count, GemColor costColor, int costAmount) {
        GemColor[] bonuses = {GemColor.WHITE, GemColor.BLUE, GemColor.GREEN, GemColor.RED, GemColor.BLACK};
        Map<GemColor, Integer> cm = new EnumMap<>(GemColor.class);
        cm.put(costColor, costAmount);
        Cost cost = new Cost(cm);
        List<Card> cards = new ArrayList<>();
        for (int i = 0; i < count; i++) {
            cards.add(new Card(level, 1 + (i % 3), bonuses[i % 5], cost));
        }
        return cards;
    }

    // ---- Individual card builders ----

    private Card buildFreeCard(int level, int points, GemColor bonus) {
        return new Card(level, points, bonus, new Cost(new EnumMap<>(GemColor.class)));
    }

    private Card buildExpensiveCard(int level) {
        Map<GemColor, Integer> cm = new EnumMap<>(GemColor.class);
        cm.put(GemColor.WHITE, 7);
        cm.put(GemColor.BLUE, 7);
        cm.put(GemColor.GREEN, 7);
        return new Card(level, level, GemColor.WHITE, new Cost(cm));
    }

    // ---- Noble builders ----

    private Noble buildSingleColorNoble(int id, GemColor color, int amount) {
        Map<GemColor, Integer> requirements = new EnumMap<>(GemColor.class);
        requirements.put(color, amount);
        return new Noble(id, "Noble" + id, requirements);
    }

    // ---- Bank ----

    private GemCollection fullBank() {
        return new GemCollection()
                .add(GemColor.WHITE, 7).add(GemColor.BLUE, 7).add(GemColor.GREEN, 7)
                .add(GemColor.RED, 7).add(GemColor.BLACK, 7).add(GemColor.GOLD, 5);
    }
}
