package edu.cs102.g04t06.game.rules.entities;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

// Generated by GPT-5 (Codex)
/**
 * Unit tests for ActionType enum.
 *
 * @author CS102 Team G6
 * @version 1.0
 */

class ActionTypeTest {

    @Test
    void hasExpectedEnumValues() {
        ActionType[] expected = {
            ActionType.TAKE_THREE_DIFFERENT,
            ActionType.TAKE_TWO_SAME,
            ActionType.PURCHASE_CARD,
            ActionType.RESERVE_CARD
        };

        assertArrayEquals(expected, ActionType.values());
    }

    @Test
    void valueOfResolvesActionName() {
        assertEquals(ActionType.PURCHASE_CARD, ActionType.valueOf("PURCHASE_CARD"));
        assertEquals(ActionType.RESERVE_CARD, ActionType.valueOf("RESERVE_CARD"));
    }
}
