package edu.cs102.g04t06.game.rules.entities;

import edu.cs102.g04t06.game.rules.valueobjects.Cost;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;

import java.util.EnumMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

// Generated by Claude Sonnet 4.5
/**
 * Unit tests for Card entity.
 * 
 */
@DisplayName("Card Tests")
class CardTest {
    
    private Cost standardCost;
    private Card level1Card;
    private Card level2Card;
    private Card level3Card;
    
    @BeforeEach
    void setUp() {
        // Create a standard cost (3 white, 2 blue)
        Map<GemColor, Integer> costMap = new EnumMap<>(GemColor.class);
        costMap.put(GemColor.WHITE, 3);
        costMap.put(GemColor.BLUE, 2);
        standardCost = new Cost(costMap);
        
        // Create cards for each level
        level1Card = new Card(1, 0, GemColor.WHITE, standardCost);
        level2Card = new Card(2, 2, GemColor.BLUE, standardCost);
        level3Card = new Card(3, 5, GemColor.GREEN, standardCost);
    }
    
    // ==================== Constructor Tests ====================
    
    @Test
    @DisplayName("Constructor should create card with correct level")
    void constructorShouldSetCorrectLevel() {
        assertEquals(1, level1Card.getLevel());
        assertEquals(2, level2Card.getLevel());
        assertEquals(3, level3Card.getLevel());
    }
    
    @Test
    @DisplayName("Constructor should create card with correct points")
    void constructorShouldSetCorrectPoints() {
        assertEquals(0, level1Card.getPoints());
        assertEquals(2, level2Card.getPoints());
        assertEquals(5, level3Card.getPoints());
    }
    
    @Test
    @DisplayName("Constructor should create card with correct bonus")
    void constructorShouldSetCorrectBonus() {
        assertEquals(GemColor.WHITE, level1Card.getBonus());
        assertEquals(GemColor.BLUE, level2Card.getBonus());
        assertEquals(GemColor.GREEN, level3Card.getBonus());
    }
    
    @Test
    @DisplayName("Constructor should create card with correct cost")
    void constructorShouldSetCorrectCost() {
        assertNotNull(level1Card.getCost());
        assertEquals(3, level1Card.getCost().getRequired(GemColor.WHITE));
        assertEquals(2, level1Card.getCost().getRequired(GemColor.BLUE));
    }
    
    // ==================== getLevel() Tests ====================
    
    @Test
    @DisplayName("getLevel should return level 1")
    void getLevelShouldReturnLevel1() {
        Card card = new Card(1, 0, GemColor.WHITE, standardCost);
        assertEquals(1, card.getLevel());
    }
    
    @Test
    @DisplayName("getLevel should return level 2")
    void getLevelShouldReturnLevel2() {
        Card card = new Card(2, 1, GemColor.BLUE, standardCost);
        assertEquals(2, card.getLevel());
    }
    
    @Test
    @DisplayName("getLevel should return level 3")
    void getLevelShouldReturnLevel3() {
        Card card = new Card(3, 3, GemColor.GREEN, standardCost);
        assertEquals(3, card.getLevel());
    }
    
    // ==================== getPoints() Tests ====================
    
    @Test
    @DisplayName("getPoints should return zero points")
    void getPointsShouldReturnZeroPoints() {
        Card card = new Card(1, 0, GemColor.WHITE, standardCost);
        assertEquals(0, card.getPoints());
    }
    
    @Test
    @DisplayName("getPoints should return positive points")
    void getPointsShouldReturnPositivePoints() {
        Card card1 = new Card(2, 1, GemColor.BLUE, standardCost);
        Card card2 = new Card(2, 2, GemColor.GREEN, standardCost);
        Card card3 = new Card(3, 5, GemColor.RED, standardCost);
        
        assertEquals(1, card1.getPoints());
        assertEquals(2, card2.getPoints());
        assertEquals(5, card3.getPoints());
    }
    
    @Test
    @DisplayName("getPoints should handle high point values")
    void getPointsShouldHandleHighPoints() {
        Card card = new Card(3, 10, GemColor.BLACK, standardCost);
        assertEquals(10, card.getPoints());
    }
    
    // ==================== getBonus() Tests ====================
    
    @Test
    @DisplayName("getBonus should return WHITE bonus")
    void getBonusShouldReturnWhiteBonus() {
        Card card = new Card(1, 0, GemColor.WHITE, standardCost);
        assertEquals(GemColor.WHITE, card.getBonus());
    }
    
    @Test
    @DisplayName("getBonus should return BLUE bonus")
    void getBonusShouldReturnBlueBonus() {
        Card card = new Card(1, 0, GemColor.BLUE, standardCost);
        assertEquals(GemColor.BLUE, card.getBonus());
    }
    
    @Test
    @DisplayName("getBonus should return GREEN bonus")
    void getBonusShouldReturnGreenBonus() {
        Card card = new Card(1, 0, GemColor.GREEN, standardCost);
        assertEquals(GemColor.GREEN, card.getBonus());
    }
    
    @Test
    @DisplayName("getBonus should return RED bonus")
    void getBonusShouldReturnRedBonus() {
        Card card = new Card(1, 0, GemColor.RED, standardCost);
        assertEquals(GemColor.RED, card.getBonus());
    }
    
    @Test
    @DisplayName("getBonus should return BLACK bonus")
    void getBonusShouldReturnBlackBonus() {
        Card card = new Card(1, 0, GemColor.BLACK, standardCost);
        assertEquals(GemColor.BLACK, card.getBonus());
    }
    
    @Test
    @DisplayName("getBonus should not return GOLD (gold not valid for card bonuses)")
    void getBonusShouldNotReturnGold() {
        // This test documents that GOLD should not be used for card bonuses
        // Gold gems are wild cards, not bonuses from cards
        Card card = new Card(1, 0, GemColor.WHITE, standardCost);
        assertNotEquals(GemColor.GOLD, card.getBonus());
    }
    
    // ==================== getCost() Tests ====================
    
    @Test
    @DisplayName("getCost should return non-null cost")
    void getCostShouldReturnNonNull() {
        assertNotNull(level1Card.getCost());
        assertNotNull(level2Card.getCost());
        assertNotNull(level3Card.getCost());
    }
    
    @Test
    @DisplayName("getCost should return correct cost object")
    void getCostShouldReturnCorrectCost() {
        Cost cost = level1Card.getCost();
        
        assertEquals(3, cost.getRequired(GemColor.WHITE));
        assertEquals(2, cost.getRequired(GemColor.BLUE));
        assertEquals(5, cost.getTotalGems());
    }
    
    @Test
    @DisplayName("getCost should return same cost instance (immutable)")
    void getCostShouldReturnSameCostInstance() {
        Cost cost1 = level1Card.getCost();
        Cost cost2 = level1Card.getCost();
        
        assertSame(cost1, cost2);
    }
    
    // ==================== Immutability Tests ====================
    
    @Test
    @DisplayName("Card should be immutable - level cannot change")
    void cardShouldBeImmutableLevel() {
        Card card = new Card(1, 0, GemColor.WHITE, standardCost);
        int originalLevel = card.getLevel();
        
        // Level should remain the same
        assertEquals(originalLevel, card.getLevel());
        assertEquals(1, card.getLevel());
    }
    
    @Test
    @DisplayName("Card should be immutable - points cannot change")
    void cardShouldBeImmutablePoints() {
        Card card = new Card(2, 2, GemColor.BLUE, standardCost);
        int originalPoints = card.getPoints();
        
        // Points should remain the same
        assertEquals(originalPoints, card.getPoints());
        assertEquals(2, card.getPoints());
    }
    
    @Test
    @DisplayName("Card should be immutable - bonus cannot change")
    void cardShouldBeImmutableBonus() {
        Card card = new Card(1, 0, GemColor.GREEN, standardCost);
        GemColor originalBonus = card.getBonus();
        
        // Bonus should remain the same
        assertEquals(originalBonus, card.getBonus());
        assertEquals(GemColor.GREEN, card.getBonus());
    }
    
    @Test
    @DisplayName("Card should be immutable - cost cannot change")
    void cardShouldBeImmutableCost() {
        Card card = new Card(1, 0, GemColor.WHITE, standardCost);
        Cost originalCost = card.getCost();
        
        // Cost should remain the same
        assertSame(originalCost, card.getCost());
        assertEquals(5, card.getCost().getTotalGems());
    }
    
    // ==================== Edge Case Tests ====================
    
    @Test
    @DisplayName("Should handle card with zero cost")
    void shouldHandleCardWithZeroCost() {
        Map<GemColor, Integer> zeroCostMap = new EnumMap<>(GemColor.class);
        Cost zeroCost = new Cost(zeroCostMap);
        
        Card card = new Card(1, 0, GemColor.WHITE, zeroCost);
        
        assertEquals(0, card.getCost().getTotalGems());
        assertNotNull(card.getCost());
    }
    
    @Test
    @DisplayName("Should handle card with single gem cost")
    void shouldHandleCardWithSingleGemCost() {
        Map<GemColor, Integer> singleGemCost = new EnumMap<>(GemColor.class);
        singleGemCost.put(GemColor.RED, 1);
        Cost cost = new Cost(singleGemCost);
        
        Card card = new Card(1, 0, GemColor.WHITE, cost);
        
        assertEquals(1, card.getCost().getTotalGems());
        assertEquals(1, card.getCost().getRequired(GemColor.RED));
    }
    
    @Test
    @DisplayName("Should handle card with high cost")
    void shouldHandleCardWithHighCost() {
        Map<GemColor, Integer> highCostMap = new EnumMap<>(GemColor.class);
        highCostMap.put(GemColor.WHITE, 7);
        highCostMap.put(GemColor.BLUE, 3);
        Cost highCost = new Cost(highCostMap);
        
        Card card = new Card(3, 5, GemColor.GREEN, highCost);
        
        assertEquals(10, card.getCost().getTotalGems());
    }
    
    @Test
    @DisplayName("Should handle card with cost in all standard colors")
    void shouldHandleCardWithAllStandardColors() {
        Map<GemColor, Integer> allColorsCost = new EnumMap<>(GemColor.class);
        allColorsCost.put(GemColor.WHITE, 1);
        allColorsCost.put(GemColor.BLUE, 1);
        allColorsCost.put(GemColor.GREEN, 1);
        allColorsCost.put(GemColor.RED, 1);
        allColorsCost.put(GemColor.BLACK, 1);
        Cost cost = new Cost(allColorsCost);
        
        Card card = new Card(2, 2, GemColor.WHITE, cost);
        
        assertEquals(5, card.getCost().getTotalGems());
        assertEquals(1, card.getCost().getRequired(GemColor.WHITE));
        assertEquals(1, card.getCost().getRequired(GemColor.BLACK));
    }
    
    // ==================== Realistic Card Tests ====================
    
    @Test
    @DisplayName("Should create typical Level 1 card (0 points, low cost)")
    void shouldCreateTypicalLevel1Card() {
        Map<GemColor, Integer> level1Cost = new EnumMap<>(GemColor.class);
        level1Cost.put(GemColor.BLUE, 1);
        level1Cost.put(GemColor.GREEN, 1);
        level1Cost.put(GemColor.RED, 1);
        level1Cost.put(GemColor.BLACK, 1);
        Cost cost = new Cost(level1Cost);
        
        Card card = new Card(1, 0, GemColor.WHITE, cost);
        
        assertEquals(1, card.getLevel());
        assertEquals(0, card.getPoints());
        assertEquals(GemColor.WHITE, card.getBonus());
        assertEquals(4, card.getCost().getTotalGems());
    }
    
    @Test
    @DisplayName("Should create typical Level 2 card (1-3 points, medium cost)")
    void shouldCreateTypicalLevel2Card() {
        Map<GemColor, Integer> level2Cost = new EnumMap<>(GemColor.class);
        level2Cost.put(GemColor.WHITE, 2);
        level2Cost.put(GemColor.BLACK, 3);
        level2Cost.put(GemColor.RED, 2);
        Cost cost = new Cost(level2Cost);
        
        Card card = new Card(2, 2, GemColor.BLUE, cost);
        
        assertEquals(2, card.getLevel());
        assertEquals(2, card.getPoints());
        assertEquals(GemColor.BLUE, card.getBonus());
        assertEquals(7, card.getCost().getTotalGems());
    }
    
    @Test
    @DisplayName("Should create typical Level 3 card (3-5 points, high cost)")
    void shouldCreateTypicalLevel3Card() {
        Map<GemColor, Integer> level3Cost = new EnumMap<>(GemColor.class);
        level3Cost.put(GemColor.WHITE, 3);
        level3Cost.put(GemColor.BLUE, 3);
        level3Cost.put(GemColor.GREEN, 5);
        level3Cost.put(GemColor.RED, 3);
        Cost cost = new Cost(level3Cost);
        
        Card card = new Card(3, 4, GemColor.GREEN, cost);
        
        assertEquals(3, card.getLevel());
        assertEquals(4, card.getPoints());
        assertEquals(GemColor.GREEN, card.getBonus());
        assertEquals(14, card.getCost().getTotalGems());
    }
    
    // ==================== Multiple Card Comparison Tests ====================
    
    @Test
    @DisplayName("Should handle multiple cards with same properties")
    void shouldHandleMultipleCardsWithSameProperties() {
        Card card1 = new Card(1, 0, GemColor.WHITE, standardCost);
        Card card2 = new Card(1, 0, GemColor.WHITE, standardCost);
        
        // Different objects
        assertNotSame(card1, card2);
        
        // But same values
        assertEquals(card1.getLevel(), card2.getLevel());
        assertEquals(card1.getPoints(), card2.getPoints());
        assertEquals(card1.getBonus(), card2.getBonus());
    }
    
    @Test
    @DisplayName("Should handle multiple cards with different properties")
    void shouldHandleMultipleCardsWithDifferentProperties() {
        Card card1 = new Card(1, 0, GemColor.WHITE, standardCost);
        Card card2 = new Card(2, 2, GemColor.BLUE, standardCost);
        Card card3 = new Card(3, 5, GemColor.GREEN, standardCost);
        
        assertNotEquals(card1.getLevel(), card2.getLevel());
        assertNotEquals(card1.getPoints(), card3.getPoints());
        assertNotEquals(card2.getBonus(), card3.getBonus());
    }
    
    @Test
    @DisplayName("Should handle cards providing all standard bonus colors")
    void shouldHandleAllBonusColors() {
        Card whiteCard = new Card(1, 0, GemColor.WHITE, standardCost);
        Card blueCard = new Card(1, 0, GemColor.BLUE, standardCost);
        Card greenCard = new Card(1, 0, GemColor.GREEN, standardCost);
        Card redCard = new Card(1, 0, GemColor.RED, standardCost);
        Card blackCard = new Card(1, 0, GemColor.BLACK, standardCost);
        
        assertEquals(GemColor.WHITE, whiteCard.getBonus());
        assertEquals(GemColor.BLUE, blueCard.getBonus());
        assertEquals(GemColor.GREEN, greenCard.getBonus());
        assertEquals(GemColor.RED, redCard.getBonus());
        assertEquals(GemColor.BLACK, blackCard.getBonus());
    }
    
    // ==================== Card Properties Consistency Tests ====================
    
    @Test
    @DisplayName("Level 1 cards should typically have 0-1 points")
    void level1CardsShouldHaveLowPoints() {
        Card card0 = new Card(1, 0, GemColor.WHITE, standardCost);
        Card card1 = new Card(1, 1, GemColor.BLUE, standardCost);
        
        assertTrue(card0.getPoints() >= 0 && card0.getPoints() <= 1);
        assertTrue(card1.getPoints() >= 0 && card1.getPoints() <= 1);
    }
    
    @Test
    @DisplayName("Level 2 cards should typically have 1-3 points")
    void level2CardsShouldHaveMediumPoints() {
        Card card1 = new Card(2, 1, GemColor.WHITE, standardCost);
        Card card2 = new Card(2, 2, GemColor.BLUE, standardCost);
        Card card3 = new Card(2, 3, GemColor.GREEN, standardCost);
        
        assertTrue(card1.getPoints() >= 1 && card1.getPoints() <= 3);
        assertTrue(card2.getPoints() >= 1 && card2.getPoints() <= 3);
        assertTrue(card3.getPoints() >= 1 && card3.getPoints() <= 3);
    }
    
    @Test
    @DisplayName("Level 3 cards should typically have 3-5 points")
    void level3CardsShouldHaveHighPoints() {
        Card card3 = new Card(3, 3, GemColor.WHITE, standardCost);
        Card card4 = new Card(3, 4, GemColor.BLUE, standardCost);
        Card card5 = new Card(3, 5, GemColor.GREEN, standardCost);
        
        assertTrue(card3.getPoints() >= 3 && card3.getPoints() <= 5);
        assertTrue(card4.getPoints() >= 3 && card4.getPoints() <= 5);
        assertTrue(card5.getPoints() >= 3 && card5.getPoints() <= 5);
    }
}