package edu.cs102.g04t06.game.rules.entities;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

// Generated by GPT-5 (Codex)
/**
 * Unit tests for GemColor enum.
 *
 */
class GemColorTest {

    @Test
    void declaresExpectedEnumValues() {
        GemColor[] expected = {
            GemColor.WHITE,
            GemColor.BLUE,
            GemColor.GREEN,
            GemColor.RED,
            GemColor.BLACK,
            GemColor.GOLD
        };

        assertArrayEquals(expected, GemColor.values());
    }

    @Test
    void valueOfParsesValidNames() {
        assertEquals(GemColor.RED, GemColor.valueOf("RED"));
        assertEquals(GemColor.GOLD, GemColor.valueOf("GOLD"));
    }
}
