package edu.cs102.g04t06.game.rules.entities;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;

import java.util.EnumMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;
// Generated by Claude Sonnet 4.5
/**
 * Unit tests for Noble entity.
 * 
 * @author CS102 Team G6
 * @version 1.0
 */

@DisplayName("Noble Tests")
class NobleTest {
    
    private Map<GemColor, Integer> standardRequirements;
    private Noble standardNoble;
    
    @BeforeEach
    void setUp() {
        // Standard noble: 3 points, requires 3 white, 3 blue, 3 green
        standardRequirements = new EnumMap<>(GemColor.class);
        standardRequirements.put(GemColor.WHITE, 3);
        standardRequirements.put(GemColor.BLUE, 3);
        standardRequirements.put(GemColor.GREEN, 3);
        
        standardNoble = new Noble(3, standardRequirements);
    }
    
    // ==================== Constructor Tests ====================
    
    @Test
    @DisplayName("Constructor should create noble with correct points")
    void constructorShouldSetCorrectPoints() {
        assertEquals(3, standardNoble.getPoints());
    }
    
    @Test
    @DisplayName("Constructor should create noble with correct requirements")
    void constructorShouldSetCorrectRequirements() {
        Map<GemColor, Integer> requirements = standardNoble.getRequirements();
        
        assertEquals(3, requirements.get(GemColor.WHITE));
        assertEquals(3, requirements.get(GemColor.BLUE));
        assertEquals(3, requirements.get(GemColor.GREEN));
    }
    
    @Test
    @DisplayName("Constructor should make defensive copy of requirements")
    void constructorShouldMakeDefensiveCopy() {
        Map<GemColor, Integer> original = new EnumMap<>(GemColor.class);
        original.put(GemColor.WHITE, 4);
        original.put(GemColor.BLUE, 4);
        
        Noble noble = new Noble(3, original);
        
        // Modify original map
        original.put(GemColor.WHITE, 999);
        original.put(GemColor.RED, 100);
        
        // Noble should be unchanged
        assertEquals(4, noble.getRequirements().get(GemColor.WHITE));
        assertNull(noble.getRequirements().get(GemColor.RED));
    }
    
    @Test
    @DisplayName("Constructor should handle empty requirements")
    void constructorShouldHandleEmptyRequirements() {
        Map<GemColor, Integer> emptyReq = new EnumMap<>(GemColor.class);
        Noble noble = new Noble(3, emptyReq);
        
        assertNotNull(noble.getRequirements());
        assertTrue(noble.getRequirements().isEmpty());
    }
    
    // ==================== getPoints() Tests ====================
    
    @Test
    @DisplayName("getPoints should return correct value")
    void getPointsShouldReturnCorrectValue() {
        assertEquals(3, standardNoble.getPoints());
    }
    
    @Test
    @DisplayName("getPoints should handle different point values")
    void getPointsShouldHandleDifferentValues() {
        Noble noble1 = new Noble(3, standardRequirements);
        Noble noble2 = new Noble(5, standardRequirements);
        
        assertEquals(3, noble1.getPoints());
        assertEquals(5, noble2.getPoints());
    }
    
    @Test
    @DisplayName("getPoints should handle zero points (edge case)")
    void getPointsShouldHandleZeroPoints() {
        Noble noble = new Noble(0, standardRequirements);
        assertEquals(0, noble.getPoints());
    }
    
    // ==================== getRequirements() Tests ====================
    
    @Test
    @DisplayName("getRequirements should return non-null map")
    void getRequirementsShouldReturnNonNull() {
        assertNotNull(standardNoble.getRequirements());
    }
    
    @Test
    @DisplayName("getRequirements should return correct requirements")
    void getRequirementsShouldReturnCorrectRequirements() {
        Map<GemColor, Integer> requirements = standardNoble.getRequirements();
        
        assertEquals(3, requirements.get(GemColor.WHITE));
        assertEquals(3, requirements.get(GemColor.BLUE));
        assertEquals(3, requirements.get(GemColor.GREEN));
        assertNull(requirements.get(GemColor.RED));
        assertNull(requirements.get(GemColor.BLACK));
    }
    
    @Test
    @DisplayName("getRequirements should return defensive copy")
    void getRequirementsShouldReturnDefensiveCopy() {
        Map<GemColor, Integer> requirements = standardNoble.getRequirements();
        
        // Modify retrieved map
        requirements.put(GemColor.WHITE, 999);
        requirements.put(GemColor.RED, 100);
        
        // Original noble should be unchanged
        assertEquals(3, standardNoble.getRequirements().get(GemColor.WHITE));
        assertNull(standardNoble.getRequirements().get(GemColor.RED));
    }
    
    // ==================== canBeClaimed() Tests ====================
    
    @Test
    @DisplayName("canBeClaimed should return true when player has exact bonuses")
    void canBeClaimedShouldReturnTrueWithExactBonuses() {
        Map<GemColor, Integer> bonuses = new EnumMap<>(GemColor.class);
        bonuses.put(GemColor.WHITE, 3);
        bonuses.put(GemColor.BLUE, 3);
        bonuses.put(GemColor.GREEN, 3);
        
        assertTrue(Noble.canBeClaimed(standardNoble, bonuses));
    }
    
    @Test
    @DisplayName("canBeClaimed should return true when player has more than required bonuses")
    void canBeClaimedShouldReturnTrueWithExcessBonuses() {
        Map<GemColor, Integer> bonuses = new EnumMap<>(GemColor.class);
        bonuses.put(GemColor.WHITE, 5);
        bonuses.put(GemColor.BLUE, 4);
        bonuses.put(GemColor.GREEN, 3);
        bonuses.put(GemColor.RED, 2);  // Extra bonus doesn't hurt
        
        assertTrue(Noble.canBeClaimed(standardNoble, bonuses));
    }
    
    @Test
    @DisplayName("canBeClaimed should return false when player lacks one bonus")
    void canBeClaimedShouldReturnFalseWhenLackingOne() {
        Map<GemColor, Integer> bonuses = new EnumMap<>(GemColor.class);
        bonuses.put(GemColor.WHITE, 3);
        bonuses.put(GemColor.BLUE, 2);  // One short
        bonuses.put(GemColor.GREEN, 3);
        
        assertFalse(Noble.canBeClaimed(standardNoble, bonuses));
    }
    
    @Test
    @DisplayName("canBeClaimed should return false when player lacks all bonuses")
    void canBeClaimedShouldReturnFalseWhenLackingAll() {
        Map<GemColor, Integer> bonuses = new EnumMap<>(GemColor.class);
        bonuses.put(GemColor.WHITE, 0);
        bonuses.put(GemColor.BLUE, 0);
        bonuses.put(GemColor.GREEN, 0);
        
        assertFalse(Noble.canBeClaimed(standardNoble, bonuses));
    }
    
    @Test
    @DisplayName("canBeClaimed should return false when player has no bonuses")
    void canBeClaimedShouldReturnFalseWithNoBonuses() {
        Map<GemColor, Integer> noBonuses = new EnumMap<>(GemColor.class);
        
        assertFalse(Noble.canBeClaimed(standardNoble, noBonuses));
    }
    
    @Test
    @DisplayName("canBeClaimed should return false when player has wrong color bonuses")
    void canBeClaimedShouldReturnFalseWithWrongColors() {
        Map<GemColor, Integer> bonuses = new EnumMap<>(GemColor.class);
        bonuses.put(GemColor.RED, 10);    // Wrong colors
        bonuses.put(GemColor.BLACK, 10);
        
        assertFalse(Noble.canBeClaimed(standardNoble, bonuses));
    }
    
    @Test
    @DisplayName("canBeClaimed should handle noble with single color requirement")
    void canBeClaimedShouldHandleSingleColorRequirement() {
        Map<GemColor, Integer> singleReq = new EnumMap<>(GemColor.class);
        singleReq.put(GemColor.WHITE, 4);
        Noble noble = new Noble(3, singleReq);
        
        Map<GemColor, Integer> bonuses = new EnumMap<>(GemColor.class);
        bonuses.put(GemColor.WHITE, 4);
        
        assertTrue(Noble.canBeClaimed(noble, bonuses));
    }
    
    @Test
    @DisplayName("canBeClaimed should handle noble with all five colors")
    void canBeClaimedShouldHandleAllFiveColors() {
        Map<GemColor, Integer> allColorsReq = new EnumMap<>(GemColor.class);
        allColorsReq.put(GemColor.WHITE, 2);
        allColorsReq.put(GemColor.BLUE, 2);
        allColorsReq.put(GemColor.GREEN, 2);
        allColorsReq.put(GemColor.RED, 2);
        allColorsReq.put(GemColor.BLACK, 2);
        Noble noble = new Noble(5, allColorsReq);
        
        Map<GemColor, Integer> bonuses = new EnumMap<>(GemColor.class);
        bonuses.put(GemColor.WHITE, 2);
        bonuses.put(GemColor.BLUE, 2);
        bonuses.put(GemColor.GREEN, 2);
        bonuses.put(GemColor.RED, 2);
        bonuses.put(GemColor.BLACK, 2);
        
        assertTrue(Noble.canBeClaimed(noble, bonuses));
    }
    
    @Test
    @DisplayName("canBeClaimed should return false when one color is short in five-color requirement")
    void canBeClaimedShouldFailWhenOneColorShortInFiveColors() {
        Map<GemColor, Integer> allColorsReq = new EnumMap<>(GemColor.class);
        allColorsReq.put(GemColor.WHITE, 2);
        allColorsReq.put(GemColor.BLUE, 2);
        allColorsReq.put(GemColor.GREEN, 2);
        allColorsReq.put(GemColor.RED, 2);
        allColorsReq.put(GemColor.BLACK, 2);
        Noble noble = new Noble(5, allColorsReq);
        
        Map<GemColor, Integer> bonuses = new EnumMap<>(GemColor.class);
        bonuses.put(GemColor.WHITE, 2);
        bonuses.put(GemColor.BLUE, 2);
        bonuses.put(GemColor.GREEN, 2);
        bonuses.put(GemColor.RED, 1);  // One short
        bonuses.put(GemColor.BLACK, 2);
        
        assertFalse(Noble.canBeClaimed(noble, bonuses));
    }
    
    // ==================== Immutability Tests ====================
    
    @Test
    @DisplayName("Noble should be immutable - points cannot change")
    void nobleShouldBeImmutablePoints() {
        int originalPoints = standardNoble.getPoints();
        
        // Points should remain the same
        assertEquals(originalPoints, standardNoble.getPoints());
        assertEquals(3, standardNoble.getPoints());
    }
    
    @Test
    @DisplayName("Noble should be immutable - requirements cannot change via getRequirements")
    void nobleShouldBeImmutableRequirements() {
        Map<GemColor, Integer> requirements1 = standardNoble.getRequirements();
        requirements1.clear();
        
        Map<GemColor, Integer> requirements2 = standardNoble.getRequirements();
        
        // Should still have original values
        assertEquals(3, requirements2.get(GemColor.WHITE));
        assertEquals(3, standardNoble.getRequirements().get(GemColor.WHITE));
    }
    
    // ==================== Realistic Noble Tests ====================
    
    @Test
    @DisplayName("Should create realistic noble requiring 3-3-3 bonuses")
    void shouldCreateRealisticNoble333() {
        Map<GemColor, Integer> req = new EnumMap<>(GemColor.class);
        req.put(GemColor.WHITE, 3);
        req.put(GemColor.BLUE, 3);
        req.put(GemColor.GREEN, 3);
        
        Noble noble = new Noble(3, req);
        
        assertEquals(3, noble.getPoints());
        assertEquals(3, noble.getRequirements().get(GemColor.WHITE));
        assertEquals(3, noble.getRequirements().get(GemColor.BLUE));
        assertEquals(3, noble.getRequirements().get(GemColor.GREEN));
    }
    
    @Test
    @DisplayName("Should create realistic noble requiring 4-4 bonuses")
    void shouldCreateRealisticNoble44() {
        Map<GemColor, Integer> req = new EnumMap<>(GemColor.class);
        req.put(GemColor.RED, 4);
        req.put(GemColor.BLACK, 4);
        
        Noble noble = new Noble(3, req);
        
        assertEquals(3, noble.getPoints());
        assertEquals(4, noble.getRequirements().get(GemColor.RED));
        assertEquals(4, noble.getRequirements().get(GemColor.BLACK));
    }
    
    @Test
    @DisplayName("Should create all 10 standard Splendor nobles")
    void shouldCreateAllStandardNobles() {
        // Noble 1: 3W, 3B, 3G
        Map<GemColor, Integer> req1 = new EnumMap<>(GemColor.class);
        req1.put(GemColor.WHITE, 3);
        req1.put(GemColor.BLUE, 3);
        req1.put(GemColor.GREEN, 3);
        Noble noble1 = new Noble(3, req1);
        
        // Noble 2: 3B, 3G, 3R
        Map<GemColor, Integer> req2 = new EnumMap<>(GemColor.class);
        req2.put(GemColor.BLUE, 3);
        req2.put(GemColor.GREEN, 3);
        req2.put(GemColor.RED, 3);
        Noble noble2 = new Noble(3, req2);
        
        // Noble 3: 3W, 3G, 3K
        Map<GemColor, Integer> req3 = new EnumMap<>(GemColor.class);
        req3.put(GemColor.WHITE, 3);
        req3.put(GemColor.GREEN, 3);
        req3.put(GemColor.BLACK, 3);
        Noble noble3 = new Noble(3, req3);
        
        // Noble 4: 3W, 3B, 3K
        Map<GemColor, Integer> req4 = new EnumMap<>(GemColor.class);
        req4.put(GemColor.WHITE, 3);
        req4.put(GemColor.BLUE, 3);
        req4.put(GemColor.BLACK, 3);
        Noble noble4 = new Noble(3, req4);
        
        // Noble 5: 3B, 3R, 3K
        Map<GemColor, Integer> req5 = new EnumMap<>(GemColor.class);
        req5.put(GemColor.BLUE, 3);
        req5.put(GemColor.RED, 3);
        req5.put(GemColor.BLACK, 3);
        Noble noble5 = new Noble(3, req5);
        
        // Noble 6: 4W, 4B
        Map<GemColor, Integer> req6 = new EnumMap<>(GemColor.class);
        req6.put(GemColor.WHITE, 4);
        req6.put(GemColor.BLUE, 4);
        Noble noble6 = new Noble(3, req6);
        
        // Noble 7: 4G, 4R
        Map<GemColor, Integer> req7 = new EnumMap<>(GemColor.class);
        req7.put(GemColor.GREEN, 4);
        req7.put(GemColor.RED, 4);
        Noble noble7 = new Noble(3, req7);
        
        // Noble 8: 4W, 4K
        Map<GemColor, Integer> req8 = new EnumMap<>(GemColor.class);
        req8.put(GemColor.WHITE, 4);
        req8.put(GemColor.BLACK, 4);
        Noble noble8 = new Noble(3, req8);
        
        // Noble 9: 4B, 4K
        Map<GemColor, Integer> req9 = new EnumMap<>(GemColor.class);
        req9.put(GemColor.BLUE, 4);
        req9.put(GemColor.BLACK, 4);
        Noble noble9 = new Noble(3, req9);
        
        // Noble 10: 4G, 4W
        Map<GemColor, Integer> req10 = new EnumMap<>(GemColor.class);
        req10.put(GemColor.GREEN, 4);
        req10.put(GemColor.WHITE, 4);
        Noble noble10 = new Noble(3, req10);
        
        // All should be valid
        assertNotNull(noble1);
        assertNotNull(noble2);
        assertNotNull(noble3);
        assertNotNull(noble4);
        assertNotNull(noble5);
        assertNotNull(noble6);
        assertNotNull(noble7);
        assertNotNull(noble8);
        assertNotNull(noble9);
        assertNotNull(noble10);
        
        // All should be worth 3 points
        assertEquals(3, noble1.getPoints());
        assertEquals(3, noble5.getPoints());
        assertEquals(3, noble10.getPoints());
    }
    
    // ==================== Edge Case Tests ====================
    
    @Test
    @DisplayName("Should handle noble with zero requirements (edge case)")
    void shouldHandleNobleWithZeroRequirements() {
        Map<GemColor, Integer> emptyReq = new EnumMap<>(GemColor.class);
        Noble noble = new Noble(3, emptyReq);
        
        Map<GemColor, Integer> bonuses = new EnumMap<>(GemColor.class);
        bonuses.put(GemColor.WHITE, 5);
        
        // Should be claimable since no requirements
        assertTrue(Noble.canBeClaimed(noble, bonuses));
    }
    
    @Test
    @DisplayName("Should handle noble with high requirements")
    void shouldHandleNobleWithHighRequirements() {
        Map<GemColor, Integer> highReq = new EnumMap<>(GemColor.class);
        highReq.put(GemColor.WHITE, 10);
        highReq.put(GemColor.BLUE, 10);
        Noble noble = new Noble(5, highReq);
        
        Map<GemColor, Integer> bonuses = new EnumMap<>(GemColor.class);
        bonuses.put(GemColor.WHITE, 10);
        bonuses.put(GemColor.BLUE, 10);
        
        assertTrue(Noble.canBeClaimed(noble, bonuses));
    }
    
    @Test
    @DisplayName("Should handle noble with single bonus requirement of 1")
    void shouldHandleNobleWithSingleBonusOfOne() {
        Map<GemColor, Integer> req = new EnumMap<>(GemColor.class);
        req.put(GemColor.RED, 1);
        Noble noble = new Noble(3, req);
        
        Map<GemColor, Integer> bonuses = new EnumMap<>(GemColor.class);
        bonuses.put(GemColor.RED, 1);
        
        assertTrue(Noble.canBeClaimed(noble, bonuses));
    }
    
    // ==================== Boundary Tests ====================
    
    @Test
    @DisplayName("canBeClaimed should handle exact match at boundary")
    void canBeClaimedShouldHandleExactBoundary() {
        Map<GemColor, Integer> req = new EnumMap<>(GemColor.class);
        req.put(GemColor.WHITE, 5);
        Noble noble = new Noble(3, req);
        
        // Exactly at boundary
        Map<GemColor, Integer> exactBonuses = new EnumMap<>(GemColor.class);
        exactBonuses.put(GemColor.WHITE, 5);
        assertTrue(Noble.canBeClaimed(noble, exactBonuses));
        
        // One below boundary
        Map<GemColor, Integer> belowBonuses = new EnumMap<>(GemColor.class);
        belowBonuses.put(GemColor.WHITE, 4);
        assertFalse(Noble.canBeClaimed(noble, belowBonuses));
        
        // One above boundary
        Map<GemColor, Integer> aboveBonuses = new EnumMap<>(GemColor.class);
        aboveBonuses.put(GemColor.WHITE, 6);
        assertTrue(Noble.canBeClaimed(noble, aboveBonuses));
    }
    
    // ==================== Multiple Nobles Comparison Tests ====================
    
    @Test
    @DisplayName("Should handle multiple nobles with same requirements")
    void shouldHandleMultipleNoblesWithSameRequirements() {
        Noble noble1 = new Noble(3, standardRequirements);
        Noble noble2 = new Noble(3, standardRequirements);
        
        // Different objects
        assertNotSame(noble1, noble2);
        
        // But same values
        assertEquals(noble1.getPoints(), noble2.getPoints());
        assertEquals(noble1.getRequirements().get(GemColor.WHITE), 
                    noble2.getRequirements().get(GemColor.WHITE));
    }
    
    @Test
    @DisplayName("Should handle nobles with different requirements for same bonus colors")
    void shouldHandleNoblesWithDifferentRequirements() {
        Map<GemColor, Integer> req1 = new EnumMap<>(GemColor.class);
        req1.put(GemColor.WHITE, 3);
        req1.put(GemColor.BLUE, 3);
        
        Map<GemColor, Integer> req2 = new EnumMap<>(GemColor.class);
        req2.put(GemColor.WHITE, 4);
        req2.put(GemColor.BLUE, 4);
        
        Noble noble1 = new Noble(3, req1);
        Noble noble2 = new Noble(3, req2);
        
        Map<GemColor, Integer> bonuses = new EnumMap<>(GemColor.class);
        bonuses.put(GemColor.WHITE, 3);
        bonuses.put(GemColor.BLUE, 3);
        
        // Can claim noble1 but not noble2
        assertTrue(Noble.canBeClaimed(noble1, bonuses));
        assertFalse(Noble.canBeClaimed(noble2, bonuses));
    }
    
    // ==================== Static Method Tests ====================
    
    @Test
    @DisplayName("canBeClaimed should be callable as static method")
    void canBeClaimedShouldBeStaticMethod() {
        Map<GemColor, Integer> bonuses = new EnumMap<>(GemColor.class);
        bonuses.put(GemColor.WHITE, 3);
        bonuses.put(GemColor.BLUE, 3);
        bonuses.put(GemColor.GREEN, 3);
        
        // Should be callable as Noble.canBeClaimed()
        boolean result = Noble.canBeClaimed(standardNoble, bonuses);
        assertTrue(result);
    }
    
    @Test
    @DisplayName("canBeClaimed should work with different noble instances")
    void canBeClaimedShouldWorkWithDifferentInstances() {
        Map<GemColor, Integer> req1 = new EnumMap<>(GemColor.class);
        req1.put(GemColor.WHITE, 3);
        Noble noble1 = new Noble(3, req1);
        
        Map<GemColor, Integer> req2 = new EnumMap<>(GemColor.class);
        req2.put(GemColor.BLUE, 4);
        Noble noble2 = new Noble(3, req2);
        
        Map<GemColor, Integer> bonuses = new EnumMap<>(GemColor.class);
        bonuses.put(GemColor.WHITE, 3);
        bonuses.put(GemColor.BLUE, 4);
        
        // Both should be claimable
        assertTrue(Noble.canBeClaimed(noble1, bonuses));
        assertTrue(Noble.canBeClaimed(noble2, bonuses));
    }
}