package edu.cs102.g04t06.game.rules.entities;

import edu.cs102.g04t06.game.rules.valueobjects.*;
import edu.cs102.g04t06.game.rules.entities.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;

import java.util.EnumMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

// Generated by Sonnet 4.5
/**
 * Unit tests for Player entity.
 * 
 * @author CS102 Team G6
 * @version 1.0
 */
@DisplayName("Player Tests")
class PlayerTest {
    
    private Player player;
    private Card whiteCard;
    private Card blueCard;
    private Card greenCard;
    private Noble standardNoble;
    private Cost standardCost;
    
    @BeforeEach
    void setUp() {
        // Create player
        player = new Player("Alice", 0);
        
        // Create standard cost
        Map<GemColor, Integer> costMap = new EnumMap<>(GemColor.class);
        costMap.put(GemColor.WHITE, 2);
        costMap.put(GemColor.BLUE, 1);
        standardCost = new Cost(costMap);
        
        // Create cards with different bonuses
        whiteCard = new Card(1, 0, GemColor.WHITE, standardCost);
        blueCard = new Card(1, 1, GemColor.BLUE, standardCost);
        greenCard = new Card(2, 2, GemColor.GREEN, standardCost);
        
        // Create noble
        Map<GemColor, Integer> nobleReq = new EnumMap<>(GemColor.class);
        nobleReq.put(GemColor.WHITE, 3);
        nobleReq.put(GemColor.BLUE, 3);
        standardNoble = new Noble(3, nobleReq);
    }
    
    // ==================== Constructor Tests ====================
    
    @Test
    @DisplayName("Constructor should create player with correct name")
    void constructorShouldSetCorrectName() {
        assertEquals("Alice", player.getName());
    }
    
    @Test
    @DisplayName("Constructor should create player with correct turn order")
    void constructorShouldSetCorrectTurnOrder() {
        assertEquals(0, player.getTurnOrder());
        
        Player player2 = new Player("Bob", 1);
        assertEquals(1, player2.getTurnOrder());
    }
    
    @Test
    @DisplayName("Constructor should initialize empty collections")
    void constructorShouldInitializeEmptyCollections() {
        assertEquals(0, player.getPurchasedCards().size());
        assertEquals(0, player.getReservedCards().size());
        assertEquals(0, player.getClaimedNobles().size());
        assertEquals(0, player.getGemCount());
    }
    
    @Test
    @DisplayName("Constructor should handle different player names")
    void constructorShouldHandleDifferentNames() {
        Player p1 = new Player("", 0);
        Player p2 = new Player("VeryLongPlayerName123", 0);
        Player p3 = new Player("中文名字", 0);
        
        assertEquals("", p1.getName());
        assertEquals("VeryLongPlayerName123", p2.getName());
        assertEquals("中文名字", p3.getName());
    }
    
    // ==================== getName() Tests ====================
    
    @Test
    @DisplayName("getName should return correct name")
    void getNameShouldReturnCorrectName() {
        assertEquals("Alice", player.getName());
    }
    
    @Test
    @DisplayName("getName should be immutable")
    void getNameShouldBeImmutable() {
        String name = player.getName();
        assertEquals("Alice", name);
        
        // Name should remain unchanged
        assertEquals("Alice", player.getName());
    }
    
    // ==================== getTurnOrder() Tests ====================
    
    @Test
    @DisplayName("getTurnOrder should return correct order")
    void getTurnOrderShouldReturnCorrectOrder() {
        Player p0 = new Player("First", 0);
        Player p1 = new Player("Second", 1);
        Player p2 = new Player("Third", 2);
        Player p3 = new Player("Fourth", 3);
        
        assertEquals(0, p0.getTurnOrder());
        assertEquals(1, p1.getTurnOrder());
        assertEquals(2, p2.getTurnOrder());
        assertEquals(3, p3.getTurnOrder());
    }
    
    @Test
    @DisplayName("getTurnOrder should be immutable")
    void getTurnOrderShouldBeImmutable() {
        int order = player.getTurnOrder();
        assertEquals(0, order);
        
        // Turn order should remain unchanged
        assertEquals(0, player.getTurnOrder());
    }
    
    // ==================== getPurchasedCards() Tests ====================
    
    @Test
    @DisplayName("getPurchasedCards should return empty list initially")
    void getPurchasedCardsShouldReturnEmptyInitially() {
        assertTrue(player.getPurchasedCards().isEmpty());
        assertEquals(0, player.getPurchasedCards().size());
    }
    
    @Test
    @DisplayName("getPurchasedCards should return cards after adding")
    void getPurchasedCardsShouldReturnCardsAfterAdding() {
        player.addCard(whiteCard);
        player.addCard(blueCard);
        
        assertEquals(2, player.getPurchasedCards().size());
        assertTrue(player.getPurchasedCards().contains(whiteCard));
        assertTrue(player.getPurchasedCards().contains(blueCard));
    }
    
    // ==================== getReservedCards() Tests ====================
    
    @Test
    @DisplayName("getReservedCards should return empty list initially")
    void getReservedCardsShouldReturnEmptyInitially() {
        assertTrue(player.getReservedCards().isEmpty());
        assertEquals(0, player.getReservedCards().size());
    }
    
    @Test
    @DisplayName("getReservedCards should return cards after reserving")
    void getReservedCardsShouldReturnCardsAfterReserving() {
        player.addReservedCard(whiteCard);
        player.addReservedCard(blueCard);
        
        assertEquals(2, player.getReservedCards().size());
        assertTrue(player.getReservedCards().contains(whiteCard));
        assertTrue(player.getReservedCards().contains(blueCard));
    }
    
    // ==================== getGems() Tests ====================
    
    @Test
    @DisplayName("getGems should return empty GemCollection initially")
    void getGemsShouldReturnEmptyInitially() {
        assertTrue(player.getGems().isEmpty());
        assertEquals(0, player.getGems().getTotalCount());
    }
    
    @Test
    @DisplayName("getGems should return current gems")
    void getGemsShouldReturnCurrentGems() {
        GemCollection gems = new GemCollection();
        gems = gems.add(GemColor.WHITE, 3);
        gems = gems.add(GemColor.BLUE, 2);
        
        player.addGems(gems);
        
        assertEquals(5, player.getGems().getTotalCount());
        assertEquals(3, player.getGems().getCount(GemColor.WHITE));
        assertEquals(2, player.getGems().getCount(GemColor.BLUE));
    }
    
    // ==================== getClaimedNobles() Tests ====================
    
    @Test
    @DisplayName("getClaimedNobles should return empty list initially")
    void getClaimedNoblesShouldReturnEmptyInitially() {
        assertTrue(player.getClaimedNobles().isEmpty());
        assertEquals(0, player.getClaimedNobles().size());
    }
    
    @Test
    @DisplayName("getClaimedNobles should return nobles after claiming")
    void getClaimedNoblesShouldReturnNoblesAfterClaiming() {
        player.claimNoble(standardNoble);
        
        assertEquals(1, player.getClaimedNobles().size());
        assertTrue(player.getClaimedNobles().contains(standardNoble));
    }
    
    // ==================== getGemCount() Tests ====================
    
    @Test
    @DisplayName("getGemCount should return 0 initially")
    void getGemCountShouldReturnZeroInitially() {
        assertEquals(0, player.getGemCount());
    }
    
    @Test
    @DisplayName("getGemCount should return total gem count")
    void getGemCountShouldReturnTotalCount() {
        GemCollection gems = new GemCollection();
        gems = gems.add(GemColor.WHITE, 3);
        gems = gems.add(GemColor.BLUE, 2);
        gems = gems.add(GemColor.GREEN, 1);
        
        player.addGems(gems);
        
        assertEquals(6, player.getGemCount());
    }
    
    @Test
    @DisplayName("getGemCount should update after adding gems")
    void getGemCountShouldUpdateAfterAddingGems() {
        assertEquals(0, player.getGemCount());
        
        GemCollection gems1 = new GemCollection().add(GemColor.WHITE, 2);
        player.addGems(gems1);
        assertEquals(2, player.getGemCount());
        
        GemCollection gems2 = new GemCollection().add(GemColor.BLUE, 3);
        player.addGems(gems2);
        assertEquals(5, player.getGemCount());
    }
    
    @Test
    @DisplayName("getGemCount should update after deducting gems")
    void getGemCountShouldUpdateAfterDeductingGems() {
        GemCollection gems = new GemCollection().add(GemColor.WHITE, 5);
        player.addGems(gems);
        assertEquals(5, player.getGemCount());
        
        GemCollection toDeduct = new GemCollection().add(GemColor.WHITE, 2);
        player.deductGems(toDeduct);
        assertEquals(3, player.getGemCount());
    }
    
    // ==================== getPoints() Tests ====================
    
    @Test
    @DisplayName("getPoints should return 0 initially")
    void getPointsShouldReturnZeroInitially() {
        assertEquals(0, player.getPoints());
    }
    
    @Test
    @DisplayName("getPoints should return points from purchased cards")
    void getPointsShouldReturnPointsFromCards() {
        player.addCard(whiteCard);  // 0 points
        player.addCard(blueCard);   // 1 point
        player.addCard(greenCard);  // 2 points
        
        assertEquals(3, player.getPoints());
    }
    
    @Test
    @DisplayName("getPoints should return points from nobles")
    void getPointsShouldReturnPointsFromNobles() {
        player.claimNoble(standardNoble);  // 3 points
        
        assertEquals(3, player.getPoints());
    }
    
    @Test
    @DisplayName("getPoints should return combined points from cards and nobles")
    void getPointsShouldReturnCombinedPoints() {
        player.addCard(blueCard);    // 1 point
        player.addCard(greenCard);   // 2 points
        player.claimNoble(standardNoble);  // 3 points
        
        assertEquals(6, player.getPoints());
    }
    
    @Test
    @DisplayName("getPoints should handle multiple nobles")
    void getPointsShouldHandleMultipleNobles() {
        Map<GemColor, Integer> req = new EnumMap<>(GemColor.class);
        req.put(GemColor.RED, 4);
        Noble noble2 = new Noble(3, req);
        
        player.claimNoble(standardNoble);  // 3 points
        player.claimNoble(noble2);         // 3 points
        
        assertEquals(6, player.getPoints());
    }
    
    @Test
    @DisplayName("getPoints should recalculate correctly after changes")
    void getPointsShouldRecalculateAfterChanges() {
        assertEquals(0, player.getPoints());
        
        player.addCard(greenCard);  // 2 points
        assertEquals(2, player.getPoints());
        
        player.addCard(blueCard);  // +1 point
        assertEquals(3, player.getPoints());
        
        player.claimNoble(standardNoble);  // +3 points
        assertEquals(6, player.getPoints());
    }
    
    // ==================== calculateBonuses() Tests ====================
    
    @Test
    @DisplayName("calculateBonuses should return empty map initially")
    void calculateBonusesShouldReturnEmptyInitially() {
        Map<GemColor, Integer> bonuses = player.calculateBonuses();
        
        assertEquals(0, bonuses.getOrDefault(GemColor.WHITE, 0));
        assertEquals(0, bonuses.getOrDefault(GemColor.BLUE, 0));
    }
    
    @Test
    @DisplayName("calculateBonuses should return bonuses from single card")
    void calculateBonusesShouldReturnBonusesFromSingleCard() {
        player.addCard(whiteCard);  // WHITE bonus
        
        Map<GemColor, Integer> bonuses = player.calculateBonuses();
        
        assertEquals(1, bonuses.get(GemColor.WHITE));
    }
    
    @Test
    @DisplayName("calculateBonuses should count multiple cards of same color")
    void calculateBonusesShouldCountMultipleCardsOfSameColor() {
        player.addCard(whiteCard);  // WHITE bonus
        
        Card anotherWhite = new Card(1, 0, GemColor.WHITE, standardCost);
        player.addCard(anotherWhite);  // Another WHITE bonus
        
        Map<GemColor, Integer> bonuses = player.calculateBonuses();
        
        assertEquals(2, bonuses.get(GemColor.WHITE));
    }
    
    @Test
    @DisplayName("calculateBonuses should count bonuses from different colors")
    void calculateBonusesShouldCountDifferentColors() {
        player.addCard(whiteCard);  // WHITE bonus
        player.addCard(blueCard);   // BLUE bonus
        player.addCard(greenCard);  // GREEN bonus
        
        Map<GemColor, Integer> bonuses = player.calculateBonuses();
        
        assertEquals(1, bonuses.get(GemColor.WHITE));
        assertEquals(1, bonuses.get(GemColor.BLUE));
        assertEquals(1, bonuses.get(GemColor.GREEN));
    }
    
    @Test
    @DisplayName("calculateBonuses should handle all 5 standard colors")
    void calculateBonusesShouldHandleAllStandardColors() {
        player.addCard(new Card(1, 0, GemColor.WHITE, standardCost));
        player.addCard(new Card(1, 0, GemColor.BLUE, standardCost));
        player.addCard(new Card(1, 0, GemColor.GREEN, standardCost));
        player.addCard(new Card(1, 0, GemColor.RED, standardCost));
        player.addCard(new Card(1, 0, GemColor.BLACK, standardCost));
        
        Map<GemColor, Integer> bonuses = player.calculateBonuses();
        
        assertEquals(1, bonuses.get(GemColor.WHITE));
        assertEquals(1, bonuses.get(GemColor.BLUE));
        assertEquals(1, bonuses.get(GemColor.GREEN));
        assertEquals(1, bonuses.get(GemColor.RED));
        assertEquals(1, bonuses.get(GemColor.BLACK));
    }
    
    @Test
    @DisplayName("calculateBonuses should handle many cards of mixed colors")
    void calculateBonusesShouldHandleManyCards() {
        // Add 3 white, 2 blue, 1 green
        player.addCard(new Card(1, 0, GemColor.WHITE, standardCost));
        player.addCard(new Card(1, 0, GemColor.WHITE, standardCost));
        player.addCard(new Card(1, 0, GemColor.WHITE, standardCost));
        player.addCard(new Card(1, 0, GemColor.BLUE, standardCost));
        player.addCard(new Card(1, 0, GemColor.BLUE, standardCost));
        player.addCard(new Card(1, 0, GemColor.GREEN, standardCost));
        
        Map<GemColor, Integer> bonuses = player.calculateBonuses();
        
        assertEquals(3, bonuses.get(GemColor.WHITE));
        assertEquals(2, bonuses.get(GemColor.BLUE));
        assertEquals(1, bonuses.get(GemColor.GREEN));
    }
    
    // ==================== addCard() Tests ====================
    
    @Test
    @DisplayName("addCard should add card to purchased cards")
    void addCardShouldAddToPurchasedCards() {
        player.addCard(whiteCard);
        
        assertEquals(1, player.getPurchasedCards().size());
        assertTrue(player.getPurchasedCards().contains(whiteCard));
    }
    
    @Test
    @DisplayName("addCard should add multiple cards")
    void addCardShouldAddMultipleCards() {
        player.addCard(whiteCard);
        player.addCard(blueCard);
        player.addCard(greenCard);
        
        assertEquals(3, player.getPurchasedCards().size());
    }
    
    @Test
    @DisplayName("addCard should update bonuses")
    void addCardShouldUpdateBonuses() {
        assertEquals(0, player.calculateBonuses().getOrDefault(GemColor.WHITE, 0));
        
        player.addCard(whiteCard);
        
        assertEquals(1, player.calculateBonuses().get(GemColor.WHITE));
    }
    
    @Test
    @DisplayName("addCard should update points")
    void addCardShouldUpdatePoints() {
        assertEquals(0, player.getPoints());
        
        player.addCard(greenCard);  // 2 points
        
        assertEquals(2, player.getPoints());
    }
    
    // ==================== addReservedCard() Tests ====================
    
    @Test
    @DisplayName("addReservedCard should add card to reserved cards")
    void addReservedCardShouldAddToReservedCards() {
        player.addReservedCard(whiteCard);
        
        assertEquals(1, player.getReservedCards().size());
        assertTrue(player.getReservedCards().contains(whiteCard));
    }
    
    @Test
    @DisplayName("addReservedCard should add multiple cards")
    void addReservedCardShouldAddMultipleCards() {
        player.addReservedCard(whiteCard);
        player.addReservedCard(blueCard);
        player.addReservedCard(greenCard);
        
        assertEquals(3, player.getReservedCards().size());
    }
    
    @Test
    @DisplayName("addReservedCard should not affect bonuses")
    void addReservedCardShouldNotAffectBonuses() {
        player.addReservedCard(whiteCard);
        
        Map<GemColor, Integer> bonuses = player.calculateBonuses();
        assertEquals(0, bonuses.getOrDefault(GemColor.WHITE, 0));
    }
    
    @Test
    @DisplayName("addReservedCard should not affect points")
    void addReservedCardShouldNotAffectPoints() {
        player.addReservedCard(greenCard);  // 2 points, but reserved
        
        assertEquals(0, player.getPoints());
    }
    
    // ==================== removeReservedCard() Tests ====================
    
    @Test
    @DisplayName("removeReservedCard should remove card from reserved cards")
    void removeReservedCardShouldRemoveFromReservedCards() {
        player.addReservedCard(whiteCard);
        player.addReservedCard(blueCard);
        
        player.removeReservedCard(whiteCard);
        
        assertEquals(1, player.getReservedCards().size());
        assertFalse(player.getReservedCards().contains(whiteCard));
        assertTrue(player.getReservedCards().contains(blueCard));
    }
    
    @Test
    @DisplayName("removeReservedCard should handle removing last card")
    void removeReservedCardShouldHandleRemovingLastCard() {
        player.addReservedCard(whiteCard);
        
        player.removeReservedCard(whiteCard);
        
        assertTrue(player.getReservedCards().isEmpty());
    }
    
    @Test
    @DisplayName("removeReservedCard should not crash when removing non-existent card")
    void removeReservedCardShouldNotCrashOnNonExistent() {
        player.addReservedCard(whiteCard);
        
        assertDoesNotThrow(() -> player.removeReservedCard(blueCard));
    }
    
    // ==================== addGems() Tests ====================
    
    @Test
    @DisplayName("addGems should add gems to player")
    void addGemsShouldAddGemsToPlayer() {
        GemCollection gems = new GemCollection().add(GemColor.WHITE, 3);
        
        player.addGems(gems);
        
        assertEquals(3, player.getGemCount());
        assertEquals(3, player.getGems().getCount(GemColor.WHITE));
    }
    
    @Test
    @DisplayName("addGems should add multiple times cumulatively")
    void addGemsShouldAddCumulatively() {
        GemCollection gems1 = new GemCollection().add(GemColor.WHITE, 2);
        GemCollection gems2 = new GemCollection().add(GemColor.WHITE, 3);
        
        player.addGems(gems1);
        player.addGems(gems2);
        
        assertEquals(5, player.getGems().getCount(GemColor.WHITE));
    }
    
    @Test
    @DisplayName("addGems should handle different colors")
    void addGemsShouldHandleDifferentColors() {
        GemCollection gems1 = new GemCollection().add(GemColor.WHITE, 2);
        GemCollection gems2 = new GemCollection().add(GemColor.BLUE, 3);
        
        player.addGems(gems1);
        player.addGems(gems2);
        
        assertEquals(2, player.getGems().getCount(GemColor.WHITE));
        assertEquals(3, player.getGems().getCount(GemColor.BLUE));
        assertEquals(5, player.getGemCount());
    }
    
    @Test
    @DisplayName("addGems should handle empty GemCollection")
    void addGemsShouldHandleEmptyCollection() {
        GemCollection empty = new GemCollection();
        
        player.addGems(empty);
        
        assertEquals(0, player.getGemCount());
    }
    
    // ==================== deductGems() Tests ====================
    
    @Test
    @DisplayName("deductGems should deduct gems from player")
    void deductGemsShouldDeductGemsFromPlayer() {
        GemCollection initial = new GemCollection().add(GemColor.WHITE, 5);
        player.addGems(initial);
        
        GemCollection toDeduct = new GemCollection().add(GemColor.WHITE, 2);
        player.deductGems(toDeduct);
        
        assertEquals(3, player.getGems().getCount(GemColor.WHITE));
        assertEquals(3, player.getGemCount());
    }
    
    @Test
    @DisplayName("deductGems should handle multiple colors")
    void deductGemsShouldHandleMultipleColors() {
        GemCollection initial = new GemCollection()
            .add(GemColor.WHITE, 5)
            .add(GemColor.BLUE, 4);
        player.addGems(initial);
        
        GemCollection toDeduct = new GemCollection()
            .add(GemColor.WHITE, 2)
            .add(GemColor.BLUE, 1);
        player.deductGems(toDeduct);
        
        assertEquals(3, player.getGems().getCount(GemColor.WHITE));
        assertEquals(3, player.getGems().getCount(GemColor.BLUE));
        assertEquals(6, player.getGemCount());
    }
    
    @Test
    @DisplayName("deductGems should handle deducting all gems of a color")
    void deductGemsShouldHandleDeductingAll() {
        GemCollection initial = new GemCollection().add(GemColor.WHITE, 3);
        player.addGems(initial);
        
        GemCollection toDeduct = new GemCollection().add(GemColor.WHITE, 3);
        player.deductGems(toDeduct);
        
        assertEquals(0, player.getGems().getCount(GemColor.WHITE));
        assertEquals(0, player.getGemCount());
    }
    
    // ==================== claimNoble() Tests ====================
    
    @Test
    @DisplayName("claimNoble should add noble to claimed nobles")
    void claimNobleShouldAddToClaimedNobles() {
        player.claimNoble(standardNoble);
        
        assertEquals(1, player.getClaimedNobles().size());
        assertTrue(player.getClaimedNobles().contains(standardNoble));
    }
    
    @Test
    @DisplayName("claimNoble should add multiple nobles")
    void claimNobleShouldAddMultipleNobles() {
        Map<GemColor, Integer> req2 = new EnumMap<>(GemColor.class);
        req2.put(GemColor.RED, 4);
        Noble noble2 = new Noble(3, req2);
        
        player.claimNoble(standardNoble);
        player.claimNoble(noble2);
        
        assertEquals(2, player.getClaimedNobles().size());
    }
    
    @Test
    @DisplayName("claimNoble should update points")
    void claimNobleShouldUpdatePoints() {
        assertEquals(0, player.getPoints());
        
        player.claimNoble(standardNoble);  // 3 points
        
        assertEquals(3, player.getPoints());
    }
    
    // ==================== Integration Tests ====================
    
    @Test
    @DisplayName("Full workflow: add gems, reserve card, buy reserved card")
    void fullWorkflowReserveAndBuyCard() {
        // Reserve a card
        player.addReservedCard(greenCard);
        assertEquals(1, player.getReservedCards().size());
        assertEquals(0, player.getPurchasedCards().size());
        assertEquals(0, player.getPoints());
        
        // Add gems
        GemCollection gems = new GemCollection()
            .add(GemColor.WHITE, 3)
            .add(GemColor.BLUE, 2);
        player.addGems(gems);
        assertEquals(5, player.getGemCount());
        
        // "Buy" reserved card (remove from reserved, add to purchased, deduct gems)
        player.removeReservedCard(greenCard);
        player.addCard(greenCard);
        GemCollection cost = new GemCollection()
            .add(GemColor.WHITE, 2)
            .add(GemColor.BLUE, 1);
        player.deductGems(cost);
        
        assertEquals(0, player.getReservedCards().size());
        assertEquals(1, player.getPurchasedCards().size());
        assertEquals(2, player.getGemCount());
        assertEquals(2, player.getPoints());
    }
    
    @Test
    @DisplayName("Full workflow: buy cards, earn bonuses, claim noble")
    void fullWorkflowBuyCardsAndClaimNoble() {
        // Buy cards to get bonuses
        player.addCard(new Card(1, 0, GemColor.WHITE, standardCost));
        player.addCard(new Card(1, 0, GemColor.WHITE, standardCost));
        player.addCard(new Card(1, 0, GemColor.WHITE, standardCost));
        player.addCard(new Card(1, 0, GemColor.BLUE, standardCost));
        player.addCard(new Card(1, 0, GemColor.BLUE, standardCost));
        player.addCard(new Card(1, 0, GemColor.BLUE, standardCost));
        
        // Check bonuses
        Map<GemColor, Integer> bonuses = player.calculateBonuses();
        assertEquals(3, bonuses.get(GemColor.WHITE));
        assertEquals(3, bonuses.get(GemColor.BLUE));
        
        // Claim noble (requires 3 white, 3 blue)
        player.claimNoble(standardNoble);
        
        assertEquals(1, player.getClaimedNobles().size());
        assertEquals(3, player.getPoints());  // Only noble points (cards were 0 points)
    }
    
    @Test
    @DisplayName("Player with mixed cards and nobles should calculate points correctly")
    void playerWithMixedContentShouldCalculatePointsCorrectly() {
        // Add cards with various points
        player.addCard(whiteCard);   // 0 points
        player.addCard(blueCard);    // 1 point
        player.addCard(greenCard);   // 2 points
        
        // Add nobles
        player.claimNoble(standardNoble);  // 3 points
        
        assertEquals(6, player.getPoints());  // 0 + 1 + 2 + 3 = 6
    }
    
    // ==================== Edge Case Tests ====================
    
    @Test
    @DisplayName("Should handle player with many cards")
    void shouldHandlePlayerWithManyCards() {
        // Add 20 cards
        for (int i = 0; i < 20; i++) {
            player.addCard(new Card(1, i % 3, GemColor.WHITE, standardCost));
        }
        
        assertEquals(20, player.getPurchasedCards().size());
        assertEquals(20, player.calculateBonuses().get(GemColor.WHITE));
    }
    
    @Test
    @DisplayName("Should handle player with max gems (10)")
    void shouldHandlePlayerWithMaxGems() {
        GemCollection gems = new GemCollection()
            .add(GemColor.WHITE, 3)
            .add(GemColor.BLUE, 3)
            .add(GemColor.GREEN, 2)
            .add(GemColor.RED, 1)
            .add(GemColor.BLACK, 1);
        
        player.addGems(gems);
        
        assertEquals(10, player.getGemCount());
    }
    
    @Test
    @DisplayName("Should handle player with no cards but with gems")
    void shouldHandlePlayerWithOnlyGems() {
        GemCollection gems = new GemCollection().add(GemColor.WHITE, 5);
        player.addGems(gems);
        
        assertEquals(0, player.getPurchasedCards().size());
        assertEquals(5, player.getGemCount());
        assertEquals(0, player.getPoints());
        assertEquals(0, player.calculateBonuses().getOrDefault(GemColor.WHITE, 0));
    }
    
    @Test
    @DisplayName("Should handle player with high points")
    void shouldHandlePlayerWithHighPoints() {
        // Add high-point cards
        player.addCard(new Card(3, 5, GemColor.WHITE, standardCost));
        player.addCard(new Card(3, 5, GemColor.BLUE, standardCost));
        player.addCard(new Card(3, 4, GemColor.GREEN, standardCost));
        
        // Add nobles
        player.claimNoble(standardNoble);
        player.claimNoble(new Noble(3, new EnumMap<>(GemColor.class)));
        
        // Total: 5 + 5 + 4 + 3 + 3 = 20 points
        assertEquals(20, player.getPoints());
    }
    
    // ==================== Player Comparison Tests ====================
    
    @Test
    @DisplayName("Different players should be independent")
    void differentPlayersShouldBeIndependent() {
        Player alice = new Player("Alice", 0);
        Player bob = new Player("Bob", 1);
        
        alice.addCard(whiteCard);
        alice.addGems(new GemCollection().add(GemColor.WHITE, 3));
        
        // Bob should be unaffected
        assertEquals(0, bob.getPurchasedCards().size());
        assertEquals(0, bob.getGemCount());
        assertEquals(0, bob.getPoints());
    }
    
    @Test
    @DisplayName("Players with same cards should have same bonuses but different identities")
    void playersWithSameCardsShouldHaveSameBonuses() {
        Player alice = new Player("Alice", 0);
        Player bob = new Player("Bob", 1);
        
        alice.addCard(whiteCard);
        alice.addCard(blueCard);
        
        bob.addCard(whiteCard);
        bob.addCard(blueCard);
        
        assertEquals(alice.getPoints(), bob.getPoints());
        assertEquals(alice.calculateBonuses().get(GemColor.WHITE), 
                    bob.calculateBonuses().get(GemColor.WHITE));
        
        // But different names and turn orders
        assertNotEquals(alice.getName(), bob.getName());
        assertNotEquals(alice.getTurnOrder(), bob.getTurnOrder());
    }
}