package edu.cs102.g04t06.game.presentation.console_old;

import java.nio.file.Files;
import java.nio.file.Path;

import edu.cs102.g04t06.App;
import edu.cs102.g04t06.game.presentation.console_old.template.BaseStack;
import edu.cs102.g04t06.game.presentation.console_old.template.StylingSheet;
import javafx.application.Platform;
import javafx.geometry.Pos;
import javafx.scene.Cursor;
import javafx.scene.Node;
import javafx.scene.control.Button;
import javafx.scene.control.CustomMenuItem;
import javafx.scene.control.Label;
import javafx.scene.control.MenuButton;
import javafx.scene.effect.DropShadow;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.Region;
import javafx.scene.layout.StackPane;
import javafx.scene.paint.Color;
import javafx.stage.PopupWindow;

/**
 * Onboarding view shown when the application starts.
 *
 * This view renders a full-screen background image and an action row
 * containing Mode selection plus a Start button.
 * 
 * Generated by Claude Sonnet 4.6 and GPT-5.2
 */
public class OnBoardingUI extends BaseStack<StackPane> implements StylingSheet{
    private static Path popupStylesheetPath;
    private boolean selectedModeValue;

    /**
     * Creates the onboarding UI and actually adds the required buttons onto the screen.
     *
     * @param application the main application for navigation callbacks
     */
    public OnBoardingUI(App application) {
        super(new StackPane(), application); // calls BaseStack constructor with StackPane and app instance
        setBaseBackground(ONBOARDING_BG_IMG_URL); // sets the background image
        this.selectedModeValue = false; // sets default mode to false, i.e. offline
        this.root.getChildren().add(createButtonGroup());
        /* 
        this.root: a variable inherited from BaseStack (parent class)
        it is a StackPane, i.e. basically an invisible container that holds everything on screen (blank canvas)
        getChildren(): in JavaFX, every container has a list of children, which are the things inside it ->
        getChildren() simply returns said list
        .add(): adds something to this list, making it appear on screen
        createButtonGroup(): this is our own method that builds and returns the GridPane containing our Mode 
        and Start buttons
        */
    }

    /**
     * Creates the bottom action row with mode selection and Start button.
     *
     * @return configured action container
     */
    private GridPane createButtonGroup() {
        /*
        GridPane is a table-like layout with rows and columns
        */
        GridPane gridPane = new GridPane();

        // here we simply add Mode button to column 0 and Start button to column 1
        gridPane.add(createModeOfPlayDropdown(), 0, 0);
        gridPane.add(createStartButton(), 1, 0);
        gridPane.setAlignment(Pos.CENTER);
        gridPane.setHgap(16); // this sets the space between the 2 buttons
        gridPane.setVgap(12);
        gridPane.setMaxSize(Region.USE_PREF_SIZE, Region.USE_PREF_SIZE);

        StackPane.setAlignment(gridPane, Pos.BOTTOM_CENTER); // this sets the grid near the bottom center of the screen
        gridPane.translateYProperty().bind(this.root.heightProperty().multiply(BUTTON_GROUP_BOTTOM_OFFSET_RATIO));
        // this essentially moves the grid upward relative to the current screen's height

        return gridPane;
    }

    /**
     * Creates the Start button, giving it hover and press effects.
     *
     * @return configured Start button
     */
    private Button createStartButton() {
        Button startBtn = new Button("Start");

        // just setting the preferred, min, and max heights of our Start button to one fixed height
        startBtn.setPrefHeight(BUTTON_HEIGHT);
        startBtn.setMinHeight(BUTTON_HEIGHT);
        startBtn.setMaxHeight(BUTTON_HEIGHT);

        startBtn.setStyle(luxuryButtonBaseStyle(START_BUTTON_WIDTH, BUTTON_HEIGHT)); 
        startBtn.setEffect(createGoldGlow());
        startBtn.setCursor(Cursor.HAND); // makes the mouse turn into a hand pointer when hovering
        startBtn.setFocusTraversable(false); // stops button from getting a focus ring when clicked

        // setOnMouseEntered fires when our cursor moves into the button, swapping the button to display 
        // a gold colour
        // setOnMouseExit does the opposite
        startBtn.setOnMouseEntered(e -> startBtn.setStyle(luxuryButtonHoverStyle(START_BUTTON_WIDTH, BUTTON_HEIGHT)));
        startBtn.setOnMouseExited(e -> startBtn.setStyle(luxuryButtonBaseStyle(START_BUTTON_WIDTH, BUTTON_HEIGHT)));

        // this is the click handler 
        // it tells the app to go to the next screen (lobby screen) when the Start button is clicked, whilst 
        // simultaneously passing along whether Online or Offline was clicked (Offline by default)
        startBtn.setOnAction(e -> this.application.showLobby(this.selectedModeValue));
        return startBtn; // this returns the finished button back to createButtonGroup(), which places it on screen
    }

    private MenuButton createModeOfPlayDropdown() {
        MenuButton menuButton = new MenuButton("  Mode");

        menuButton.setPrefWidth(MODE_BUTTON_WIDTH);
        menuButton.setPrefHeight(BUTTON_HEIGHT);
        menuButton.setMinHeight(BUTTON_HEIGHT);
        menuButton.setMaxHeight(BUTTON_HEIGHT);

        // helper method -> "false" means not hovering, so apply standard dark base style
        // "true" applies gold hover style
        applyModeButtonState(menuButton, false);
        menuButton.setEffect(createGoldGlow());
        menuButton.setCursor(Cursor.HAND);
        menuButton.setFocusTraversable(false);

        /*
        every JavaFX node has a sceneProperty(), which holds a reference to the Scene (screen)
        which the node currently belongs to (n.b. Properties are different from variables -> they are able to
        inform us when its value changes)
        addListener(): runs a block of code when a Property's value changes
        */
        menuButton.sceneProperty().addListener((obs, oldScene, newScene) -> {
            if (newScene != null) { // when scene stops being null (this button gets added to the screen,)
                Platform.runLater(() -> applyModeButtonLabelStyle(menuButton, false));
                // start styling the internal labels
            }
        });
        // showingProperty is a Property that tracks whether the dropdown is currently open or close, but instead
        // of holding a Scene it holds a boolean
        menuButton.showingProperty().addListener((obs, wasShowing, isShowing) -> {
            // if the dropdown is showing, style the popup window
            if (isShowing) {
                Platform.runLater(this::styleDropdownPopupWindows);
            }
        });

        // similar to hover instructions for Start button, just that now we need 2 method calls
        // 1 for the Menu button and 1 for the labels inside the Menu button
        menuButton.setOnMouseEntered(e -> {
            applyModeButtonState(menuButton, true);
            applyModeButtonLabelStyle(menuButton, true);
        });
        menuButton.setOnMouseExited(e -> {
            applyModeButtonState(menuButton, false);
            applyModeButtonLabelStyle(menuButton, false);
        });

        // get the list of options inside the dropdown, then addAll of these items at once to the Menu button
        menuButton.getItems().addAll(
            createModeMenuItem(menuButton, "Online", true, true, false), // Online maps to true
            createModeMenuItem(menuButton, "Offline", false, false, true) // Offline maps to false
            // last 2 booleans indicate whether the row should have rounded corners or not
        );
        return menuButton; // returns the fully built dropdown back to createButtonGroup(), which places it
        // on scree next to the Start button
    }

    // takes in the button and a boolean hovered -> true for hovering, false for not
    private void applyModeButtonState(MenuButton menuButton, boolean hovered) {
        String base = hovered // standard ternary -> if hovered apply gold hover style, if not apply base style
            ? luxuryButtonHoverStyle(MODE_BUTTON_WIDTH, BUTTON_HEIGHT)
            : luxuryButtonBaseStyle(MODE_BUTTON_WIDTH, BUTTON_HEIGHT);
        String markColor = hovered ? MARK_COLOR_HOVER : MARK_COLOR_BASE;
        menuButton.setStyle(base + "-fx-mark-color: " + markColor + ";" + "-fx-padding: 4 18 4 18;");
    }

    private void applyModeButtonLabelStyle(MenuButton menuButton, boolean hovered) {
        Node label = menuButton.lookup(".label"); // tries to find the internal label inside Mode
        if (label == null) {
            return; // if unable to find, i.e. it does not exist yet, then return
        }
        String color = hovered ? DARK_TEXT : GOLD_TEXT;
        label.setStyle("-fx-text-fill: " + color + "; -fx-font-family: 'Georgia'; -fx-font-weight: bold;");
    }

    private void styleDropdownPopupWindows() {
        // loop through every window currently open in the application (dropdown popups open as a separate
        // window)
        for (javafx.stage.Window window : javafx.stage.Window.getWindows()) {
            // check if current window is not a popup (since we only want to style popup windows)
            if (!(window instanceof PopupWindow popupWindow)) { 
                continue;
            }

            // clears both the window's background color and the root node's background inside the window
            // i.e. remove the default white rectangle around the dropdown
            window.getScene().setFill(javafx.scene.paint.Color.TRANSPARENT);
            popupWindow.getScene().getRoot().setStyle(TRANSPARENT_ROOT_STYLE);

            // this block of code basically uses a StyleSheet to set all the internal labels, instead of 
            // manually setting style on each internal label
            try {
                window.getScene().getStylesheets().add(ensurePopupStylesheet());
            } catch (Exception ex) {
                ex.printStackTrace();
            }

            // when the dropdown opens, look through every UI element inside it
            // if it is the menu button, style it using the default dark-gold style
            // if it is any internal menu part, remove its default styling            
            window.getScene().getRoot().lookupAll("*").forEach(node -> {
                String cls = node.getStyleClass().toString();
                if (cls.contains("context-menu")) {
                    node.setEffect(null);
                    if (!node.styleProperty().isBound()) {
                        node.setStyle(POPUP_MENU_STYLE);
                    }
                } else if (cls.contains("menu-item") || cls.contains("container") || cls.contains("graphic")) {
                    if (!node.styleProperty().isBound()) {
                        node.setStyle("-fx-background-color: transparent; -fx-padding: 0;");
                    }
                }
            });
        }
    }

    // this makes a temporary css file, puts our styling rules inside it, and gives
    // Java the location of it
    private String ensurePopupStylesheet() throws Exception {
        if (popupStylesheetPath == null) {
            popupStylesheetPath = Files.createTempFile("splendor-", ".css");
            Files.writeString(popupStylesheetPath, POPUP_STYLESHEET_CSS);
        }
        return popupStylesheetPath.toUri().toString();
    }

    /**
     * Creates a single dropdown item with an associated boolean value.
     *
     * @param menuButton the parent button whose label is updated on selection
     * @param optionName the text shown for this selectable option
     * @param optionValue the internal boolean value to store for this option
     * @return configured menu item with width binding and selection handler
     */
    private CustomMenuItem createModeMenuItem(
        MenuButton menuButton,
        String optionName,
        boolean optionValue,
        boolean isTopRounded,
        boolean isBottomRounded
    ) {
        Label optionLabel = new Label(optionName);
        optionLabel.setAlignment(Pos.CENTER_LEFT);
        optionLabel.setMaxWidth(Double.MAX_VALUE);
        optionLabel.prefWidthProperty().bind(menuButton.widthProperty().subtract(16));
        String rowRadius = isTopRounded
            ? "9px 9px 0px 0px"
            : (isBottomRounded ? "0px 0px 9px 9px" : "0px");
        String borderWidth = isBottomRounded ? "0" : "0 0 0.8px 0";
        optionLabel.setStyle(dropdownRowStyle(rowRadius, borderWidth, false));
        optionLabel.setOnMouseEntered(e -> optionLabel.setStyle(dropdownRowStyle(rowRadius, borderWidth, true)));
        optionLabel.setOnMouseExited(e -> optionLabel.setStyle(dropdownRowStyle(rowRadius, borderWidth, false)));

        optionLabel.setFocusTraversable(false);
        CustomMenuItem optionItem = new CustomMenuItem(optionLabel, true);
        optionItem.setHideOnClick(true);
        optionItem.setUserData(optionValue);

        // sets the menu button to show what option the user presses
        optionItem.setOnAction(e -> {
            menuButton.setText(optionName);
            this.selectedModeValue = (boolean) optionItem.getUserData(); // saves the selected option
        });
        return optionItem;
    }

    // styling helper methods
    private String dropdownRowStyle(String rowRadius, String borderWidth, boolean hovered) {
        String textColor = hovered ? DARK_TEXT : GOLD_TEXT;
        String bg = hovered
            ? "linear-gradient(to bottom, rgba(243, 210, 122, 0.98), rgba(173, 124, 35, 0.98))"
            : "linear-gradient(to bottom, rgba(36, 22, 12, 0.92), rgba(15, 9, 5, 0.92))";
        return
            "-fx-text-fill: " + textColor + ";" +
            "-fx-font-family: " + BUTTON_FONT_FAMILY + ";" +
            "-fx-font-size: 14px;" +
            "-fx-font-weight: bold;" +
            "-fx-padding: 8 18 8 18;" +
            "-fx-background-color: " + bg + ";" +
            "-fx-background-radius: " + rowRadius + ";" +
            "-fx-background-insets: 0;" +
            "-fx-border-color: rgba(242, 210, 122, 0.85);" +
            "-fx-border-width: " + borderWidth + ";" +
            "-fx-border-radius: " + rowRadius + ";";
    }

    private DropShadow createGoldGlow() {
        DropShadow glow = new DropShadow();
        glow.setColor(Color.web("#F2D27A", BUTTON_GLOW_OPACITY));
        glow.setRadius(BUTTON_GLOW_RADIUS);
        glow.setSpread(0.08);
        glow.setOffsetY(2);
        return glow;
    }

    private String luxuryButtonBaseStyle(double minWidth, double minHeight) {
        return
            "-fx-min-width: " + minWidth + "px;" +
            "-fx-min-height: " + minHeight + "px;" +
            "-fx-background-color: " +
                "linear-gradient(to bottom, rgba(36, 22, 12, 0.92), rgba(15, 9, 5, 0.92))," +
                "linear-gradient(to bottom, rgba(255, 255, 255, 0.08), rgba(255, 255, 255, 0.02));" +
            "-fx-background-insets: 0, 1;" +
            "-fx-background-radius: 10, 9;" +
            "-fx-border-color: rgba(242, 210, 122, 0.85);" +
            "-fx-border-width: 1.6px;" +
            "-fx-border-radius: 10px;" +
            "-fx-text-fill: #F5E6B3;" +
            "-fx-font-family: " + BUTTON_FONT_FAMILY + ";" +
            "-fx-font-size: 14px;" +
            "-fx-font-weight: bold;" +
            "-fx-letter-spacing: 0.5px;" +
            "-fx-padding: 8 18 8 18;";
    }

    private String luxuryButtonHoverStyle(double minWidth, double minHeight) {
        return
            "-fx-min-width: " + minWidth + "px;" +
            "-fx-min-height: " + minHeight + "px;" +
            "-fx-background-color: " +
                "linear-gradient(to bottom, rgba(243, 210, 122, 0.98), rgba(173, 124, 35, 0.98))," +
                "linear-gradient(to bottom, rgba(255, 255, 255, 0.18), rgba(255, 255, 255, 0.06));" +
            "-fx-background-insets: 0, 1;" +
            "-fx-background-radius: 10, 9;" +
            "-fx-border-color: rgba(255, 239, 190, 0.95);" +
            "-fx-border-width: 1.6px;" +
            "-fx-border-radius: 10px;" +
            "-fx-text-fill: #1a0a00;" +
            "-fx-font-family: " + BUTTON_FONT_FAMILY + ";" +
            "-fx-font-size: 14px;" +
            "-fx-font-weight: bold;" +
            "-fx-letter-spacing: 0.5px;" +
            "-fx-padding: 8 18 8 18;";
    }

    /**
     * Returns the currently selected mode value.
     *
     * @return selected mode value (true for online, false for offline)
     */
    public boolean getSelectedModeValue() {
        return this.selectedModeValue;
    }
}
