package edu.cs102.g04t06.game.exception;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

// Generated by GPT-5 (Codex)
/**
 * Unit tests for InvalidMoveException.
 *
 */


@DisplayName("InvalidMoveException Tests")
class InvalidMoveExceptionTest {

    @Test
    @DisplayName("Default constructor creates exception with null message and cause")
    void defaultConstructorCreatesNullMessageAndCause() {
        InvalidMoveException ex = new InvalidMoveException();

        assertNull(ex.getMessage());
        assertNull(ex.getCause());
    }

    @Test
    @DisplayName("Message constructor stores message")
    void messageConstructorStoresMessage() {
        InvalidMoveException ex = new InvalidMoveException("invalid move");

        assertEquals("invalid move", ex.getMessage());
        assertNull(ex.getCause());
    }

    @Test
    @DisplayName("Message and cause constructor stores both values")
    void messageAndCauseConstructorStoresBothValues() {
        Throwable cause = new IllegalArgumentException("root cause");
        InvalidMoveException ex = new InvalidMoveException("invalid move", cause);

        assertEquals("invalid move", ex.getMessage());
        assertSame(cause, ex.getCause());
    }

    @Test
    @DisplayName("Cause constructor stores cause")
    void causeConstructorStoresCause() {
        Throwable cause = new RuntimeException("root cause");
        InvalidMoveException ex = new InvalidMoveException(cause);

        assertSame(cause, ex.getCause());
    }

    @Test
    @DisplayName("Full constructor applies suppression and stack-trace options")
    void fullConstructorAppliesSuppressionAndStackTraceOptions() {
        Throwable cause = new RuntimeException("root cause");
        InvalidMoveException ex = new InvalidMoveException("invalid move", cause, false, false);

        ex.addSuppressed(new IllegalStateException("suppressed"));

        assertEquals(0, ex.getSuppressed().length);
        assertEquals(0, ex.getStackTrace().length);
    }
}
