package edu.cs102.g04t06.game.exception;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.EnumMap;
import java.util.Map;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import edu.cs102.g04t06.game.rules.entities.GemColor;
import edu.cs102.g04t06.game.rules.entities.Noble;

// Generated by GPT-5 (Codex)
/**
 * Unit tests for NobleNotAvailableException.
 *
 */

@DisplayName("NobleNotAvailableException Tests")
class NobleNotAvailableExceptionTest {

    private Noble sampleNoble() {
        Map<GemColor, Integer> requirements = new EnumMap<>(GemColor.class);
        requirements.put(GemColor.WHITE, 3);
        requirements.put(GemColor.BLUE, 3);
        return new Noble(3, requirements);
    }

    @Test
    @DisplayName("Exception extends InvalidMoveException")
    void exceptionExtendsInvalidMoveException() {
        NobleNotAvailableException ex = new NobleNotAvailableException();

        assertInstanceOf(InvalidMoveException.class, ex);
    }

    @Test
    @DisplayName("Default constructor uses default message")
    void defaultConstructorUsesDefaultMessage() {
        NobleNotAvailableException ex = new NobleNotAvailableException();

        assertEquals("Selected noble is not available in the current game state.", ex.getMessage());
    }

    @Test
    @DisplayName("Noble constructor includes noble context")
    void nobleConstructorIncludesNobleContext() {
        Noble noble = sampleNoble();

        NobleNotAvailableException ex = new NobleNotAvailableException(noble);

        assertTrue(ex.getMessage().contains(noble.toString()));
        assertTrue(ex.getMessage().contains("is not available in the current game state."));
    }

    @Test
    @DisplayName("Noble and cause constructor stores both message and cause")
    void nobleAndCauseConstructorStoresBothMessageAndCause() {
        Noble noble = sampleNoble();
        Throwable cause = new RuntimeException("root cause");

        NobleNotAvailableException ex = new NobleNotAvailableException(noble, cause);

        assertSame(cause, ex.getCause());
        assertTrue(ex.getMessage().contains("is not available in the current game state."));
    }

    @Test
    @DisplayName("Cause constructor stores cause")
    void causeConstructorStoresCause() {
        Throwable cause = new RuntimeException("root cause");

        NobleNotAvailableException ex = new NobleNotAvailableException(cause);

        assertSame(cause, ex.getCause());
    }
}
