package edu.cs102.g04t06.game.rules;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import edu.cs102.g04t06.game.exception.NobleNotAvailableException;
import edu.cs102.g04t06.game.rules.entities.Card;
import edu.cs102.g04t06.game.rules.entities.GemColor;
import edu.cs102.g04t06.game.rules.entities.Noble;
import edu.cs102.g04t06.game.rules.entities.Player;
import edu.cs102.g04t06.game.rules.valueobjects.CardMarket;
import edu.cs102.g04t06.game.rules.valueobjects.Cost;
import edu.cs102.g04t06.game.rules.valueobjects.GemCollection;

// Generated by GPT-5 (Codex)
/**
 * Unit tests for GameState.
 *
 */

@DisplayName("GameState Tests")
class GameStateTest {

    private Card makeCard(int level, int points, GemColor bonus) {
        return new Card(level, points, bonus, new Cost(new EnumMap<>(GemColor.class)));
    }

    private List<Card> makeDeck(int level) {
        List<Card> cards = new ArrayList<>();
        GemColor[] colors = GemColor.values();

        for (int i = 0; i < 20; i++) {
            cards.add(makeCard(level, i % 3, colors[i % colors.length]));
        }
        return cards;
    }

    private CardMarket makeMarket() {
        return new CardMarket(makeDeck(1), makeDeck(2), makeDeck(3));
    }

    private Noble makeNoble(int points, int whiteReq, int blueReq) {
        Map<GemColor, Integer> requirements = new EnumMap<>(GemColor.class);
        requirements.put(GemColor.WHITE, whiteReq);
        requirements.put(GemColor.BLUE, blueReq);
        return new Noble(points, "Test Noble", requirements);
    }

    private GameState makeGameState(List<Noble> nobles, GemCollection gemBank) {
        List<Player> players = List.of(new Player("Alice", 0), new Player("Bob", 1));
        return new GameState(players, makeMarket(), gemBank, nobles, 15);
    }

    @Test
    @DisplayName("advanceToNextPlayer should rotate turn order and wrap around")
    void advanceToNextPlayerShouldRotateAndWrap() {
        GameState state = makeGameState(new ArrayList<>(), new GemCollection());

        assertEquals(0, state.getCurrentPlayerIndex());
        assertEquals(1, state.getRoundNumber());

        state.advanceToNextPlayer();
        assertEquals(1, state.getCurrentPlayerIndex());
        assertEquals(1, state.getRoundNumber());

        state.advanceToNextPlayer();
        assertEquals(0, state.getCurrentPlayerIndex());
        assertEquals(2, state.getRoundNumber());
    }

    @Test
    @DisplayName("removeNoble should remove and return the matching noble")
    void removeNobleShouldRemoveAndReturnMatchingNoble() {
        Noble removable = makeNoble(3, 3, 3);
        Noble other = makeNoble(3, 4, 4);
        List<Noble> nobles = new ArrayList<>(List.of(removable, other));
        GameState state = makeGameState(nobles, new GemCollection());

        Noble removed = state.removeNoble(removable);

        assertSame(removable, removed);
        assertEquals(1, state.getAvailableNobles().size());
        assertEquals(other, state.getAvailableNobles().get(0));
    }

    @Test
    @DisplayName("removeNoble should throw when noble is not available")
    void removeNobleShouldThrowWhenNobleIsNotAvailable() {
        Noble available = makeNoble(3, 3, 3);
        Noble missing = makeNoble(4, 4, 4);
        GameState state = makeGameState(new ArrayList<>(List.of(available)), new GemCollection());

        assertThrows(NobleNotAvailableException.class, () -> state.removeNoble(missing));
    }

    @Test
    @DisplayName("addGemsToBank and removeGemsFromBank should update bank correctly")
    void gemBankMutationsShouldUpdateCountsCorrectly() {
        GemCollection startingBank = new GemCollection()
                .add(GemColor.WHITE, 4)
                .add(GemColor.BLUE, 2);
        GameState state = makeGameState(new ArrayList<>(), startingBank);

        GemCollection toAdd = new GemCollection().add(GemColor.WHITE, 1).add(GemColor.RED, 2);
        state.addGemsToBank(toAdd);
        assertEquals(5, state.getGemBank().getCount(GemColor.WHITE));
        assertEquals(2, state.getGemBank().getCount(GemColor.BLUE));
        assertEquals(2, state.getGemBank().getCount(GemColor.RED));

        GemCollection toRemove = new GemCollection().add(GemColor.WHITE, 3).add(GemColor.RED, 1);
        state.removeGemsFromBank(toRemove);
        assertEquals(2, state.getGemBank().getCount(GemColor.WHITE));
        assertEquals(2, state.getGemBank().getCount(GemColor.BLUE));
        assertEquals(1, state.getGemBank().getCount(GemColor.RED));
    }
}
