package edu.cs102.g04t06.game.rules;

import java.util.EnumMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import edu.cs102.g04t06.game.rules.entities.Card;
import edu.cs102.g04t06.game.rules.entities.GemColor;
import edu.cs102.g04t06.game.rules.entities.Noble;
import edu.cs102.g04t06.game.rules.entities.Player;
import edu.cs102.g04t06.game.rules.valueobjects.Cost;
import edu.cs102.g04t06.game.rules.valueobjects.GemCollection;


// Generated by Claude Sonnet 4.6
/**
 * 
 * Unit tests for GameRules.
 *
 */
public class GameRulesTest {

    private GameRules gameRules;

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /** Creates an empty Cost with no gem requirements */
    private Cost emptyCost() {
        return new Cost(new EnumMap<>(GemColor.class));
    }

    /** Creates a Cost with a single color requirement */
    private Cost costOf(GemColor color, int amount) {
        Map<GemColor, Integer> map = new EnumMap<>(GemColor.class);
        map.put(color, amount);
        return new Cost(map);
    }

    /** Creates a Cost with two color requirements */
    private Cost costOf(GemColor c1, int a1, GemColor c2, int a2) {
        Map<GemColor, Integer> map = new EnumMap<>(GemColor.class);
        map.put(c1, a1);
        map.put(c2, a2);
        return new Cost(map);
    }

    /** Creates a GemCollection with a single color */
    private GemCollection gemsOf(GemColor color, int amount) {
        Map<GemColor, Integer> map = new EnumMap<>(GemColor.class);
        map.put(color, amount);
        return new GemCollection(map);
    }

    /** Creates a GemCollection with two colors */
    private GemCollection gemsOf(GemColor c1, int a1, GemColor c2, int a2) {
        Map<GemColor, Integer> map = new EnumMap<>(GemColor.class);
        map.put(c1, a1);
        map.put(c2, a2);
        return new GemCollection(map);
    }

    private Noble nobleRequiring(int id, GemColor color, int amount) {
        Map<GemColor, Integer> reqs = new EnumMap<>(GemColor.class);
        reqs.put(color, amount);
        return new Noble(id, "Noble" + id, reqs);
    }

    private Noble nobleRequiring(int id, GemColor c1, int a1, GemColor c2, int a2) {
        Map<GemColor, Integer> reqs = new EnumMap<>(GemColor.class);
        reqs.put(c1, a1);
        reqs.put(c2, a2);
        return new Noble(id, "Noble" + id, reqs);
    }

    @BeforeEach
    void setUp() {
        gameRules = new GameRules();
    }

    // =========================================================================
    // canAffordCard() tests
    // =========================================================================

    @Test
    void testCanAffordCard_playerHasExactGems() {
        // Card costs 2 RED, 1 BLUE — player has exactly that
        Card card = new Card(1, 0, GemColor.WHITE, costOf(GemColor.RED, 2, GemColor.BLUE, 1));

        Player player = new Player("Alice", 1);
        player.addGems(gemsOf(GemColor.RED, 2, GemColor.BLUE, 1));

        assertTrue(gameRules.canAffordCard(player, card));
    }

    @Test
    void testCanAffordCard_playerHasBonusesCoveringCost() {
        // Card costs 2 RED — player has 0 gems but 2 RED bonus from purchased cards
        Card card = new Card(1, 0, GemColor.WHITE, costOf(GemColor.RED, 2));

        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));

        assertTrue(gameRules.canAffordCard(player, card));
    }

    @Test
    void testCanAffordCard_playerHasMixOfGemsAndBonuses() {
        // Card costs 3 RED — player has 1 RED bonus and 2 RED gems
        Card card = new Card(1, 0, GemColor.WHITE, costOf(GemColor.RED, 3));

        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost())); // 1 RED bonus
        player.addGems(gemsOf(GemColor.RED, 2));                   // 2 RED gems

        assertTrue(gameRules.canAffordCard(player, card));
    }

    @Test
    void testCanAffordCard_playerCannotAfford() {
        // Card costs 3 BLUE — player only has 1 BLUE gem, no bonuses
        Card card = new Card(1, 0, GemColor.WHITE, costOf(GemColor.BLUE, 3));

        Player player = new Player("Alice", 1);
        player.addGems(gemsOf(GemColor.BLUE, 1));

        assertFalse(gameRules.canAffordCard(player, card));
    }

    // =========================================================================
    // calculateActualCost() tests
    // =========================================================================

    @Test
    void testCalculateActualCost_noBonuses() {
        // Card costs 2 RED, 1 GREEN — player has no bonuses
        // Actual cost should remain 2 RED, 1 GREEN
        Card card = new Card(1, 0, GemColor.WHITE, costOf(GemColor.RED, 2, GemColor.GREEN, 1));

        Player player = new Player("Alice", 1);

        GemCollection actualCost = gameRules.calculateActualCost(player, card);

        assertEquals(2, actualCost.getCount(GemColor.RED));
        assertEquals(1, actualCost.getCount(GemColor.GREEN));
    }

    @Test
    void testCalculateActualCost_bonusesFullyCoverAColor() {
        // Card costs 2 RED — player has 2 RED bonuses
        // Actual RED cost should be 0
        Card card = new Card(1, 0, GemColor.WHITE, costOf(GemColor.RED, 2));

        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));

        GemCollection actualCost = gameRules.calculateActualCost(player, card);

        assertEquals(0, actualCost.getCount(GemColor.RED));
    }

    @Test
    void testCalculateActualCost_bonusesPartiallyCover() {
        // Card costs 3 BLUE — player has 1 BLUE bonus
        // Actual BLUE cost should be 2
        Card card = new Card(1, 0, GemColor.WHITE, costOf(GemColor.BLUE, 3));

        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 0, GemColor.BLUE, emptyCost()));

        GemCollection actualCost = gameRules.calculateActualCost(player, card);

        assertEquals(2, actualCost.getCount(GemColor.BLUE));
    }

    // =========================================================================
    // hasPlayerWon() tests
    // =========================================================================

    @Test
    void testHasPlayerWon_playerAtExactlyWinningPoints() {
        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 15, GemColor.RED, emptyCost()));

        assertTrue(gameRules.hasPlayerWon(player, 15));
    }

    @Test
    void testHasPlayerWon_playerAboveWinningPoints() {
        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 18, GemColor.RED, emptyCost()));

        assertTrue(gameRules.hasPlayerWon(player, 15));
    }

    @Test
    void testHasPlayerWon_playerBelowWinningPoints() {
        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 10, GemColor.RED, emptyCost()));

        assertFalse(gameRules.hasPlayerWon(player, 15));
    }

    // =========================================================================
    // getWinner() tests
    // =========================================================================

    @Test
    void testGetWinner_singleWinner() {
        Player alice = new Player("Alice", 1);
        Player bob   = new Player("Bob", 2);

        alice.addCard(new Card(1, 16, GemColor.RED,  emptyCost()));
        bob.addCard(new Card(1, 10,   GemColor.BLUE, emptyCost()));

        Player winner = gameRules.getWinner(List.of(alice, bob), 15);

        assertEquals(alice, winner);
    }

    @Test
    void testGetWinner_tieFewercardWins() {
        // Both players reach 15 points via nobles
        // Alice has 1 purchased card, Bob has 2 — Alice should win tiebreak
        Player alice = new Player("Alice", 1);
        Player bob   = new Player("Bob", 2);

        Map<GemColor, Integer> emptyReqs = new EnumMap<>(GemColor.class);
        alice.claimNoble(new Noble(1, "Noble1", emptyReqs));
        bob.claimNoble(new Noble(2, "Noble2", emptyReqs));

        // Give both 15 noble points via a card
        alice.addCard(new Card(1, 15, GemColor.RED,   emptyCost()));
        bob.addCard(new Card(1, 15,   GemColor.BLUE,  emptyCost()));
        bob.addCard(new Card(1, 0,    GemColor.GREEN, emptyCost())); // extra card for bob

        Player winner = gameRules.getWinner(List.of(alice, bob), 15);

        assertEquals(alice, winner);
    }

    @Test
    void testGetWinner_exactTieReturnsNull() {
        Player alice = new Player("Alice", 1);
        Player bob = new Player("Bob", 2);

        alice.addCard(new Card(1, 15, GemColor.RED, emptyCost()));
        bob.addCard(new Card(1, 15, GemColor.BLUE, emptyCost()));

        Player winner = gameRules.getWinner(List.of(alice, bob), 15);

        assertNull(winner);
    }

    @Test
    void testGetWinner_noWinnerYet() {
        Player alice = new Player("Alice", 1);
        Player bob   = new Player("Bob", 2);

        alice.addCard(new Card(1, 5, GemColor.RED,  emptyCost()));
        bob.addCard(new Card(1, 7,   GemColor.BLUE, emptyCost()));

        Player winner = gameRules.getWinner(List.of(alice, bob), 15);

        assertNull(winner);
    }

    // =========================================================================
    // Full Purchase Flow Integration Tests
    // =========================================================================

    @Test
    void testFullPurchaseFlow_gemsOnly() {
        // Setup: card costs 2 RED, 1 BLUE — player has exact gems
        Card card = new Card(1, 1, GemColor.RED, costOf(GemColor.RED, 2, GemColor.BLUE, 1));
        Player player = new Player("Alice", 1);
        player.addGems(gemsOf(GemColor.RED, 2, GemColor.BLUE, 1));

        // Step 1: check can afford
        assertTrue(gameRules.canAffordCard(player, card));

        // Step 2: calculate actual cost — no bonuses so cost unchanged
        GemCollection actualCost = gameRules.calculateActualCost(player, card);
        assertEquals(2, actualCost.getCount(GemColor.RED));
        assertEquals(1, actualCost.getCount(GemColor.BLUE));

        // Step 3: simulate purchase — deduct gems, add card
        player.deductGems(actualCost);
        player.addCard(card);

        // Step 4: verify player state after purchase
        assertEquals(0, player.getGems().getCount(GemColor.RED));
        assertEquals(0, player.getGems().getCount(GemColor.BLUE));
        assertEquals(1, player.getPurchasedCards().size());
        assertEquals(1, player.getPoints());
    }

    @Test
    void testFullPurchaseFlow_withBonusesReducingCost() {
        // Card costs 3 RED — player has 2 RED bonuses, needs only 1 RED gem
        Card card = new Card(1, 2, GemColor.RED, costOf(GemColor.RED, 3));
        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost())); // bonus 1
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost())); // bonus 2
        player.addGems(gemsOf(GemColor.RED, 1));

        // Step 1: check can afford
        assertTrue(gameRules.canAffordCard(player, card));

        // Step 2: calculate actual cost — 3 RED - 2 bonus = 1 RED
        GemCollection actualCost = gameRules.calculateActualCost(player, card);
        assertEquals(1, actualCost.getCount(GemColor.RED));

        // Step 3: simulate purchase
        player.deductGems(actualCost);
        player.addCard(card);

        // Step 4: verify gems fully spent, card added
        assertEquals(0, player.getGems().getCount(GemColor.RED));
        assertEquals(3, player.getPurchasedCards().size()); // 2 bonus cards + new card
        assertEquals(2, player.getPoints());
    }

    @Test
    void testFullPurchaseFlow_nobleClaimed() {
        // Player purchases cards to meet noble requirements, then noble is claimable
        Noble noble = nobleRequiring(1, GemColor.RED, 3);
        List<Noble> availableNobles = List.of(noble);

        Player player = new Player("Alice", 1);

        // Before purchase: noble not claimable
        List<Noble> claimableBefore = gameRules.getClaimableNobles(player, availableNobles);
        assertTrue(claimableBefore.isEmpty());

        // Purchase 3 RED bonus cards
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));

        // After purchase: noble now claimable
        List<Noble> claimableAfter = gameRules.getClaimableNobles(player, availableNobles);
        assertEquals(1, claimableAfter.size());
        assertEquals(noble, claimableAfter.get(0));
    }

    @Test
    void testFullPurchaseFlow_purchaseTriggersWin() {
        // Player is at 14 points, purchases a 1-point card to reach 15 and win
        Card winningCard = new Card(1, 1, GemColor.RED, costOf(GemColor.BLUE, 1));
        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 14, GemColor.RED, emptyCost())); // 14 points already
        player.addGems(gemsOf(GemColor.BLUE, 1));

        // Before purchase: not won yet
        assertFalse(gameRules.hasPlayerWon(player, 15));

        // Purchase the card
        GemCollection actualCost = gameRules.calculateActualCost(player, winningCard);
        player.deductGems(actualCost);
        player.addCard(winningCard);

        // After purchase: player has won
        assertTrue(gameRules.hasPlayerWon(player, 15));
        assertEquals(player, gameRules.getWinner(List.of(player), 15));
    }

    // =========================================================================
    // canTakeThreeDifferentGems edge cases
    // =========================================================================

    @Test
    void testCanTakeThreeDifferentGems_valid() {
        Map<GemColor, Integer> reqMap = new EnumMap<>(GemColor.class);
        reqMap.put(GemColor.RED, 1);
        reqMap.put(GemColor.BLUE, 1);
        reqMap.put(GemColor.GREEN, 1);
        GemCollection requested = new GemCollection(reqMap);

        Map<GemColor, Integer> bankMap = new EnumMap<>(GemColor.class);
        bankMap.put(GemColor.RED, 4);
        bankMap.put(GemColor.BLUE, 4);
        bankMap.put(GemColor.GREEN, 4);
        GemCollection bank = new GemCollection(bankMap);

        assertTrue(gameRules.canTakeThreeDifferentGems(requested, bank));
    }

    @Test
    void testCanTakeThreeDifferentGems_bankHasOnlyOneOfAColor() {
        // Bank has only 1 GREEN — still valid since we only need 1
        Map<GemColor, Integer> reqMap = new EnumMap<>(GemColor.class);
        reqMap.put(GemColor.RED, 1);
        reqMap.put(GemColor.BLUE, 1);
        reqMap.put(GemColor.GREEN, 1);
        GemCollection requested = new GemCollection(reqMap);

        Map<GemColor, Integer> bankMap = new EnumMap<>(GemColor.class);
        bankMap.put(GemColor.RED, 4);
        bankMap.put(GemColor.BLUE, 4);
        bankMap.put(GemColor.GREEN, 1);
        GemCollection bank = new GemCollection(bankMap);

        assertTrue(gameRules.canTakeThreeDifferentGems(requested, bank));
    }

    @Test
    void testCanTakeThreeDifferentGems_bankEmptyForOneColor() {
        // Bank has 0 GREEN — invalid
        Map<GemColor, Integer> reqMap = new EnumMap<>(GemColor.class);
        reqMap.put(GemColor.RED, 1);
        reqMap.put(GemColor.BLUE, 1);
        reqMap.put(GemColor.GREEN, 1);
        GemCollection requested = new GemCollection(reqMap);

        Map<GemColor, Integer> bankMap = new EnumMap<>(GemColor.class);
        bankMap.put(GemColor.RED, 4);
        bankMap.put(GemColor.BLUE, 4);
        bankMap.put(GemColor.GREEN, 0);
        GemCollection bank = new GemCollection(bankMap);

        assertFalse(gameRules.canTakeThreeDifferentGems(requested, bank));
    }

    @Test
    void testCanTakeThreeDifferentGems_requestedTwoOfSameColor() {
        // Requesting 2 RED instead of 1 each — invalid for three different
        Map<GemColor, Integer> reqMap = new EnumMap<>(GemColor.class);
        reqMap.put(GemColor.RED, 2);
        reqMap.put(GemColor.BLUE, 1);
        GemCollection requested = new GemCollection(reqMap);

        Map<GemColor, Integer> bankMap = new EnumMap<>(GemColor.class);
        bankMap.put(GemColor.RED, 4);
        bankMap.put(GemColor.BLUE, 4);
        GemCollection bank = new GemCollection(bankMap);

        assertFalse(gameRules.canTakeThreeDifferentGems(requested, bank));
    }

    // =========================================================================
    // canTakeTwoSameGems edge cases
    // =========================================================================

    @Test
    void testCanTakeTwoSameGems_exactlyFourInBank() {
        // Exactly 4 RED in bank — valid
        Map<GemColor, Integer> bankMap = new EnumMap<>(GemColor.class);
        bankMap.put(GemColor.RED, 4);
        GemCollection bank = new GemCollection(bankMap);

        assertTrue(gameRules.canTakeTwoSameGems(GemColor.RED, bank));
    }

    @Test
    void testCanTakeTwoSameGems_onlyThreeInBank() {
        // Only 3 RED — invalid
        Map<GemColor, Integer> bankMap = new EnumMap<>(GemColor.class);
        bankMap.put(GemColor.RED, 3);
        GemCollection bank = new GemCollection(bankMap);

        assertFalse(gameRules.canTakeTwoSameGems(GemColor.RED, bank));
    }

    @Test
    void testCanTakeTwoSameGems_zeroInBank() {
        // 0 RED in bank — invalid
        Map<GemColor, Integer> bankMap = new EnumMap<>(GemColor.class);
        bankMap.put(GemColor.RED, 0);
        GemCollection bank = new GemCollection(bankMap);

        assertFalse(gameRules.canTakeTwoSameGems(GemColor.RED, bank));
    }

    // =========================================================================
    // mustReturnGems edge cases
    // =========================================================================

    @Test
    void testMustReturnGems_exactlyTen() {
        // Exactly 10 gems — no need to return
        Player player = new Player("Alice", 1);
        Map<GemColor, Integer> gemMap = new EnumMap<>(GemColor.class);
        gemMap.put(GemColor.RED,   4);
        gemMap.put(GemColor.BLUE,  3);
        gemMap.put(GemColor.GREEN, 3);
        player.addGems(new GemCollection(gemMap));

        assertFalse(gameRules.mustReturnGems(player));
    }

    @Test
    void testMustReturnGems_elevenGems() {
        // 11 gems — must return
        Player player = new Player("Alice", 1);
        Map<GemColor, Integer> gemMap = new EnumMap<>(GemColor.class);
        gemMap.put(GemColor.RED,   4);
        gemMap.put(GemColor.BLUE,  4);
        gemMap.put(GemColor.GREEN, 3);
        player.addGems(new GemCollection(gemMap));

        assertTrue(gameRules.mustReturnGems(player));
    }

    @Test
    void testMustReturnGems_zeroGems() {
        // 0 gems — no need to return
        Player player = new Player("Alice", 1);
        assertFalse(gameRules.mustReturnGems(player));
    }

    // =========================================================================
    // canReserveCard edge cases
    // =========================================================================

    @Test
    void testCanReserveCard_noReservedCards() {
        Player player = new Player("Alice", 1);
        assertTrue(gameRules.canReserveCard(player));
    }

    @Test
    void testCanReserveCard_twoReservedCards() {
        Player player = new Player("Alice", 1);
        player.addReservedCard(new Card(1, 0, GemColor.RED, emptyCost()));
        player.addReservedCard(new Card(1, 0, GemColor.BLUE, emptyCost()));

        assertTrue(gameRules.canReserveCard(player));
    }

    @Test
    void testCanReserveCard_atMaxThreeReservedCards() {
        Player player = new Player("Alice", 1);
        player.addReservedCard(new Card(1, 0, GemColor.RED,   emptyCost()));
        player.addReservedCard(new Card(1, 0, GemColor.BLUE,  emptyCost()));
        player.addReservedCard(new Card(1, 0, GemColor.GREEN, emptyCost()));

        assertFalse(gameRules.canReserveCard(player));
    }

    // =========================================================================
    // getClaimableNobles edge cases
    // =========================================================================

    @Test
    void testGetClaimableNobles_noNoblesAvailable() {
        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));

        List<Noble> claimable = gameRules.getClaimableNobles(player, List.of());
        assertTrue(claimable.isEmpty());
    }

    @Test
    void testGetClaimableNobles_playerMeetsNone() {
        Noble noble = nobleRequiring(1, GemColor.RED, 4);
        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost())); // only 1 RED bonus

        List<Noble> claimable = gameRules.getClaimableNobles(player, List.of(noble));
        assertTrue(claimable.isEmpty());
    }

    @Test
    void testGetClaimableNobles_playerMeetsMultiple() {
        Noble noble1 = nobleRequiring(1, GemColor.RED, 3);
        Noble noble2 = nobleRequiring(2, GemColor.BLUE, 3);

        Player player = new Player("Alice", 1);
        // Give player 3 RED and 3 BLUE bonuses
        player.addCard(new Card(1, 0, GemColor.RED,  emptyCost()));
        player.addCard(new Card(1, 0, GemColor.RED,  emptyCost()));
        player.addCard(new Card(1, 0, GemColor.RED,  emptyCost()));
        player.addCard(new Card(1, 0, GemColor.BLUE, emptyCost()));
        player.addCard(new Card(1, 0, GemColor.BLUE, emptyCost()));
        player.addCard(new Card(1, 0, GemColor.BLUE, emptyCost()));

        List<Noble> claimable = gameRules.getClaimableNobles(player, List.of(noble1, noble2));
        assertEquals(2, claimable.size());
    }

    @Test
    void testGetClaimableNobles_playerMeetsOneOfTwo() {
        Noble noble1 = nobleRequiring(1, GemColor.RED,  3);
        Noble noble2 = nobleRequiring(2, GemColor.BLUE, 3);

        Player player = new Player("Alice", 1);
        // Only 3 RED bonuses — meets noble1 but not noble2
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));

        List<Noble> claimable = gameRules.getClaimableNobles(player, List.of(noble1, noble2));
        assertEquals(1, claimable.size());
        assertEquals(noble1, claimable.get(0));
    }

    // =========================================================================
    // getWinner edge cases
    // =========================================================================

    @Test
    void testGetWinner_multiplePlayersAboveThreshold_highestPointsWins() {
        Player alice = new Player("Alice", 1);
        Player bob   = new Player("Bob",   2);
        Player carol = new Player("Carol", 3);

        alice.addCard(new Card(1, 16, GemColor.RED,   emptyCost()));
        bob.addCard(new Card(1,   18, GemColor.BLUE,  emptyCost()));
        carol.addCard(new Card(1, 10, GemColor.GREEN, emptyCost())); // below threshold

        Player winner = gameRules.getWinner(List.of(alice, bob, carol), 15);
        assertEquals(bob, winner);
    }

    @Test
    void testGetWinner_emptyPlayerList() {
        Player winner = gameRules.getWinner(List.of(), 15);
        assertNull(winner);
    }

    @Test
    void testGetWinner_singlePlayerBelowThreshold() {
        Player alice = new Player("Alice", 1);
        alice.addCard(new Card(1, 5, GemColor.RED, emptyCost()));

        Player winner = gameRules.getWinner(List.of(alice), 15);
        assertNull(winner);
    }

    // =========================================================================
    // canAffordCard() - additional edge cases
    // =========================================================================

    @Test
    void testCanAffordCard_zeroCostCard() {
        // Card with no cost — player with no gems can afford it
        Card card = new Card(1, 1, GemColor.RED, emptyCost());
        Player player = new Player("Alice", 1);

        assertTrue(gameRules.canAffordCard(player, card));
    }

    @Test
    void testCanAffordCard_goldCoversShortfall() {
        // Card costs 3 RED — player has 2 RED gems and 1 GOLD (wildcard)
        Card card = new Card(1, 1, GemColor.RED, costOf(GemColor.RED, 3));
        Player player = new Player("Alice", 1);
        player.addGems(gemsOf(GemColor.RED, 2));
        player.addGems(gemsOf(GemColor.GOLD, 1));

        assertTrue(gameRules.canAffordCard(player, card));
    }

    @Test
    void testCanAffordCard_bonusesAndGoldTogetherCoverCost() {
        // Card costs 4 RED — player has 1 RED bonus, 2 RED gems, 1 GOLD
        Card card = new Card(1, 1, GemColor.RED, costOf(GemColor.RED, 4));
        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost())); // 1 RED bonus
        player.addGems(gemsOf(GemColor.RED, 2));
        player.addGems(gemsOf(GemColor.GOLD, 1));

        assertTrue(gameRules.canAffordCard(player, card));
    }

    @Test
    void testCanAffordCard_bonusesExceedCost_notNegative() {
        // Card costs 1 RED — player has 3 RED bonuses, cost should floor at 0
        Card card = new Card(1, 1, GemColor.RED, costOf(GemColor.RED, 1));
        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));

        assertTrue(gameRules.canAffordCard(player, card));
    }

    @Test
    void testCanAffordCard_multiColorCost_missingOneColor() {
        // Card costs 2 RED, 2 BLUE — player has 2 RED but 0 BLUE
        Card card = new Card(1, 1, GemColor.RED, costOf(GemColor.RED, 2, GemColor.BLUE, 2));
        Player player = new Player("Alice", 1);
        player.addGems(gemsOf(GemColor.RED, 2));

        assertFalse(gameRules.canAffordCard(player, card));
    }

    @Test
    void testCanAffordCard_playerHasMoreGemsThanNeeded() {
        // Card costs 1 RED — player has 4 RED gems, should still afford it
        Card card = new Card(1, 1, GemColor.RED, costOf(GemColor.RED, 1));
        Player player = new Player("Alice", 1);
        player.addGems(gemsOf(GemColor.RED, 4));

        assertTrue(gameRules.canAffordCard(player, card));
    }

    // =========================================================================
    // calculateActualCost() - additional edge cases
    // =========================================================================

    @Test
    void testCalculateActualCost_bonusesExceedCost_floorAtZero() {
        // Card costs 1 RED — player has 3 RED bonuses, actual cost should be 0 not negative
        Card card = new Card(1, 1, GemColor.RED, costOf(GemColor.RED, 1));
        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));

        GemCollection actualCost = gameRules.calculateActualCost(player, card);

        assertEquals(0, actualCost.getCount(GemColor.RED));
    }

    @Test
    void testCalculateActualCost_multiColorCost_bonusesPartiallyReduceEach() {
        // Card costs 3 RED, 3 BLUE — player has 1 RED bonus, 2 BLUE bonuses
        // Expected: 2 RED, 1 BLUE remaining
        Map<GemColor, Integer> costMap = new EnumMap<>(GemColor.class);
        costMap.put(GemColor.RED, 3);
        costMap.put(GemColor.BLUE, 3);
        Card card = new Card(1, 1, GemColor.RED, new Cost(costMap));

        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 0, GemColor.RED,  emptyCost())); // 1 RED bonus
        player.addCard(new Card(1, 0, GemColor.BLUE, emptyCost())); // 1 BLUE bonus
        player.addCard(new Card(1, 0, GemColor.BLUE, emptyCost())); // 2 BLUE bonus

        GemCollection actualCost = gameRules.calculateActualCost(player, card);

        assertEquals(2, actualCost.getCount(GemColor.RED));
        assertEquals(1, actualCost.getCount(GemColor.BLUE));
    }

    @Test
    void testCalculateActualCost_zeroCostCard_remainsZero() {
        // Card with no cost — actual cost should still be 0 for all colors
        Card card = new Card(1, 1, GemColor.RED, emptyCost());
        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));

        GemCollection actualCost = gameRules.calculateActualCost(player, card);

        assertEquals(0, actualCost.getCount(GemColor.RED));
        assertEquals(0, actualCost.getCount(GemColor.BLUE));
    }

    @Test
    void testCalculateActualCost_bonusColorNotInCost_ignored() {
        // Card costs 2 BLUE — player has RED bonuses (irrelevant)
        // BLUE cost should be unchanged
        Card card = new Card(1, 1, GemColor.BLUE, costOf(GemColor.BLUE, 2));
        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost())); // RED bonus, irrelevant

        GemCollection actualCost = gameRules.calculateActualCost(player, card);

        assertEquals(2, actualCost.getCount(GemColor.BLUE));
        assertEquals(0, actualCost.getCount(GemColor.RED));
    }

    // =========================================================================
    // canTakeThreeDifferentGems() - additional edge cases
    // =========================================================================

    @Test
    void testCanTakeThreeDifferentGems_requestingGold_invalid() {
        // GOLD (wildcard) cannot be taken as a regular gem
        Map<GemColor, Integer> reqMap = new EnumMap<>(GemColor.class);
        reqMap.put(GemColor.RED,  1);
        reqMap.put(GemColor.BLUE, 1);
        reqMap.put(GemColor.GOLD, 1); // invalid
        GemCollection requested = new GemCollection(reqMap);

        Map<GemColor, Integer> bankMap = new EnumMap<>(GemColor.class);
        bankMap.put(GemColor.RED,  4);
        bankMap.put(GemColor.BLUE, 4);
        bankMap.put(GemColor.GOLD, 4);
        GemCollection bank = new GemCollection(bankMap);

        assertFalse(gameRules.canTakeThreeDifferentGems(requested, bank));
    }

    @Test
    void testCanTakeThreeDifferentGems_requestingFewerThanThree() {
        // Only 2 gems requested — invalid
        Map<GemColor, Integer> reqMap = new EnumMap<>(GemColor.class);
        reqMap.put(GemColor.RED,  1);
        reqMap.put(GemColor.BLUE, 1);
        GemCollection requested = new GemCollection(reqMap);

        Map<GemColor, Integer> bankMap = new EnumMap<>(GemColor.class);
        bankMap.put(GemColor.RED,  4);
        bankMap.put(GemColor.BLUE, 4);
        GemCollection bank = new GemCollection(bankMap);

        assertFalse(gameRules.canTakeThreeDifferentGems(requested, bank));
    }

    @Test
    void testCanTakeThreeDifferentGems_requestingMoreThanThree() {
        // 4 gems requested — invalid
        Map<GemColor, Integer> reqMap = new EnumMap<>(GemColor.class);
        reqMap.put(GemColor.RED,   1);
        reqMap.put(GemColor.BLUE,  1);
        reqMap.put(GemColor.GREEN, 1);
        reqMap.put(GemColor.WHITE, 1);
        GemCollection requested = new GemCollection(reqMap);

        Map<GemColor, Integer> bankMap = new EnumMap<>(GemColor.class);
        bankMap.put(GemColor.RED,   4);
        bankMap.put(GemColor.BLUE,  4);
        bankMap.put(GemColor.GREEN, 4);
        bankMap.put(GemColor.WHITE, 4);
        GemCollection bank = new GemCollection(bankMap);

        assertFalse(gameRules.canTakeThreeDifferentGems(requested, bank));
    }

    // =========================================================================
    // canTakeTwoSameGems() - additional edge cases
    // =========================================================================

    @Test
    void testCanTakeTwoSameGems_moreThanFourInBank() {
        // 7 RED in bank — valid
        Map<GemColor, Integer> bankMap = new EnumMap<>(GemColor.class);
        bankMap.put(GemColor.RED, 7);
        GemCollection bank = new GemCollection(bankMap);

        assertTrue(gameRules.canTakeTwoSameGems(GemColor.RED, bank));
    }

    @Test
    void testCanTakeTwoSameGems_requestingGold_invalid() {
        // Cannot take 2 GOLD (wildcard)
        Map<GemColor, Integer> bankMap = new EnumMap<>(GemColor.class);
        bankMap.put(GemColor.GOLD, 5);
        GemCollection bank = new GemCollection(bankMap);

        assertFalse(gameRules.canTakeTwoSameGems(GemColor.GOLD, bank));
    }

    // =========================================================================
    // mustReturnGems() - additional edge cases
    // =========================================================================

    @Test
    void testMustReturnGems_nineGems() {
        // 9 gems — no need to return
        Player player = new Player("Alice", 1);
        Map<GemColor, Integer> gemMap = new EnumMap<>(GemColor.class);
        gemMap.put(GemColor.RED,   4);
        gemMap.put(GemColor.BLUE,  3);
        gemMap.put(GemColor.GREEN, 2);
        player.addGems(new GemCollection(gemMap));

        assertFalse(gameRules.mustReturnGems(player));
    }

    @Test
    void testMustReturnGems_includesGold() {
        // 8 regular gems + 3 GOLD = 11 total — must return
        Player player = new Player("Alice", 1);
        Map<GemColor, Integer> gemMap = new EnumMap<>(GemColor.class);
        gemMap.put(GemColor.RED,   4);
        gemMap.put(GemColor.BLUE,  4);
        gemMap.put(GemColor.GOLD,  3);
        player.addGems(new GemCollection(gemMap));

        assertTrue(gameRules.mustReturnGems(player));
    }

    // =========================================================================
    // canReserveCard() - additional edge cases
    // =========================================================================

    @Test
    void testCanReserveCard_oneReservedCard() {
        Player player = new Player("Alice", 1);
        player.addReservedCard(new Card(1, 0, GemColor.RED, emptyCost()));

        assertTrue(gameRules.canReserveCard(player));
    }

    // =========================================================================
    // hasPlayerWon() - additional edge cases
    // =========================================================================

    @Test
    void testHasPlayerWon_pointsFromNoblesOnly() {
        // Points come only from nobles, not cards
        Player player = new Player("Alice", 1);
        Map<GemColor, Integer> emptyReqs = new EnumMap<>(GemColor.class);
        player.claimNoble(new Noble(1, "Noble1", emptyReqs));
        player.claimNoble(new Noble(2, "Noble2", emptyReqs));
        // Assuming each noble gives enough points to reach threshold
        // Adjust noble points to match your Noble constructor
        assertTrue(gameRules.hasPlayerWon(player, player.getPoints()));
    }

    @Test
    void testHasPlayerWon_pointsFromCardsAndNobles() {
        // 10 points from card + 5 from noble = 15
        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 10, GemColor.RED, emptyCost()));
        Map<GemColor, Integer> emptyReqs = new EnumMap<>(GemColor.class);
        player.claimNoble(new Noble(1, "Noble1", emptyReqs));
        // Noble gives 5 points — adjust if your noble points differ
        assertTrue(gameRules.hasPlayerWon(player, player.getPoints()));
    }

    @Test
    void testHasPlayerWon_zeroPoints() {
        Player player = new Player("Alice", 1);
        assertFalse(gameRules.hasPlayerWon(player, 15));
    }

    // =========================================================================
    // getWinner() - additional edge cases
    // =========================================================================

    @Test
    void testGetWinner_allPlayersAboveThreshold_highestWins() {
        Player alice = new Player("Alice", 1);
        Player bob   = new Player("Bob",   2);
        Player carol = new Player("Carol", 3);

        alice.addCard(new Card(1, 15, GemColor.RED,   emptyCost()));
        bob.addCard(new Card(1,   17, GemColor.BLUE,  emptyCost()));
        carol.addCard(new Card(1, 16, GemColor.GREEN, emptyCost()));

        Player winner = gameRules.getWinner(List.of(alice, bob, carol), 15);
        assertEquals(bob, winner);
    }

    @Test
    void testGetWinner_tieOnPointsAndCards_returnsNull() {
        Player alice = new Player("Alice", 1);
        Player bob   = new Player("Bob",   2);

        alice.addCard(new Card(1, 15, GemColor.RED,  emptyCost()));
        bob.addCard(new Card(1,   15, GemColor.BLUE, emptyCost()));

        Player winner = gameRules.getWinner(List.of(alice, bob), 15);
        assertNull(winner);
    }

    @Test
    void testGetWinner_onlyOnePlayerTotal_wins() {
        Player alice = new Player("Alice", 1);
        alice.addCard(new Card(1, 15, GemColor.RED, emptyCost()));

        Player winner = gameRules.getWinner(List.of(alice), 15);
        assertEquals(alice, winner);
    }

    @Test
    void testGetWinner_onlyOnePlayerTotal_doesNotWin() {
        Player alice = new Player("Alice", 1);
        alice.addCard(new Card(1, 5, GemColor.RED, emptyCost()));

        Player winner = gameRules.getWinner(List.of(alice), 15);
        assertNull(winner);
    }

    // =========================================================================
    // getClaimableNobles() - additional edge cases
    // =========================================================================

    @Test
    void testGetClaimableNobles_nobleRequiresMultipleColors_playerMeetsAll() {
        // Noble requires 2 RED and 2 BLUE — player has both
        Noble noble = nobleRequiring(1, GemColor.RED, 2, GemColor.BLUE, 2);
        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 0, GemColor.RED,  emptyCost()));
        player.addCard(new Card(1, 0, GemColor.RED,  emptyCost()));
        player.addCard(new Card(1, 0, GemColor.BLUE, emptyCost()));
        player.addCard(new Card(1, 0, GemColor.BLUE, emptyCost()));

        List<Noble> claimable = gameRules.getClaimableNobles(player, List.of(noble));
        assertEquals(1, claimable.size());
    }

    @Test
    void testGetClaimableNobles_nobleRequiresMultipleColors_playerMissingOne() {
        // Noble requires 2 RED and 2 BLUE — player only has RED
        Noble noble = nobleRequiring(1, GemColor.RED, 2, GemColor.BLUE, 2);
        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));

        List<Noble> claimable = gameRules.getClaimableNobles(player, List.of(noble));
        assertTrue(claimable.isEmpty());
    }

    @Test
    void testGetClaimableNobles_playerExceedsRequirements() {
        // Noble requires 2 RED — player has 4 RED bonuses (more than enough)
        Noble noble = nobleRequiring(1, GemColor.RED, 2);
        Player player = new Player("Alice", 1);
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));
        player.addCard(new Card(1, 0, GemColor.RED, emptyCost()));

        List<Noble> claimable = gameRules.getClaimableNobles(player, List.of(noble));
        assertEquals(1, claimable.size());
    }

    @Test
    void testGetClaimableNobles_playerHasGemsButNotBonuses_notClaimable() {
        // Noble requires 2 RED bonuses — gems don't count, only purchased card bonuses
        Noble noble = nobleRequiring(1, GemColor.RED, 2);
        Player player = new Player("Alice", 1);
        player.addGems(gemsOf(GemColor.RED, 4)); // gems, not bonuses

        List<Noble> claimable = gameRules.getClaimableNobles(player, List.of(noble));
        assertTrue(claimable.isEmpty());
    }
}
