package edu.cs102.g04t06.game;

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.stream.Stream;

import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;

// Generated by GPT-5 (Codex)
/**
 * Unit tests for placeholder game modules.
 *
 */
class GamePlaceholderModulesTest {

    @TestFactory
    Stream<DynamicTest> placeholderModulesHaveCorrectPackageDeclaration() {
        Map<String, String> expectedPackages = new LinkedHashMap<>();
        expectedPackages.put(
            "src/main/java/edu/cs102/g04t06/game/presentation/console/ConsoleUI.java",
            "package edu.cs102.g04t06.game.presentation.console;"
        );
        expectedPackages.put(
            "src/main/java/edu/cs102/g04t06/game/presentation/console/InputHandler.java",
            "package edu.cs102.g04t06.game.presentation.console;"
        );
        expectedPackages.put(
            "src/main/java/edu/cs102/g04t06/game/presentation/console/GameRenderer.java",
            "package edu.cs102.g04t06.game.presentation.console;"
        );
        expectedPackages.put(
            "src/main/java/edu/cs102/g04t06/game/infrastructure/data/ExcelDataLoader.java",
            "package edu.cs102.g04t06.game.infrastructure.data;"
        );
        expectedPackages.put(
            "src/main/java/edu/cs102/g04t06/game/rules/GameState.java",
            "package edu.cs102.g04t06.game.rules;"
        );
        expectedPackages.put(
            "src/main/java/edu/cs102/g04t06/game/rules/GameRules.java",
            "package edu.cs102.g04t06.game.rules;"
        );
        expectedPackages.put(
            "src/main/java/edu/cs102/g04t06/game/execution/ai/AIPlayer.java",
            "package edu.cs102.g04t06.game.execution.ai;"
        );
        expectedPackages.put(
            "src/main/java/edu/cs102/g04t06/game/execution/GameEngine.java",
            "package edu.cs102.g04t06.game.execution;"
        );
        expectedPackages.put(
            "src/main/java/edu/cs102/g04t06/game/execution/ActionResult.java",
            "package edu.cs102.g04t06.game.execution;"
        );
        expectedPackages.put(
            "src/main/java/edu/cs102/g04t06/game/execution/ActionExecutor.java",
            "package edu.cs102.g04t06.game.execution;"
        );

        return expectedPackages.entrySet().stream()
            .map(entry -> DynamicTest.dynamicTest(entry.getKey(), () -> {
                Path path = Path.of(entry.getKey());
                assertTrue(Files.exists(path), "Module file should exist");

                String content = Files.readString(path, StandardCharsets.UTF_8).trim();
                assertTrue(content.startsWith(entry.getValue()),
                    "Module should start with expected package declaration");
            }));
    }
}
