package edu.cs102.g04t06.game;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.stream.Stream;

import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;

// Generated by GPT-5 (Codex)
/**
 * Unit tests for game placeholder modules.
 *
 * @author CS102 Team G6
 * @version 1.0
 */
class GamePlaceholderModulesTest {

    @TestFactory
    Stream<DynamicTest> placeholderFilesRemainPackageOnly() {
        Map<String, String> filesToPackageLines = new LinkedHashMap<>();
        filesToPackageLines.put(
            "src/main/java/edu/cs102/g04t06/game/presentation/console/ConsoleUI.java",
            "package edu.cs102.g04t06.game.presentation.console;"
        );
        filesToPackageLines.put(
            "src/main/java/edu/cs102/g04t06/game/presentation/console/InputHandler.java",
            "package edu.cs102.g04t06.game.presentation.console;"
        );
        filesToPackageLines.put(
            "src/main/java/edu/cs102/g04t06/game/presentation/console/GameRenderer.java",
            "package edu.cs102.g04t06.game.presentation.console;"
        );
        filesToPackageLines.put(
            "src/main/java/edu/cs102/g04t06/game/infrastructure/data/ExcelDataLoader.java",
            "package edu.cs102.g04t06.game.infrastructure.data;"
        );
        filesToPackageLines.put(
            "src/main/java/edu/cs102/g04t06/game/rules/GameState.java",
            "package edu.cs102.g04t06.game.rules;"
        );
        filesToPackageLines.put(
            "src/main/java/edu/cs102/g04t06/game/rules/GameRules.java",
            "package edu.cs102.g04t06.game.rules;"
        );
        filesToPackageLines.put(
            "src/main/java/edu/cs102/g04t06/game/execution/ai/AIPlayer.java",
            "package edu.cs102.g04t06.game.execution.ai;"
        );
        filesToPackageLines.put(
            "src/main/java/edu/cs102/g04t06/game/execution/GameEngine.java",
            "package edu.cs102.g04t06.game.execution;"
        );
        filesToPackageLines.put(
            "src/main/java/edu/cs102/g04t06/game/execution/ActionResult.java",
            "package edu.cs102.g04t06.game.execution;"
        );
        filesToPackageLines.put(
            "src/main/java/edu/cs102/g04t06/game/execution/ActionExecutor.java",
            "package edu.cs102.g04t06.game.execution;"
        );

        return filesToPackageLines.entrySet().stream()
            .map(entry -> DynamicTest.dynamicTest(entry.getKey(), () -> {
                Path path = Path.of(entry.getKey());
                assertTrue(Files.exists(path), "File should exist");

                String content = readTrimmedFile(path);
                assertEquals(entry.getValue(), content);
            }));
    }

    private String readTrimmedFile(Path path) throws IOException {
        return Files.readString(path, StandardCharsets.UTF_8).trim();
    }
}
