package edu.cs102.g04t06.game.rules.valueobjects;

import edu.cs102.g04t06.game.rules.entities.GemColor;
import java.util.EnumMap;
import java.util.Map;
// Generated by Claude Sonnet 4.5
/**
 * Represents the cost to purchase a development card in Splendor.
 * 
 * <p>Cost is an immutable value object that stores the gem requirements
 * for purchasing a card. It provides methods to query the cost and calculate
 * the actual cost after applying player bonuses.</p>
 * 
 * <p>This class is immutable - once created, the cost cannot be changed.
 * Operations like afterBonuses() return a new Cost object.</p>
 * 
 * @author CS102 Team G6
 * @version 1.0
 * @since Sprint 1
 */
public class Cost {
    private final Map<GemColor, Integer> required;
    
    /**
     * Creates a new Cost with the specified gem requirements.
     * 
     * <p>Makes a defensive copy of the input map to ensure immutability.</p>
     * 
     * @param costMap Map of gem colors to required amounts
     */
    public Cost(Map<GemColor, Integer> costMap) {
        this.required = new EnumMap<>(costMap);
    }
    
    /**
     * Gets the number of gems required for a specific color.
     * 
     * @param color The gem color to query
     * @return Number of gems required, or 0 if this color is not required
     */
    public int getRequired(GemColor color) {
        return required.getOrDefault(color, 0);
    }
    
    /**
     * Gets the total number of gems required across all colors.
     * 
     * @return Sum of all gem requirements
     */
    public int getTotalGems() { 
        return required.values().stream()
                .mapToInt(Integer::intValue)
                .sum();
    }
    
    /**
     * Gets a copy of the cost requirements map.
     * 
     * <p>Returns a defensive copy to maintain immutability.</p>
     * 
     * @return Map of gem colors to required amounts
     */
    public Map<GemColor, Integer> asMap() {
        return new EnumMap<>(required);
    }
    
    /**
     * Calculates the actual cost after applying player bonuses.
     * 
     * <p>Player bonuses (from purchased cards) reduce the gem cost.
     * For example, if a card costs 3 white gems and the player has
     * 1 white bonus, the actual cost is 2 white gems.</p>
     * 
     * <p>If bonuses cover the entire cost for a color, that color
     * is not included in the returned Cost.</p>
     * 
     * @param bonuses Map of gem colors to bonus counts from player's cards
     * @return New Cost object with bonuses subtracted from requirements
     */
    public Cost afterBonuses(Map<GemColor, Integer> bonuses) {
        Map<GemColor, Integer> actualCost = new EnumMap<>(GemColor.class);
        
        for (GemColor color : required.keySet()) {
            int needed = required.get(color);
            int bonus = bonuses.getOrDefault(color, 0);
            int toPay = Math.max(0, needed - bonus);
            
            if (toPay > 0) {
                actualCost.put(color, toPay);
            }
        }
        
        return new Cost(actualCost);
    }
}