package edu.cs102.g04t06.game.presentation.console.old;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;

import org.junit.jupiter.api.Test;

import javafx.scene.layout.StackPane;

// Generated by GPT-5 (Codex)
/**
 * Unit tests for BaseStack view.
 *
 * @author CS102 Team G6
 * @version 1.0
 */

class BaseStackTest {

    @Test
    void declaresProtectedRootFieldOfTypeStackPane() throws NoSuchFieldException {
        Field rootField = BaseStack.class.getDeclaredField("root");

        assertEquals(StackPane.class, rootField.getType());
        assertTrue(Modifier.isProtected(rootField.getModifiers()));
    }

    @Test
    void hasPublicNoArgsConstructor() throws NoSuchMethodException {
        Constructor<BaseStack> constructor = BaseStack.class.getDeclaredConstructor();

        assertTrue(Modifier.isPublic(constructor.getModifiers()));
    }
}
