package edu.cs102.g04t06.game.presentation.console.old;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.lang.reflect.Constructor;
import java.lang.reflect.Modifier;

import org.junit.jupiter.api.Test;

import edu.cs102.g04t06.App;

// Generated by GPT-5 (Codex)
/**
 * Unit tests for Menu view.
 *
 */
class MenuTest {

    @Test
    void extendsBaseStack() {
        assertEquals(BaseStack.class, Menu.class.getSuperclass());
    }

    @Test
    void hasPublicConstructorAcceptingApp() throws NoSuchMethodException {
        Constructor<Menu> constructor = Menu.class.getDeclaredConstructor(App.class);

        assertTrue(Modifier.isPublic(constructor.getModifiers()));
    }
}
