package edu.cs102.g04t06.game.rules.valueobjects;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.EnumMap;
import java.util.Map;

import org.junit.jupiter.api.Test;

import edu.cs102.g04t06.game.rules.entities.GemColor;

// Generated by GPT-5 (Codex)
/**
 * Unit tests for GemCollection value object.
 *
 * @author CS102 Team G6
 * @version 1.0
 */
class GemCollectionTest {

    @Test
    void defaultConstructorCreatesEmptyCollection() {
        GemCollection collection = new GemCollection();

        assertTrue(collection.isEmpty());
        assertEquals(0, collection.getTotalCount());
        for (GemColor color : GemColor.values()) {
            assertEquals(0, collection.getCount(color));
        }
    }

    @Test
    void mapConstructorReadsValues() {
        Map<GemColor, Integer> gems = new EnumMap<>(GemColor.class);
        gems.put(GemColor.WHITE, 2);
        gems.put(GemColor.BLUE, 1);

        GemCollection collection = new GemCollection(gems);

        assertEquals(2, collection.getCount(GemColor.WHITE));
        assertEquals(1, collection.getCount(GemColor.BLUE));
        assertEquals(3, collection.getTotalCount());
    }

    @Test
    void addReturnsNewCollectionWithoutMutatingOriginal() {
        GemCollection original = new GemCollection();
        GemCollection updated = original.add(GemColor.RED, 3);

        assertEquals(0, original.getCount(GemColor.RED));
        assertEquals(3, updated.getCount(GemColor.RED));
    }

    @Test
    void subtractByColorThrowsWhenResultWouldBeNegative() {
        GemCollection collection = new GemCollection();

        assertThrows(IllegalArgumentException.class, () -> collection.subtract(GemColor.BLACK, 1));
    }

    @Test
    void subtractByCollectionReturnsDifference() {
        GemCollection mine = new GemCollection()
            .add(GemColor.WHITE, 4)
            .add(GemColor.BLUE, 2);
        GemCollection cost = new GemCollection()
            .add(GemColor.WHITE, 1)
            .add(GemColor.BLUE, 2);

        GemCollection result = mine.subtract(cost);

        assertEquals(3, result.getCount(GemColor.WHITE));
        assertEquals(0, result.getCount(GemColor.BLUE));
        assertEquals(3, result.getTotalCount());
    }

    @Test
    void subtractByCollectionThrowsWhenNotEnoughGems() {
        GemCollection mine = new GemCollection().add(GemColor.WHITE, 1);
        GemCollection cost = new GemCollection().add(GemColor.WHITE, 2);

        assertThrows(IllegalArgumentException.class, () -> mine.subtract(cost));
    }

    @Test
    void containsChecksAllColors() {
        GemCollection mine = new GemCollection()
            .add(GemColor.WHITE, 2)
            .add(GemColor.GREEN, 1);
        GemCollection affordable = new GemCollection().add(GemColor.WHITE, 2);
        GemCollection notAffordable = new GemCollection().add(GemColor.GREEN, 2);

        assertTrue(mine.contains(affordable));
        assertFalse(mine.contains(notAffordable));
    }

    @Test
    void asMapReturnsCopy() {
        GemCollection collection = new GemCollection().add(GemColor.WHITE, 2);

        Map<GemColor, Integer> copy = collection.asMap();
        copy.put(GemColor.WHITE, 99);

        assertEquals(2, collection.getCount(GemColor.WHITE));
    }
}
