package edu.cs102.g04t06.game.rules.valueobjects;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.EnumMap;
import java.util.Map;

import org.junit.jupiter.api.Test;

import edu.cs102.g04t06.game.rules.entities.GemColor;

// Generated by GPT-5 (Codex)
/**
 * Unit tests for GemCollection value object.
 *
 */
class GemCollectionTest {

    @Test
    void defaultConstructorCreatesEmptyCollection() {
        GemCollection gems = new GemCollection();

        assertTrue(gems.isEmpty());
        assertEquals(0, gems.getTotalCount());
        for (GemColor color : GemColor.values()) {
            assertEquals(0, gems.getCount(color));
        }
    }

    @Test
    void mapConstructorReadsProvidedValues() {
        Map<GemColor, Integer> seed = new EnumMap<>(GemColor.class);
        seed.put(GemColor.WHITE, 2);
        seed.put(GemColor.BLUE, 1);

        GemCollection gems = new GemCollection(seed);

        assertEquals(2, gems.getCount(GemColor.WHITE));
        assertEquals(1, gems.getCount(GemColor.BLUE));
        assertEquals(3, gems.getTotalCount());
    }

    @Test
    void addReturnsUpdatedCollectionWithoutMutatingOriginal() {
        GemCollection original = new GemCollection();
        GemCollection updated = original.add(GemColor.RED, 3);

        assertEquals(0, original.getCount(GemColor.RED));
        assertEquals(3, updated.getCount(GemColor.RED));
    }

    @Test
    void subtractByColorThrowsForNegativeResult() {
        GemCollection gems = new GemCollection();

        assertThrows(IllegalArgumentException.class, () -> gems.subtract(GemColor.BLACK, 1));
    }

    @Test
    void subtractCollectionReturnsDifference() {
        GemCollection wallet = new GemCollection()
            .add(GemColor.WHITE, 4)
            .add(GemColor.BLUE, 2);
        GemCollection cost = new GemCollection()
            .add(GemColor.WHITE, 1)
            .add(GemColor.BLUE, 2);

        GemCollection remaining = wallet.subtract(cost);

        assertEquals(3, remaining.getCount(GemColor.WHITE));
        assertEquals(0, remaining.getCount(GemColor.BLUE));
        assertEquals(3, remaining.getTotalCount());
    }

    @Test
    void subtractCollectionThrowsWhenInsufficient() {
        GemCollection wallet = new GemCollection().add(GemColor.WHITE, 1);
        GemCollection cost = new GemCollection().add(GemColor.WHITE, 2);

        assertThrows(IllegalArgumentException.class, () -> wallet.subtract(cost));
    }

    @Test
    void containsChecksAllColors() {
        GemCollection wallet = new GemCollection()
            .add(GemColor.WHITE, 2)
            .add(GemColor.GREEN, 1);

        GemCollection affordable = new GemCollection().add(GemColor.WHITE, 2);
        GemCollection notAffordable = new GemCollection().add(GemColor.GREEN, 2);

        assertTrue(wallet.contains(affordable));
        assertFalse(wallet.contains(notAffordable));
    }

    @Test
    void asMapReturnsCopy() {
        GemCollection gems = new GemCollection().add(GemColor.WHITE, 2);

        Map<GemColor, Integer> copy = gems.asMap();
        copy.put(GemColor.WHITE, 99);

        assertEquals(2, gems.getCount(GemColor.WHITE));
    }
}
