package edu.cs102.g04t06.game.presentation.console;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import edu.cs102.g04t06.game.rules.GameState;
import edu.cs102.g04t06.game.rules.entities.Card;
import edu.cs102.g04t06.game.rules.entities.GemColor;
import edu.cs102.g04t06.game.rules.entities.Noble;
import edu.cs102.g04t06.game.rules.entities.Player;
import edu.cs102.g04t06.game.rules.valueobjects.CardMarket;
import edu.cs102.g04t06.game.rules.valueobjects.Cost;
import edu.cs102.g04t06.game.rules.valueobjects.GemCollection;

// Generated by Claude Sonnet 4.6
/**
 * GameRendererTest
 *
 * Unit tests for {@link GameRenderer}.
 *
 * Every test captures output via a {@code ByteArrayOutputStream} so that
 * the real terminal is never touched. {@link GameRenderer#GameRenderer(PrintStream)}
 * accepts the injected stream, making each assertion purely in-memory.
 *
 * <p>All game-model objects used here are real instances (no mocking framework
 * is required). Stubs for {@link CardMarket} are provided as a private inner
 * class so tests can control which cards are returned by
 * {@code getVisibleCards()}.</p>
 */
class GameRendererTest {

    // -------------------------------------------------------------------------
    // Test infrastructure
    // -------------------------------------------------------------------------

    private ByteArrayOutputStream captureStream;
    private GameRenderer renderer;

    @BeforeEach
    void setUp() {
        captureStream = new ByteArrayOutputStream();
        renderer = new GameRenderer(new PrintStream(captureStream));
    }

    /** Returns the captured output as a plain String (ANSI codes included). */
    private String output() {
        return captureStream.toString();
    }

    /** Returns the captured output with all ANSI escape codes stripped. */
    private String plainOutput() {
        return output().replaceAll("\u001B\\[[;\\d]*m", "");
    }

    // -------------------------------------------------------------------------
    // Shared test fixtures
    // -------------------------------------------------------------------------

    /** Builds a minimal Player with a given name and some gems. */
    private Player makePlayer(String name, int turnOrder) {
        Player p = new Player(name, turnOrder);
        GemCollection startGems = new GemCollection();
        // Add 2 RED and 1 BLUE so gem counts are non-zero
        p.addGems(startGems.add(GemColor.RED, 2).add(GemColor.BLUE, 1));
        return p;
    }

    /** Builds a Card at the given tier with known attributes. */
    private Card makeCard(int tier, int points, GemColor bonus) {
        // Cost: 2 RED gems
        Cost cost = new Cost(Map.of(GemColor.RED, 2));
        return new Card(tier, points, bonus, cost);
    }

    /** Builds a Noble with 3 points requiring 3 WHITE and 3 RED bonuses. */
    private Noble makeNoble() {
        Map<GemColor, Integer> reqs = new EnumMap<>(GemColor.class);
        reqs.put(GemColor.WHITE, 3);
        reqs.put(GemColor.RED,   3);
        return new Noble(1, "Test Noble", reqs);
    }

    /**
     * Builds a minimal {@link GameState} with the supplied players, one noble,
     * and one visible card.
     */
    private GameState makeGameState(List<Player> players) {
        Noble noble = makeNoble();
        Card  card  = makeCard(1, 1, GemColor.GREEN);

        // CardMarket stub that returns a single visible card
        CardMarket market = new StubCardMarket(List.of(card));

        GemCollection bank = new GemCollection()
                .add(GemColor.WHITE, 4)
                .add(GemColor.RED,   3)
                .add(GemColor.BLUE,  2)
                .add(GemColor.GREEN, 1)
                .add(GemColor.BLACK, 2)
                .add(GemColor.GOLD,  5);

        return new GameState(players, market, bank, new ArrayList<>(List.of(noble)), 15);
    }

    // =========================================================================
    // Person 1 Tests — displayGameState
    // =========================================================================

    /**
     * displayGameState() must produce non-empty output.
     */
    @Test
    void displayGameState_producesNonEmptyOutput() {
        Player alice = makePlayer("Alice", 0);
        GameState state = makeGameState(List.of(alice));

        renderer.displayGameState(state);

        assertFalse(plainOutput().isBlank(),
                "displayGameState() should produce non-empty output");
    }

    /**
     * displayGameState() must include all visible cards.
     * The stub market returns one card with GemColor.GREEN bonus (label "G").
     */
    @Test
    void displayGameState_includesAllVisibleCards() {
        Player alice = makePlayer("Alice", 0);
        GameState state = makeGameState(List.of(alice));

        renderer.displayGameState(state);

        String out = plainOutput();
        assertTrue(out.contains("DEVELOPMENT CARDS"),
                "Output should contain the DEVELOPMENT CARDS section header");
        // The card has GemColor.GREEN bonus → label "G" and "Tier 1"
        assertTrue(out.contains("Tier 1"),
                "Output should list the tier-1 card from the market");
    }

    /**
     * displayGameState() must include gem bank information for every colour.
     */
    @Test
    void displayGameState_includesGemBankInfo() {
        Player alice = makePlayer("Alice", 0);
        GameState state = makeGameState(List.of(alice));

        renderer.displayGameState(state);

        String out = plainOutput();
        assertTrue(out.contains("GEM BANK"),
                "Output should contain the GEM BANK section header");
        // Bank has WHITE:4 → label W:4 should appear
        assertTrue(out.contains("W:4"),
                "Output should show WHITE gem count from the bank");
    }

    /**
     * displayGameState() must include the nobles section.
     */
    @Test
    void displayGameState_includesNobles() {
        Player alice = makePlayer("Alice", 0);
        GameState state = makeGameState(List.of(alice));

        renderer.displayGameState(state);

        String out = plainOutput();
        assertTrue(out.contains("NOBLES"),
                "Output should contain the NOBLES section header");
        // Noble has 3 pts → "3 pts" should appear
        assertTrue(out.contains("3 pts"),
                "Output should show the noble's point value");
    }

    // =========================================================================
    // Person 1 Tests — displayCurrentPlayer
    // =========================================================================

    /**
     * displayCurrentPlayer() must include the player's name.
     */
    @Test
    void displayCurrentPlayer_includesPlayerName() {
        Player alice = makePlayer("Alice", 0);

        renderer.displayCurrentPlayer(alice);

        assertTrue(plainOutput().contains("Alice"),
                "Output should contain the player's name");
    }

    /**
     * displayCurrentPlayer() must include the player's gem counts.
     * Alice has 2 RED and 1 BLUE.
     */
    @Test
    void displayCurrentPlayer_includesGemCounts() {
        Player alice = makePlayer("Alice", 0);

        renderer.displayCurrentPlayer(alice);

        String out = plainOutput();
        // formatGemCollection outputs "R:2" for 2 red gems
        assertTrue(out.contains("R:2"),
                "Output should show RED gem count (R:2)");
        assertTrue(out.contains("U:1"),
                "Output should show BLUE gem count (U:1)");
    }

    /**
     * displayCurrentPlayer() must include the player's card count.
     * Alice starts with 0 purchased cards.
     */
    @Test
    void displayCurrentPlayer_includesCardCount() {
        Player alice = makePlayer("Alice", 0);

        renderer.displayCurrentPlayer(alice);

        String out = plainOutput();
        assertTrue(out.contains("Cards"),
                "Output should contain a 'Cards' label");
        assertTrue(out.contains("0 purchased"),
                "Output should show the number of purchased cards");
    }

    /**
     * displayCurrentPlayer() must include the player's prestige points.
     * Alice has 0 pts initially; we buy a card to give her points.
     */
    @Test
    void displayCurrentPlayer_includesPoints() {
        Player alice = makePlayer("Alice", 0);
        // Give Alice a card worth 2 points
        alice.addCard(makeCard(1, 2, GemColor.WHITE));

        renderer.displayCurrentPlayer(alice);

        String out = plainOutput();
        assertTrue(out.contains("pts"),
                "Output should contain a points label");
        assertTrue(out.contains("2 pts"),
                "Output should show the correct prestige point total");
    }

    // =========================================================================
    // Person 2 Tests — displayActionMenu
    // =========================================================================

    /**
     * displayActionMenu() must show all four action options.
     */
    @Test
    void displayActionMenu_showsAllFourOptions() {
        renderer.displayActionMenu();

        String out = plainOutput();
        assertTrue(out.contains("[ 1 ]"), "Option 1 should be present");
        assertTrue(out.contains("[ 2 ]"), "Option 2 should be present");
        assertTrue(out.contains("[ 3 ]"), "Option 3 should be present");
        assertTrue(out.contains("[ 4 ]"), "Option 4 should be present");
        assertTrue(out.contains("three different gems"),  "Option 1 label should mention three different gems");
        assertTrue(out.contains("same colour"),           "Option 2 label should mention same colour");
        assertTrue(out.contains("Purchase"),              "Option 3 label should mention Purchase");
        assertTrue(out.contains("Reserve"),               "Option 4 label should mention Reserve");
    }

    // =========================================================================
    // Person 2 Tests — displayError
    // =========================================================================

    /**
     * displayError() must include the exact error message passed to it.
     */
    @Test
    void displayError_includesErrorMessage() {
        String errorMsg = "Not enough gems to purchase that card.";

        renderer.displayError(errorMsg);

        assertTrue(plainOutput().contains(errorMsg),
                "Output should contain the exact error message");
    }

    // =========================================================================
    // Person 2 Tests — displayWinner
    // =========================================================================

    /**
     * displayWinner() must show the winner's name.
     */
    @Test
    void displayWinner_showsWinnerName() {
        Player alice = makePlayer("Alice", 0);
        Player bob   = makePlayer("Bob",   1);
        alice.addCard(makeCard(2, 10, GemColor.BLUE)); // Alice wins with 10 pts

        renderer.displayWinner(alice, List.of(alice, bob));

        assertTrue(plainOutput().contains("Alice"),
                "Output should contain the winner's name");
    }

    // =========================================================================
    // Person 2 Tests — formatCard
    // =========================================================================

    /**
     * formatCard() must include the card's level, point value, bonus colour,
     * and cost information.
     */
    @Test
    void formatCard_includesLevelPointsBonusCost() {
        Card card = makeCard(2, 3, GemColor.RED);

        String result = renderer.formatCard(card);
        String plain  = result.replaceAll("\u001B\\[[;\\d]*m", "");

        assertTrue(plain.contains("Tier 2"),  "formatCard should include the tier level");
        assertTrue(plain.contains("3 pts"),   "formatCard should include the point value");
        assertTrue(plain.contains("R"),       "formatCard should include the bonus colour label");
        assertTrue(plain.contains("Cost:"),   "formatCard should include the cost label");
    }

    // =========================================================================
    // Person 2 Tests — formatNoble
    // =========================================================================

    /**
     * formatNoble() must include the noble's point value and its requirements.
     */
    @Test
    void formatNoble_includesPointsAndRequirements() {
        Noble noble = makeNoble(); // 3 pts, requires WHITE:3 RED:3

        String result = renderer.formatNoble(noble);
        String plain  = result.replaceAll("\u001B\\[[;\\d]*m", "");

        assertTrue(plain.contains("3 pts"),  "formatNoble should include the point value");
        assertTrue(plain.contains("Requires:"), "formatNoble should include the requirements label");
        assertTrue(plain.contains("W:3"),    "formatNoble should show WHITE:3 requirement");
        assertTrue(plain.contains("R:3"),    "formatNoble should show RED:3 requirement");
    }

    // =========================================================================
    // Person 2 Tests — formatGemCollection
    // =========================================================================

    /**
     * formatGemCollection() must show a count for every gem colour.
     */
    @Test
    void formatGemCollection_showsAllGemCounts() {
        GemCollection gems = new GemCollection()
                .add(GemColor.WHITE, 2)
                .add(GemColor.BLUE,  1)
                .add(GemColor.GREEN, 3)
                .add(GemColor.RED,   0)
                .add(GemColor.BLACK, 4)
                .add(GemColor.GOLD,  1);

        String result = renderer.formatGemCollection(gems);
        String plain  = result.replaceAll("\u001B\\[[;\\d]*m", "");

        assertTrue(plain.contains("W:2"), "Should show WHITE count");
        assertTrue(plain.contains("U:1"), "Should show BLUE count");
        assertTrue(plain.contains("G:3"), "Should show GREEN count");
        assertTrue(plain.contains("R:0"), "Should show RED count (even when 0)");
        assertTrue(plain.contains("K:4"), "Should show BLACK count");
        assertTrue(plain.contains("*:1"), "Should show GOLD count");
    }

    // =========================================================================
    // Stub inner class — CardMarket
    // =========================================================================

    /**
     * Minimal stub for {@link CardMarket}.
     *
     * CardMarket requires 3 lists of 20+ cards each (it shuffles and splits them).
     * We pad them with dummy cards so the constructor is satisfied, then override
     * getVisibleCards(int level) to return our controlled test list for level 1.
     */
    private static class StubCardMarket extends CardMarket {
        private final List<Card> visibleOverride;

        StubCardMarket(List<Card> visibleOverride) {
            super(makePadded(visibleOverride), makePadded(List.of()), makePadded(List.of()));
            this.visibleOverride = new ArrayList<>(visibleOverride);
        }

        /** Builds a list of 20 cards (the minimum CardMarket requires). */
        private static List<Card> makePadded(List<Card> seed) {
            List<Card> list = new ArrayList<>(seed);
            Cost dummyCost = new Cost(Map.of(GemColor.WHITE, 1));
            while (list.size() < 20) {
                list.add(new Card(1, 0, GemColor.WHITE, dummyCost));
            }
            return list;
        }

        @Override
        public List<Card> getVisibleCards(int level) {
            return level == 1 ? visibleOverride : super.getVisibleCards(level);
        }
    }
}
