package edu.cs102.g04t06.game.presentation.console;

import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import edu.cs102.g04t06.game.rules.entities.Card;
import edu.cs102.g04t06.game.rules.entities.GemColor;
import edu.cs102.g04t06.game.rules.entities.Noble;
import edu.cs102.g04t06.game.rules.entities.Player;
import edu.cs102.g04t06.game.rules.valueobjects.CardMarket;
import edu.cs102.g04t06.game.rules.valueobjects.Cost;
import edu.cs102.g04t06.game.rules.valueobjects.GemCollection;

/**
 * Unit tests for InputHandler input validation methods.
 * Test cases generated by Claude Opus 4.6 (Anthropic).
 *
 * @author CS102 Team G6
 * @version 1.0
 */
@DisplayName("InputHandler Tests")
class InputHandlerTest {

    // ==================== Setup ====================

    private InputHandler handler;

    @BeforeEach
    void setUp() {
        handler = new InputHandler();
    }

    // ==================== Helpers ====================

    /** Creates a CardMarket filled with 40 dummy cards per level. */
    private CardMarket makeCardMarket() {
        Cost zeroCost = new Cost(new EnumMap<>(GemColor.class));
        List<Card> level1 = new ArrayList<>();
        List<Card> level2 = new ArrayList<>();
        List<Card> level3 = new ArrayList<>();
        for (int i = 0; i < 40; i++) {
            level1.add(new Card(1, 0, GemColor.WHITE, zeroCost));
            level2.add(new Card(2, 1, GemColor.BLUE, zeroCost));
            level3.add(new Card(3, 2, GemColor.GREEN, zeroCost));
        }
        return new CardMarket(level1, level2, level3);
    }

    /** Creates a Noble with a single-colour requirement. */
    private Noble makeNoble(int points, GemColor color, int amount) {
        Map<GemColor, Integer> reqs = new EnumMap<>(GemColor.class);
        reqs.put(color, amount);
        return new Noble(points,"Test noble name", reqs);
    }

    // ==================== promptActionChoice() Tests ====================

    @Test
    @DisplayName("promptActionChoice returns 1 for choice 1")
    void promptActionChoiceReturnsOne() {
        assertEquals(1, handler.promptActionChoice(1));
    }

    @Test
    @DisplayName("promptActionChoice returns 4 for choice 4")
    void promptActionChoiceReturnsFour() {
        assertEquals(4, handler.promptActionChoice(4));
    }

    @Test
    @DisplayName("promptActionChoice accepts all boundary values 1-4")
    void promptActionChoiceAcceptsAllBoundaryValues() {
        assertEquals(1, handler.promptActionChoice(1));
        assertEquals(2, handler.promptActionChoice(2));
        assertEquals(3, handler.promptActionChoice(3));
        assertEquals(4, handler.promptActionChoice(4));
    }

    @Test
    @DisplayName("promptActionChoice throws on choice 0 (below range)")
    void promptActionChoiceThrowsOnZero() {
        assertThrows(IllegalArgumentException.class, () -> handler.promptActionChoice(0));
    }

    @Test
    @DisplayName("promptActionChoice throws on choice 5 (above range)")
    void promptActionChoiceThrowsOnFive() {
        assertThrows(IllegalArgumentException.class, () -> handler.promptActionChoice(5));
    }

    @Test
    @DisplayName("promptActionChoice throws on negative choice")
    void promptActionChoiceThrowsOnNegative() {
        assertThrows(IllegalArgumentException.class, () -> handler.promptActionChoice(-1));
    }

    // ==================== promptPlayerCount() Tests ====================

    @Test
    @DisplayName("promptPlayerCount returns 2 for minimum valid count")
    void promptPlayerCountReturnsTwo() {
        assertEquals(2, handler.promptPlayerCount(2));
    }

    @Test
    @DisplayName("promptPlayerCount returns 3 for middle valid count")
    void promptPlayerCountReturnsThree() {
        assertEquals(3, handler.promptPlayerCount(3));
    }

    @Test
    @DisplayName("promptPlayerCount returns 4 for maximum valid count")
    void promptPlayerCountReturnsFour() {
        assertEquals(4, handler.promptPlayerCount(4));
    }

    @Test
    @DisplayName("promptPlayerCount throws on count 1 (below range)")
    void promptPlayerCountThrowsOnOne() {
        assertThrows(IllegalArgumentException.class, () -> handler.promptPlayerCount(1));
    }

    @Test
    @DisplayName("promptPlayerCount throws on count 5 (above range)")
    void promptPlayerCountThrowsOnFive() {
        assertThrows(IllegalArgumentException.class, () -> handler.promptPlayerCount(5));
    }

    @Test
    @DisplayName("promptPlayerCount throws on count 0")
    void promptPlayerCountThrowsOnZero() {
        assertThrows(IllegalArgumentException.class, () -> handler.promptPlayerCount(0));
    }

    @Test
    @DisplayName("promptPlayerCount throws on negative count")
    void promptPlayerCountThrowsOnNegative() {
        assertThrows(IllegalArgumentException.class, () -> handler.promptPlayerCount(-1));
    }

    // ==================== promptPlayerNames() Tests ====================

    @Test
    @DisplayName("promptPlayerNames returns list with correct size for 2 names")
    void promptPlayerNamesReturnsTwoNames() {
        List<String> names = handler.promptPlayerNames(List.of("Alice", "Bob"));
        assertEquals(2, names.size());
    }

    @Test
    @DisplayName("promptPlayerNames returns list with correct size for 4 names")
    void promptPlayerNamesReturnsFourNames() {
        List<String> names = handler.promptPlayerNames(List.of("Alice", "Bob", "Charlie", "Diana"));
        assertEquals(4, names.size());
    }

    @Test
    @DisplayName("promptPlayerNames preserves name order")
    void promptPlayerNamesPreservesOrder() {
        List<String> names = handler.promptPlayerNames(List.of("Alice", "Bob", "Charlie"));
        assertEquals("Alice", names.get(0));
        assertEquals("Bob", names.get(1));
        assertEquals("Charlie", names.get(2));
    }

    @Test
    @DisplayName("promptPlayerNames returns a defensive copy")
    void promptPlayerNamesReturnsDefensiveCopy() {
        List<String> input = new ArrayList<>(List.of("Alice", "Bob"));
        List<String> result = handler.promptPlayerNames(input);
        input.add("Extra");
        assertEquals(2, result.size());
    }

    @Test
    @DisplayName("promptPlayerNames throws on empty name")
    void promptPlayerNamesThrowsOnEmptyName() {
        assertThrows(IllegalArgumentException.class,
            () -> handler.promptPlayerNames(List.of("Alice", "")));
    }

    @Test
    @DisplayName("promptPlayerNames throws on blank (whitespace-only) name")
    void promptPlayerNamesThrowsOnBlankName() {
        assertThrows(IllegalArgumentException.class,
            () -> handler.promptPlayerNames(List.of("Alice", "   ")));
    }

    @Test
    @DisplayName("promptPlayerNames throws on null name")
    void promptPlayerNamesThrowsOnNullName() {
        List<String> names = new ArrayList<>();
        names.add("Alice");
        names.add(null);
        assertThrows(IllegalArgumentException.class, () -> handler.promptPlayerNames(names));
    }

    @Test
    @DisplayName("promptPlayerNames accepts names with internal spaces")
    void promptPlayerNamesAcceptsNamesWithInternalSpaces() {
        List<String> names = handler.promptPlayerNames(List.of("Alice Smith", "Bob Jones"));
        assertEquals("Alice Smith", names.get(0));
        assertEquals("Bob Jones", names.get(1));
    }

    // ==================== promptGemSelection() Tests ====================

    @Test
    @DisplayName("promptGemSelection returns correct GemCollection for 3 different colours")
    void promptGemSelectionReturnsDifferentColours() {
        GemCollection gems = handler.promptGemSelection(3,
            List.of(GemColor.WHITE, GemColor.BLUE, GemColor.GREEN));
        assertEquals(1, gems.getCount(GemColor.WHITE));
        assertEquals(1, gems.getCount(GemColor.BLUE));
        assertEquals(1, gems.getCount(GemColor.GREEN));
        assertEquals(3, gems.getTotalCount());
    }

    @Test
    @DisplayName("promptGemSelection returns correct GemCollection for 2 same colour")
    void promptGemSelectionReturnsTwoOfSameColour() {
        GemCollection gems = handler.promptGemSelection(2,
            List.of(GemColor.RED, GemColor.RED));
        assertEquals(2, gems.getCount(GemColor.RED));
        assertEquals(2, gems.getTotalCount());
    }

    @Test
    @DisplayName("promptGemSelection returns correct GemCollection for 1 gem")
    void promptGemSelectionReturnsSingleGem() {
        GemCollection gems = handler.promptGemSelection(1, List.of(GemColor.BLACK));
        assertEquals(1, gems.getCount(GemColor.BLACK));
        assertEquals(1, gems.getTotalCount());
    }

    @Test
    @DisplayName("promptGemSelection does not include GOLD in the returned collection")
    void promptGemSelectionNeverReturnsGold() {
        GemCollection gems = handler.promptGemSelection(3,
            List.of(GemColor.WHITE, GemColor.BLUE, GemColor.GREEN));
        assertEquals(0, gems.getCount(GemColor.GOLD));
    }

    @Test
    @DisplayName("promptGemSelection throws when GOLD is included")
    void promptGemSelectionThrowsOnGold() {
        assertThrows(IllegalArgumentException.class,
            () -> handler.promptGemSelection(1, List.of(GemColor.GOLD)));
    }

    @Test
    @DisplayName("promptGemSelection throws when colour list size does not match count")
    void promptGemSelectionThrowsOnWrongCount() {
        assertThrows(IllegalArgumentException.class,
            () -> handler.promptGemSelection(3, List.of(GemColor.WHITE, GemColor.BLUE)));
    }

    @Test
    @DisplayName("promptGemSelection throws when too many colours are supplied")
    void promptGemSelectionThrowsOnTooManyColours() {
        assertThrows(IllegalArgumentException.class,
            () -> handler.promptGemSelection(2,
                List.of(GemColor.WHITE, GemColor.BLUE, GemColor.GREEN)));
    }

    @Test
    @DisplayName("promptGemSelection accepts all five non-GOLD colours")
    void promptGemSelectionAcceptsAllNonGoldColours() {
        GemCollection gems = handler.promptGemSelection(5,
            List.of(GemColor.WHITE, GemColor.BLUE, GemColor.GREEN,
                    GemColor.RED, GemColor.BLACK));
        assertEquals(5, gems.getTotalCount());
        assertEquals(0, gems.getCount(GemColor.GOLD));
    }

    // ==================== promptGemsToReturn() Tests ====================

    @Test
    @DisplayName("promptGemsToReturn returns correct GemCollection for a single gem")
    void promptGemsToReturnReturnsSingleGem() {
        Player player = new Player("Alice", 0);
        player.addGems(new GemCollection().add(GemColor.WHITE, 3));

        GemCollection toReturn = handler.promptGemsToReturn(player, 1,
            List.of(GemColor.WHITE));

        assertEquals(1, toReturn.getCount(GemColor.WHITE));
        assertEquals(1, toReturn.getTotalCount());
    }

    @Test
    @DisplayName("promptGemsToReturn returns correct GemCollection for multiple gems")
    void promptGemsToReturnReturnsMultipleGems() {
        Player player = new Player("Alice", 0);
        player.addGems(new GemCollection()
            .add(GemColor.WHITE, 3)
            .add(GemColor.BLUE, 3));

        GemCollection toReturn = handler.promptGemsToReturn(player, 2,
            List.of(GemColor.WHITE, GemColor.BLUE));

        assertEquals(1, toReturn.getCount(GemColor.WHITE));
        assertEquals(1, toReturn.getCount(GemColor.BLUE));
        assertEquals(2, toReturn.getTotalCount());
    }

    @Test
    @DisplayName("promptGemsToReturn throws when player does not hold the requested gem colour")
    void promptGemsToReturnThrowsWhenPlayerLacksColour() {
        Player player = new Player("Alice", 0);
        player.addGems(new GemCollection().add(GemColor.WHITE, 2));

        assertThrows(IllegalArgumentException.class,
            () -> handler.promptGemsToReturn(player, 1, List.of(GemColor.RED)));
    }

    @Test
    @DisplayName("promptGemsToReturn throws when requested amount exceeds player holdings")
    void promptGemsToReturnThrowsWhenAmountExceedsHoldings() {
        Player player = new Player("Alice", 0);
        player.addGems(new GemCollection().add(GemColor.BLUE, 1));

        assertThrows(IllegalArgumentException.class,
            () -> handler.promptGemsToReturn(player, 2,
                List.of(GemColor.BLUE, GemColor.BLUE)));
    }

    @Test
    @DisplayName("promptGemsToReturn throws when gem list size does not match excessCount")
    void promptGemsToReturnThrowsOnWrongCount() {
        Player player = new Player("Alice", 0);
        player.addGems(new GemCollection().add(GemColor.WHITE, 3));

        assertThrows(IllegalArgumentException.class,
            () -> handler.promptGemsToReturn(player, 2, List.of(GemColor.WHITE)));
    }

    // ==================== promptNobleSelection() Tests ====================

    @Test
    @DisplayName("promptNobleSelection returns the first noble for selection 1")
    void promptNobleSelectionReturnsFirstNoble() {
        Noble noble1 = makeNoble(3, GemColor.WHITE, 4);
        Noble noble2 = makeNoble(3, GemColor.BLUE, 4);

        assertSame(noble1, handler.promptNobleSelection(List.of(noble1, noble2), 1));
    }

    @Test
    @DisplayName("promptNobleSelection returns the second noble for selection 2")
    void promptNobleSelectionReturnsSecondNoble() {
        Noble noble1 = makeNoble(3, GemColor.WHITE, 4);
        Noble noble2 = makeNoble(3, GemColor.BLUE, 4);

        assertSame(noble2, handler.promptNobleSelection(List.of(noble1, noble2), 2));
    }

    @Test
    @DisplayName("promptNobleSelection returns the only noble in a one-element list")
    void promptNobleSelectionReturnsSingleNoble() {
        Noble noble = makeNoble(3, GemColor.RED, 3);

        assertSame(noble, handler.promptNobleSelection(List.of(noble), 1));
    }

    @Test
    @DisplayName("promptNobleSelection throws on selection 0 (below range)")
    void promptNobleSelectionThrowsOnZero() {
        Noble noble = makeNoble(3, GemColor.RED, 3);

        assertThrows(IllegalArgumentException.class,
            () -> handler.promptNobleSelection(List.of(noble), 0));
    }

    @Test
    @DisplayName("promptNobleSelection throws when selection exceeds list size")
    void promptNobleSelectionThrowsOnOutOfRange() {
        Noble noble = makeNoble(3, GemColor.GREEN, 3);

        assertThrows(IllegalArgumentException.class,
            () -> handler.promptNobleSelection(List.of(noble), 5));
    }

    // ==================== promptCardSelection() Tests ====================

    @Test
    @DisplayName("promptCardSelection returns the first visible card for selection 1")
    void promptCardSelectionReturnsFirstVisibleCard() {
        CardMarket market = makeCardMarket();
        Card expected = market.getVisibleCards(1).get(0);

        assertSame(expected, handler.promptCardSelection(market, 1, false, List.of(), 1));
    }

    @Test
    @DisplayName("promptCardSelection returns the third visible card for selection 3")
    void promptCardSelectionReturnsThirdVisibleCard() {
        CardMarket market = makeCardMarket();
        Card expected = market.getVisibleCards(1).get(2);

        assertSame(expected, handler.promptCardSelection(market, 1, false, List.of(), 3));
    }

    @Test
    @DisplayName("promptCardSelection returns a reserved card when includeReserved is true")
    void promptCardSelectionReturnsReservedCard() {
        CardMarket market = makeCardMarket();
        Cost zeroCost = new Cost(new EnumMap<>(GemColor.class));
        Card reservedCard = new Card(1, 5, GemColor.BLACK, zeroCost);

        // 4 visible cards at level 1 → reserved card is option 5
        assertSame(reservedCard,
            handler.promptCardSelection(market, 1, true, List.of(reservedCard), 5));
    }

    @Test
    @DisplayName("promptCardSelection ignores reserved cards when includeReserved is false")
    void promptCardSelectionIgnoresReservedWhenFlagFalse() {
        CardMarket market = makeCardMarket();
        Cost zeroCost = new Cost(new EnumMap<>(GemColor.class));
        Card reservedCard = new Card(1, 5, GemColor.BLACK, zeroCost);
        Card expected = market.getVisibleCards(1).get(0);

        // Only 4 options exist; selecting 1 should give the first visible card
        assertSame(expected,
            handler.promptCardSelection(market, 1, false, List.of(reservedCard), 1));
    }

    @Test
    @DisplayName("promptCardSelection throws on selection 0 (below range)")
    void promptCardSelectionThrowsOnZero() {
        CardMarket market = makeCardMarket();

        assertThrows(IllegalArgumentException.class,
            () -> handler.promptCardSelection(market, 1, false, List.of(), 0));
    }

    @Test
    @DisplayName("promptCardSelection throws when selection exceeds number of available cards")
    void promptCardSelectionThrowsOnOutOfRange() {
        CardMarket market = makeCardMarket();

        assertThrows(IllegalArgumentException.class,
            () -> handler.promptCardSelection(market, 1, false, List.of(), 99));
    }

    @Test
    @DisplayName("promptCardSelection works correctly for level 3 market cards")
    void promptCardSelectionWorksForLevel3() {
        CardMarket market = makeCardMarket();
        Card expected = market.getVisibleCards(3).get(3);

        assertSame(expected, handler.promptCardSelection(market, 3, false, List.of(), 4));
    }
}
